const $=s=>document.querySelector(s);let mode='login',account=null,catalog=[];
async function api(path,data){const r=await fetch('/api/'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},...(data?{body:JSON.stringify(data)}:{})});let result;try{result=await r.json();}catch{throw Error('Không đọc được phản hồi. Thử tải lại trang nhé.');}if(!r.ok)throw Error(result.error||'Không kết nối được tài khoản.');return result;}
function status(t){$('#status').textContent=t;}
function render(){ $('#auth-panel').hidden=!!account;$('#profile').hidden=!account;if(!account)return;$('#welcome').textContent='Chào '+account.nickname+'!';$('#email').textContent=account.email;$('#coins').textContent=account.coins;$('#daily').disabled=!account.dailyAvailable;$('#daily').textContent=account.dailyAvailable?'Nhận 75 xu':'Đã nhận hôm nay';$('#rename').elements.nickname.value=account.nickname;$('#inventory').replaceChildren();for(const item of catalog){const article=document.createElement('article'),h=document.createElement('h3'),p=document.createElement('p'),b=document.createElement('button');h.textContent=item.name;p.textContent=item.description+' · '+item.price+' xu';const owned=account.owned.includes(item.id),active=account.equipped[item.slot]===item.id;b.textContent=active?'Đang dùng · Tháo':owned?'Trang bị':'Mua';b.onclick=()=>run(b,async()=>{const r=await api(owned?'shop/equip':'shop/buy',owned?{itemId:active?null:item.id,slot:item.slot}:{itemId:item.id});account=r.account;render();status(owned?'Đã cập nhật trang bị.':'Mua thành công. Bấm Trang bị để dùng.');});article.append(h,p,b);$('#inventory').append(article);}}
async function run(button,fn){button.disabled=true;try{await fn();}catch(e){status(e.message);}finally{if(button.isConnected)button.disabled=false;if(account&&!account.dailyAvailable)$('#daily').disabled=true;}}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#nickname-label').hidden=mode!=='signup';const form=$('#auth-form');form.elements.nickname.required=mode==='signup';form.elements.password.minLength=mode==='signup'?10:1;form.elements.password.autocomplete=mode==='signup'?'new-password':'current-password';form.querySelector('button').textContent=mode==='signup'?'Tạo nick':'Đăng nhập';$('#password-note').textContent=mode==='signup'?'Mật khẩu từ 10 đến 128 ký tự.':'Dùng email và mật khẩu đã đăng ký.';});
$('#auth-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget;run(f.querySelector('button'),async()=>{const r=await api('auth/'+mode,Object.fromEntries(new FormData(f)));f.elements.password.value='';account=r.account;render();status(account?'Đăng nhập thành công.':r.message);});};
$('#logout').onclick=e=>run(e.currentTarget,async()=>{await api('auth/logout',{});account=null;render();status('Đã đăng xuất.');});
$('#daily').onclick=e=>run(e.currentTarget,async()=>{account=(await api('shop/daily',{})).account;render();status('Đã nhận 75 xu vào tài khoản.');});
$('#rename').onsubmit=e=>{e.preventDefault();const f=e.currentTarget;run(f.querySelector('button'),async()=>{account=(await api('auth/profile',{nickname:f.elements.nickname.value})).account;render();status('Đã lưu biệt danh.');});};
try{const me=await api('auth/me');if(!me.configured){status('Tạo nick đang chờ kích hoạt máy chủ. Bạn vẫn có thể chơi Battle BETA và dùng shop chơi khách.');}else{catalog=(await api('shop/catalog')).catalog;account=me.account;render();status(account?'Nick đã được kết nối.':'Đăng nhập hoặc tạo nick để lưu hồ sơ và đồ trực tuyến.');}}catch(e){status(e.message);}
