// Confirmation links may return tokens in the fragment. Login uses server cookies; never persist these tokens.
const confirmationReturned=location.hash.includes('access_token=');if(location.hash)history.replaceState(null,'',location.pathname+location.search);
const $=s=>document.querySelector(s);let mode='login',account=null,catalog=[];
async function api(path,data){const r=await fetch('/api/'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},...(data?{body:JSON.stringify(data)}:{})});let result;try{result=await r.json();}catch{throw Error('Không đọc được phản hồi. Thử tải lại trang nhé.');}if(!r.ok)throw Error(result.error||'Không kết nối được tài khoản.');return result;}
function status(t){$('#status').textContent=t;}
function render(){ $('#auth-panel').hidden=!!account;$('#profile').hidden=!account;$('#admin-panel').hidden=account?.role!=='admin';if(!account)return;$('#welcome').textContent='Chào '+account.nickname+'!';$('#email').textContent=account.email;$('#coins').textContent=account.coins;$('#daily').disabled=!account.dailyAvailable;$('#daily').textContent=account.dailyAvailable?'Nhận 75 xu':'Đã nhận hôm nay';$('#rename').elements.nickname.value=account.nickname;$('#inventory').replaceChildren();for(const item of catalog){const article=document.createElement('article'),h=document.createElement('h3'),p=document.createElement('p'),b=document.createElement('button');h.textContent=item.name;p.textContent=item.description+' · '+item.price+' xu';const owned=account.owned.includes(item.id),active=account.equipped[item.slot]===item.id;b.textContent=active?'Đang dùng · Tháo':owned?'Trang bị':'Mua';b.onclick=()=>run(b,async()=>{const r=await api(owned?'shop/equip':'shop/buy',owned?{itemId:active?null:item.id,slot:item.slot}:{itemId:item.id});account=r.account;render();status(owned?'Đã cập nhật trang bị.':'Mua thành công. Bấm Trang bị để dùng.');});article.append(h,p,b);$('#inventory').append(article);}}
async function run(button,fn){button.disabled=true;try{await fn();}catch(e){status(e.message);}finally{if(button.isConnected)button.disabled=false;if(account&&!account.dailyAvailable)$('#daily').disabled=true;}}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#nickname-label').hidden=mode!=='signup';const form=$('#auth-form');form.elements.nickname.required=mode==='signup';form.elements.password.minLength=mode==='signup'?10:1;form.elements.password.autocomplete=mode==='signup'?'new-password':'current-password';form.querySelector('button').textContent=mode==='signup'?'Tạo nick':'Đăng nhập';$('#password-note').textContent=mode==='signup'?'Mật khẩu từ 10 đến 128 ký tự.':'Dùng email và mật khẩu đã đăng ký.';});
$('#auth-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget;run(f.querySelector('button'),async()=>{const r=await api('auth/'+mode,Object.fromEntries(new FormData(f)));f.elements.password.value='';account=r.account;render();status(account?'Đăng nhập thành công.':r.message);});};
$('#logout').onclick=e=>run(e.currentTarget,async()=>{await api('auth/logout',{});account=null;render();status('Đã đăng xuất.');});
$('#daily').onclick=e=>run(e.currentTarget,async()=>{account=(await api('shop/daily',{})).account;render();status('Đã nhận 75 xu vào tài khoản.');});
$('#rename').onsubmit=e=>{e.preventDefault();const f=e.currentTarget;run(f.querySelector('button'),async()=>{account=(await api('auth/profile',{nickname:f.elements.nickname.value})).account;render();status('Đã lưu biệt danh.');});};
try{const me=await api('auth/me');if(!me.configured){status('Tạo nick đang chờ kích hoạt máy chủ. Bạn vẫn có thể chơi Battle BETA và dùng shop chơi khách.');}else{catalog=(await api('shop/catalog')).catalog;account=me.account;render();status(account?'Nick đã được kết nối.':confirmationReturned?'Email đã được xác nhận. Đăng nhập để vào nick.':'Đăng nhập hoặc tạo nick để lưu hồ sơ và đồ trực tuyến.');}}catch(e){status(e.message);}

for(const [id,enabled] of [['admin-enable',true],['admin-disable',false]])$( '#'+id).onclick=e=>run(e.currentTarget,async()=>{const r=await api('shooter/admin-boost',{enabled});status(r.adminBoostActive?'Đã bật hỗ trợ tài nguyên.':'Đã tắt hỗ trợ tài nguyên.');});

// Admin-only resource sharing monitor
const fmtGb=b=>(b/1073741824).toFixed(b<1e6?6:4)+' GB/s';
function drawShare(history){const c=$('#share-chart'),x=c.getContext('2d'),W=c.width,H=c.height;x.clearRect(0,0,W,H);const cs=getComputedStyle(c);const maxCpu=Math.max(50,...history.map(h=>h.cpuMs)),maxB=Math.max(1e5,...history.map(h=>h.bytes));x.globalAlpha=.25;x.strokeStyle=cs.color;for(let i=1;i<4;i++){x.beginPath();x.moveTo(0,H*i/4);x.lineTo(W,H*i/4);x.stroke();}x.globalAlpha=1;
 const line=(key,max,color)=>{x.strokeStyle=color;x.lineWidth=2;x.beginPath();history.forEach((h,i)=>{const px=i/(history.length-1)*W,py=H-6-(h[key]/max)*(H-24);i?x.lineTo(px,py):x.moveTo(px,py);});x.stroke();};
 line('cpuMs',maxCpu,'#3ddc84');line('bytes',maxB,'#4aa3ff');x.font='12px sans-serif';x.fillStyle='#3ddc84';x.fillText('CPU (đỉnh '+maxCpu.toFixed(0)+' ms/s)',8,14);x.fillStyle='#4aa3ff';x.fillText('RAM/dữ liệu (đỉnh '+fmtGb(maxB)+')',200,14);x.fillStyle=cs.color;x.fillText('60 giây gần nhất',W-110,14);}
async function pollShare(){if(account?.role!=='admin'||$('#admin-panel').hidden)return;try{const r=await api('shooter/admin-resource-stats',{});const last=r.history.slice(-5),cpu=last.reduce((a,h)=>a+h.cpuMs,0)/last.length,bytes=last.reduce((a,h)=>a+h.bytes,0)/last.length;
 const cores=r.hosts.reduce((a,h)=>a+h.cores,0)||1,pct=cpu/10/cores;const level=cpu<1?'Không chia sẻ':cpu<20?'Ít':cpu<60?'Vừa':'Nhiều';
 $('#share-level').textContent=(r.adminBoostActive?'Đang bật':'Đang tắt')+' · Mức chia sẻ: '+level;$('#share-cpu').textContent=cpu.toFixed(1)+' ms/s ('+pct.toFixed(2)+'% CPU)';$('#share-ram').textContent=fmtGb(bytes);$('#share-hosts').textContent=r.hosts.filter(h=>h.host).length+' / '+r.hosts.length;
 const t=$('#share-table');t.replaceChildren();const head=t.insertRow();for(const h of ['Người chơi','Luồng CPU','RAM máy','CPU ms/s','GB/s','Ping','Mất gói','Tổng'])head.appendChild(Object.assign(document.createElement('th'),{textContent:h}));
 for(const h of r.hosts){const row=t.insertRow();for(const v of [h.name+(h.host?' ✓':''),h.cores,h.memoryGb?h.memoryGb+' GB':'?',h.cpuMs.toFixed(1),fmtGb(h.bytes),h.rtt==null?'-':h.rtt.toFixed(0)+' ms',(h.packetLoss*100).toFixed(1)+'%',(h.totalCpuMs/1000).toFixed(1)+' s CPU · '+(h.totalBytes/1048576).toFixed(2)+' MB'])row.insertCell().textContent=v;}
 drawShare(r.history);}catch(e){$('#share-level').textContent=e.message;}}
setInterval(pollShare,2000);setTimeout(pollShare,500);
