import {openGame,updateOnline} from './games.js';
const $=s=>document.querySelector(s), grid=$('#game-grid'), modal=$('#modal');
const games=[{id:'battle',name:'Game bắn nhau — BETA',category:'arcade',tag:'BETA 0.1',players:'1 người · 8 bot',description:'Bắn súng 2D, kỹ năng và vòng bo sinh tồn.'},{id:'runner',name:'Robot phiêu lưu',category:'arcade',tag:'ARCADE',players:'1 người',description:'Băng qua thành cổ, thu thập xu.'},{id:'blocks',name:'Phá gạch quỹ đạo',category:'arcade',tag:'ARCADE',players:'1 người',description:'Ba màn chơi giữa không gian.'},{id:'caro',name:'Cờ caro',category:'board',tag:'ĐẤU TRÍ',players:'2 người',description:'Một hàng cờ, ngàn nước tính.'},{id:'chess',name:'Cờ vua',category:'board',tag:'CHIẾN THUẬT',players:'2 người',description:'Nước đi nhỏ. Thế cờ lớn.'}];
let favorites=[];try{const saved=JSON.parse(localStorage.getItem('xa_favorites')||'[]');if(Array.isArray(saved))favorites=saved.filter(x=>games.some(g=>g.id===x));}catch{}
let view='all',filter='all',current=null,connected=false,modalMode='',toastTimer;
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function gameName(id){return games.find(g=>g.id===id)?.name||'Sảnh chờ';}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function renderGames(){const q=$('#search').value.toLocaleLowerCase('vi');const list=games.filter(g=>(filter==='all'||g.category===filter)&&(view!=='favorites'||favorites.includes(g.id))&&(g.name+' '+g.description).toLocaleLowerCase('vi').includes(q));grid.innerHTML=list.map(g=>'<article class="game-card"><div class="game-art '+g.id+'"><span class="game-tag">'+g.tag+'</span><button class="favorite '+(favorites.includes(g.id)?'selected':'')+'" data-favorite="'+g.id+'" aria-label="'+(favorites.includes(g.id)?'Bỏ yêu thích ':'Yêu thích ')+g.name+'" aria-pressed="'+favorites.includes(g.id)+'">'+(favorites.includes(g.id)?'♥':'♡')+'</button>'+'<img class="game-cover" src="/cover-'+(g.id==='battle'?'blocks':g.id)+'-v2.webp" alt="Ảnh minh họa '+g.name+'" width="960" height="640" loading="lazy" decoding="async">'+'</div><div class="game-info"><div class="game-info-top"><h3>'+g.name+'</h3></div><p>'+g.description+'</p><div class="game-info-bottom"><span>'+g.players+'</span><span class="coming">'+(g.id==='chess'?'Sắp ra mắt':'Chơi ngay')+'</span><button class="game-detail" data-detail="'+g.id+'" aria-label="'+(g.id==='chess'?'Xem thông tin ':'Chơi ')+g.name+'">'+(g.id==='chess'?'Chi tiết ↗':'Chơi ngay ↗')+'</button></div></div></article>').join('');$('#empty-games').classList.toggle('hidden',list.length>0);$('#game-count').textContent=String(list.length).padStart(2,'0');$('#fav-count').textContent=favorites.length;}
function applyState(data){current=data;updateOnline(data);$('#online-count').textContent=data.online+' người đang ở sảnh';$('#room-count').textContent=data.rooms.length;$('#nav-room-count').textContent=data.rooms.length;$('#profile-button').textContent=data.me.name.slice(0,1).toUpperCase();$('#profile-button').setAttribute('aria-label','Biệt danh: '+data.me.name+'. Bấm để đổi.');const r=data.room,active=$('#active-room');active.classList.toggle('hidden',!r);active.classList.add('active-room');if(r){active.innerHTML='<span class="eyebrow muted">PHÒNG CỦA BẠN · '+escapeHTML(gameName(r.game))+'</span><h3>'+escapeHTML(r.title)+'</h3><div class="room-code"><span>'+escapeHTML(r.code)+'</span><button data-copy>Sao chép mã</button></div>'+r.members.map(m=>'<div class="member"><span>'+escapeHTML(m.name)+(m.host?' ♛':'')+'</span><span class="'+(m.ready?'is-ready':'')+'">'+(m.ready?'✓ Sẵn sàng':'Đang chờ')+'</span></div>').join('')+'<div class="room-controls"><button class="primary" data-ready>'+(data.me.ready?'Hủy sẵn sàng':'Sẵn sàng')+'</button><button class="secondary" data-leave>Rời phòng</button></div>'+(r.game==='caro'?'<div class="room-controls">'+(data.me.host?'<button data-start class="primary">Bắt đầu ván</button>':'')+(r.match?'<button data-watch>Vào bàn cờ</button>':'')+'</div><p class="room-hint">Hai người đầu phòng thi đấu, người còn lại xem trận. Cả hai sẵn sàng rồi chủ phòng bắt đầu.</p>':'<p class="room-hint">Phòng giao lưu. Arcade chơi riêng trên từng máy; cờ vua chưa mở.</p>')+'';}
const others=data.rooms.filter(x=>x.code!==data.me.room);$('#room-list').innerHTML=others.length?others.map(x=>'<div class="room-row"><div><strong>'+escapeHTML(x.title)+'</strong><small>'+escapeHTML(gameName(x.game))+' · '+x.count+'/8 người</small></div><button data-join="'+escapeHTML(x.code)+'">Vào ↗</button></div>').join(''):r?'':'<div class="room-empty"><span class="room-icon">▦</span><b>Sảnh đang chờ hội bạn</b><p>Tạo phòng đầu tiên rồi gửi mã<br>cho người bạn muốn rủ.</p></div>';}
function setConnected(value){connected=value;$('#connection').classList.toggle('offline',!value);$('#connection').innerHTML='<span class="tiny-dot"></span>'+(value?'Sảnh trực tuyến':'Đang kết nối lại');}
async function api(path,data={}){const response=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'Không thể kết nối.');applyState(result);return result;}
function showModal(mode,game){modalMode=mode;$('#form-error').textContent='';$('#modal-submit').classList.remove('hidden');$('#modal-submit').textContent='Tiếp tục ↗';const fields=$('#modal-fields');if(mode==='create'){$('#modal-title').textContent='Tạo phòng chờ';$('#modal-description').textContent='Chơi caro trực tuyến: 2 người thi đấu, tối đa 6 khán giả.';fields.innerHTML='<label class="field">Tên phòng<input name="title" maxlength="40" placeholder="Hội bạn của Xanh" required></label><label class="field">Game đang chờ<select name="game">'+games.filter(g=>g.id==='caro').map(g=>'<option value="'+g.id+'" '+((game||'caro')===g.id?'selected':'')+'>'+g.name+' — trực tuyến</option>').join('')+'</select></label>';$('#modal-submit').textContent='Tạo phòng ↗';}
else if(mode==='join'){$('#modal-title').textContent='Gặp nhau trong phòng';$('#modal-description').textContent='Nhập mã 6 ký tự mà bạn bè gửi cho bạn.';fields.innerHTML='<label class="field">Mã phòng<input name="code" maxlength="6" minlength="6" autocomplete="off" placeholder="VD: A1B2C3" required></label>';$('#modal-submit').textContent='Vào phòng ↗';}
else if(mode==='profile'){$('#modal-title').textContent='Bạn tên gì nhỉ?';$('#modal-description').textContent='Biệt danh này sẽ hiển thị với những người trong phòng.';fields.innerHTML='<label class="field">Biệt danh<input name="name" maxlength="24" value="'+escapeHTML(current?.me.name||'')+'" placeholder="Nhập biệt danh" required></label>';$('#modal-submit').textContent='Lưu biệt danh ↗';}
else{const g=games.find(x=>x.id===game);$('#modal-title').textContent=g.name;$('#modal-description').textContent=g.description;fields.innerHTML='<p>Game đang trong kế hoạch phát triển và chưa thể chơi. Bạn có thể đánh dấu yêu thích để tìm lại nhanh.</p><span class="coming">Sắp ra mắt · '+g.players+'</span>';$('#modal-submit').classList.add('hidden');}modal.showModal();}
document.addEventListener('click',async e=>{const fav=e.target.closest('[data-favorite]');if(fav){const id=fav.dataset.favorite;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];try{localStorage.setItem('xa_favorites',JSON.stringify(favorites));}catch{}renderGames();return;}const detail=e.target.closest('[data-detail]');if(detail){if(detail.dataset.detail==='battle'){location.assign('/battle');return;}if(detail.dataset.detail==='chess')showModal('detail','chess');else openGame(detail.dataset.detail);return;}const play=e.target.closest('[data-play]');if(play){openGame(play.dataset.play);return;}if(e.target.closest('[data-start]')){try{await api('start');openOnline();}catch(err){toast(err.message);}return;}if(e.target.closest('[data-watch]')){openOnline();return;}const join=e.target.closest('[data-join]');const action=e.target.closest('[data-ready],[data-leave],[data-copy]');if(join||action){try{if(join)await api('join',{code:join.dataset.join});else if(action.hasAttribute('data-ready'))await api('ready');else if(action.hasAttribute('data-leave'))await api('leave');else{await navigator.clipboard.writeText(current.room.code);toast('Đã sao chép mã phòng '+current.room.code);}}catch(err){toast(err.message||'Chưa sao chép được. Bạn có thể chọn mã phòng để sao chép.');}}});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});renderGames();}));document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));$('#page-label').textContent=view==='favorites'?'Yêu thích':view==='rooms'?'Phòng chơi':'Khám phá';$('#catalog-title').childNodes[0].textContent=view==='favorites'?'Game yêu thích ':'Kho game ';renderGames();if(view==='rooms')$('#lobby').scrollIntoView({behavior:'smooth',block:'start'});else $('#catalog').scrollIntoView({behavior:'smooth',block:'start'});}));
$('#search').addEventListener('input',renderGames);$('#create-room').onclick=()=>{if(current?.room){toast('Bạn đang ở một phòng. Hãy rời phòng trước khi tạo phòng mới.');$('#lobby').scrollIntoView({behavior:'smooth'});}else showModal('create');};$('#join-room').onclick=()=>showModal('join');$('#profile-button').onclick=()=>showModal('profile');$('#close-modal').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});$('#modal-form').addEventListener('submit',async e=>{e.preventDefault();const button=$('#modal-submit');button.disabled=true;$('#form-error').textContent='';try{const data=Object.fromEntries(new FormData(e.target));await api(modalMode==='create'?'rooms':modalMode,data);modal.close();toast(modalMode==='profile'?'Đã lưu biệt danh.':modalMode==='create'?'Phòng đã mở. Gửi mã cho bạn bè nhé!':'Bạn đã vào phòng.');}catch(err){$('#form-error').textContent=err.message||'Mất kết nối, bạn thử lại nhé.';}finally{button.disabled=false;}});
function openOnline(){openGame('caro',{online:true,state:current,sendMove:index=>api('move',{index})});}
$('#year').textContent=new Date().getFullYear();renderGames();const events=new EventSource('/api/events');events.onopen=()=>setConnected(true);events.onmessage=e=>{try{applyState(JSON.parse(e.data));setConnected(true);}catch{toast('Chưa nhận được trạng thái sảnh.');}};events.onerror=()=>setConnected(false);
