const $=s=>document.querySelector(s), grid=$('#game-grid'), modal=$('#modal');
const art={
runner:'<svg viewBox="0 0 300 180" aria-hidden="true"><path d="M0 130 150 75l150 55v50H0Z" fill="#152e38"/><path d="m0 160 150-66 150 66M55 180l95-86 95 86M120 180l30-86 30 86M0 130h300M0 155h300" fill="none" stroke="#3c7580" stroke-width="1"/><circle cx="235" cy="42" r="23" fill="#ebba6d"/><path d="m108 82 20-19 24 8 13 21-17 11-13-20-14 12 16 15-9 22-26 11-7-15 22-11-15-17Z" fill="#b8fa46"/><path d="m149 97 22 12 13-8 8 13-23 14-26-18" fill="#8ecc30"/><rect x="136" y="40" width="25" height="25" rx="8" fill="#d5ff8a"/><path d="m78 77-22 10m29 6-38 16m35 6-24 10" stroke="#7cadbf" stroke-width="4" stroke-linecap="round"/><path d="m222 141 14-24 14 24Z" fill="#dd7e61"/><path d="m39 145 8-17 9 17" fill="#8bbad0"/></svg>',
blocks:'<svg viewBox="0 0 300 180" aria-hidden="true"><path d="M30 24h240v135H30Z" fill="#251f39"/><g stroke="#352e4c" stroke-width="4"><rect x="53" y="39" width="45" height="19" rx="5" fill="#ae95e1"/><rect x="102" y="39" width="45" height="19" rx="5" fill="#ae95e1"/><rect x="151" y="39" width="45" height="19" rx="5" fill="#ae95e1"/><rect x="200" y="39" width="45" height="19" rx="5" fill="#ae95e1"/><rect x="53" y="61" width="45" height="19" rx="5" fill="#f4c385"/><rect x="102" y="61" width="45" height="19" rx="5" fill="#f4c385"/><rect x="151" y="61" width="45" height="19" rx="5" fill="#f4c385"/><rect x="200" y="61" width="45" height="19" rx="5" fill="#f4c385"/><rect x="53" y="83" width="45" height="19" rx="5" fill="#c5e799"/><rect x="102" y="83" width="45" height="19" rx="5" fill="#c5e799"/><rect x="200" y="83" width="45" height="19" rx="5" fill="#c5e799"/></g><path d="m168 116 14-20" stroke="#f8e9b3" stroke-width="3" stroke-dasharray="4 5"/><circle cx="163" cy="123" r="6" fill="#fff4ce"/><rect x="111" y="148" width="62" height="8" rx="4" fill="#aa8fdf"/><path d="m265 75 7-10m-10 23 12 2" stroke="#a48acf" stroke-width="3"/></svg>',
caro:'<svg viewBox="0 0 300 180" aria-hidden="true"><g transform="translate(85 18) rotate(8 65 70)"><rect x="-10" y="-8" width="150" height="158" rx="12" fill="#282819"/><path d="M43 0v138M88 0v138M0 45h132M0 91h132" stroke="#8f8f59" stroke-width="2"/><g stroke="#d7ea89" stroke-width="9" stroke-linecap="round"><path d="m11 11 20 22m0-22L11 33m42 25 24 23m0-23L53 81m46 23 22 22m0-22-22 22"/></g><circle cx="111" cy="23" r="13" fill="none" stroke="#e7b077" stroke-width="8"/><circle cx="21" cy="113" r="13" fill="none" stroke="#e7b077" stroke-width="8"/></g><path d="m56 41 5-12m-13 9 14 5m194 74 5-12m-13 9 14 5" stroke="#a9a864" stroke-width="2"/></svg>',
chess:'<svg viewBox="0 0 300 180" aria-hidden="true"><path d="m37 145 116-45 114 47-113 32Z" fill="#1b3328"/><path d="m61 135 115-26m-73 42 114-27m-76 39 112-27m-176-8 114 38m-76-53 116 39m-73-54 110 38" stroke="#6c9364" stroke-width="8"/><path d="M95 124h55l-5-13h-45Z" fill="#d7e8ac"/><path d="M108 109V89l-12-6 8-29 26-19 8 5-2 15 17 22-19 13-8-10-6 29Z" fill="#e6f0be"/><path d="m109 58 15-9" stroke="#748859" stroke-width="4"/><circle cx="128" cy="60" r="3" fill="#243d26"/><path d="M172 136h54l-6-12h-42Z" fill="#afc286"/><path d="M183 121h31l-6-38h-19Z" fill="#c6d697"/><circle cx="199" cy="73" r="15" fill="#d8e6ad"/><path d="m54 62 5-12m-13 9 14 5m183-13 5-12m-13 9 14 5" stroke="#8ab07b" stroke-width="2"/></svg>'};
const games=[{id:'runner',name:'Neon Runner',category:'arcade',tag:'ARCADE',players:'1 người',description:'Bứt tốc qua thế giới neon.'},{id:'blocks',name:'Phá gạch',category:'arcade',tag:'ARCADE',players:'1 người',description:'Một cú nảy, phá mọi giới hạn.'},{id:'caro',name:'Cờ caro',category:'board',tag:'ĐẤU TRÍ',players:'2 người',description:'Một hàng cờ, ngàn nước tính.'},{id:'chess',name:'Cờ vua',category:'board',tag:'CHIẾN THUẬT',players:'2 người',description:'Nước đi nhỏ. Thế cờ lớn.'}];
let favorites=[];try{const saved=JSON.parse(localStorage.getItem('xa_favorites')||'[]');if(Array.isArray(saved))favorites=saved.filter(x=>games.some(g=>g.id===x));}catch{}
let view='all',filter='all',current=null,connected=false,modalMode='',toastTimer;
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function gameName(id){return games.find(g=>g.id===id)?.name||'Sảnh chờ';}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function renderGames(){const q=$('#search').value.toLocaleLowerCase('vi');const list=games.filter(g=>(filter==='all'||g.category===filter)&&(view!=='favorites'||favorites.includes(g.id))&&(g.name+' '+g.description).toLocaleLowerCase('vi').includes(q));grid.innerHTML=list.map(g=>'<article class="game-card"><div class="game-art '+g.id+'"><span class="game-tag">'+g.tag+'</span><button class="favorite '+(favorites.includes(g.id)?'selected':'')+'" data-favorite="'+g.id+'" aria-label="'+(favorites.includes(g.id)?'Bỏ yêu thích ':'Yêu thích ')+g.name+'" aria-pressed="'+favorites.includes(g.id)+'">'+(favorites.includes(g.id)?'♥':'♡')+'</button>'+art[g.id]+'</div><div class="game-info"><div class="game-info-top"><h3>'+g.name+'</h3></div><p>'+g.description+'</p><div class="game-info-bottom"><span>'+g.players+'</span><span class="coming">Sắp ra mắt</span><button class="game-detail" data-detail="'+g.id+'" aria-label="Xem thông tin '+g.name+'">Chi tiết ↗</button></div></div></article>').join('');$('#empty-games').classList.toggle('hidden',list.length>0);$('#game-count').textContent=String(list.length).padStart(2,'0');$('#fav-count').textContent=favorites.length;}
function applyState(data){current=data;$('#online-count').textContent=data.online+' người đang ở sảnh';$('#room-count').textContent=data.rooms.length;$('#nav-room-count').textContent=data.rooms.length;$('#profile-button').textContent=data.me.name.slice(0,1).toUpperCase();$('#profile-button').setAttribute('aria-label','Biệt danh: '+data.me.name+'. Bấm để đổi.');const r=data.room,active=$('#active-room');active.classList.toggle('hidden',!r);active.classList.add('active-room');if(r){active.innerHTML='<span class="eyebrow muted">PHÒNG CỦA BẠN · '+escapeHTML(gameName(r.game))+'</span><h3>'+escapeHTML(r.title)+'</h3><div class="room-code"><span>'+escapeHTML(r.code)+'</span><button data-copy>Sao chép mã</button></div>'+r.members.map(m=>'<div class="member"><span>'+escapeHTML(m.name)+(m.host?' ♛':'')+'</span><span class="'+(m.ready?'is-ready':'')+'">'+(m.ready?'✓ Sẵn sàng':'Đang chờ')+'</span></div>').join('')+'<div class="room-controls"><button class="primary" data-ready>'+(data.me.ready?'Hủy sẵn sàng':'Sẵn sàng')+'</button><button class="secondary" data-leave>Rời phòng</button></div><p class="room-hint">Đây là phòng chờ thử nghiệm. Game '+escapeHTML(gameName(r.game))+' chưa mở chơi.</p>';}
const others=data.rooms.filter(x=>x.code!==data.me.room);$('#room-list').innerHTML=others.length?others.map(x=>'<div class="room-row"><div><strong>'+escapeHTML(x.title)+'</strong><small>'+escapeHTML(gameName(x.game))+' · '+x.count+'/8 người</small></div><button data-join="'+escapeHTML(x.code)+'">Vào ↗</button></div>').join(''):r?'':'<div class="room-empty"><span class="room-icon">▦</span><b>Sảnh đang chờ hội bạn</b><p>Tạo phòng đầu tiên rồi gửi mã<br>cho người bạn muốn rủ.</p></div>';}
function setConnected(value){connected=value;$('#connection').classList.toggle('offline',!value);$('#connection').innerHTML='<span class="tiny-dot"></span>'+(value?'Sảnh trực tuyến':'Đang kết nối lại');}
async function api(path,data={}){const response=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'Không thể kết nối.');applyState(result);return result;}
function showModal(mode,game){modalMode=mode;$('#form-error').textContent='';$('#modal-submit').classList.remove('hidden');$('#modal-submit').textContent='Tiếp tục ↗';const fields=$('#modal-fields');if(mode==='create'){$('#modal-title').textContent='Tạo phòng chờ';$('#modal-description').textContent='Rủ tối đa 8 người vào sảnh. Game sẽ được bổ sung sau.';fields.innerHTML='<label class="field">Tên phòng<input name="title" maxlength="40" placeholder="Hội bạn của Xanh" required></label><label class="field">Game đang chờ<select name="game">'+games.map(g=>'<option value="'+g.id+'" '+((game||'caro')===g.id?'selected':'')+'>'+g.name+' — sắp ra mắt</option>').join('')+'</select></label>';$('#modal-submit').textContent='Tạo phòng ↗';}
else if(mode==='join'){$('#modal-title').textContent='Gặp nhau trong phòng';$('#modal-description').textContent='Nhập mã 6 ký tự mà bạn bè gửi cho bạn.';fields.innerHTML='<label class="field">Mã phòng<input name="code" maxlength="6" minlength="6" autocomplete="off" placeholder="VD: A1B2C3" required></label>';$('#modal-submit').textContent='Vào phòng ↗';}
else if(mode==='profile'){$('#modal-title').textContent='Bạn tên gì nhỉ?';$('#modal-description').textContent='Biệt danh này sẽ hiển thị với những người trong phòng.';fields.innerHTML='<label class="field">Biệt danh<input name="name" maxlength="24" value="'+escapeHTML(current?.me.name||'')+'" placeholder="Nhập biệt danh" required></label>';$('#modal-submit').textContent='Lưu biệt danh ↗';}
else{const g=games.find(x=>x.id===game);$('#modal-title').textContent=g.name;$('#modal-description').textContent=g.description;fields.innerHTML='<p>Game đang trong kế hoạch phát triển và chưa thể chơi. Bạn có thể đánh dấu yêu thích để tìm lại nhanh.</p><span class="coming">Sắp ra mắt · '+g.players+'</span>';$('#modal-submit').classList.add('hidden');}modal.showModal();}
document.addEventListener('click',async e=>{const fav=e.target.closest('[data-favorite]');if(fav){const id=fav.dataset.favorite;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];try{localStorage.setItem('xa_favorites',JSON.stringify(favorites));}catch{}renderGames();return;}const detail=e.target.closest('[data-detail]');if(detail){showModal('detail',detail.dataset.detail);return;}const join=e.target.closest('[data-join]');const action=e.target.closest('[data-ready],[data-leave],[data-copy]');if(join||action){try{if(join)await api('join',{code:join.dataset.join});else if(action.hasAttribute('data-ready'))await api('ready');else if(action.hasAttribute('data-leave'))await api('leave');else{await navigator.clipboard.writeText(current.room.code);toast('Đã sao chép mã phòng '+current.room.code);}}catch(err){toast(err.message||'Chưa sao chép được. Bạn có thể chọn mã phòng để sao chép.');}}});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});renderGames();}));document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));$('#page-label').textContent=view==='favorites'?'Yêu thích':view==='rooms'?'Phòng chơi':'Khám phá';$('#catalog-title').childNodes[0].textContent=view==='favorites'?'Game yêu thích ':'Kho game ';renderGames();if(view==='rooms')$('#lobby').scrollIntoView({behavior:'smooth',block:'start'});else $('#catalog').scrollIntoView({behavior:'smooth',block:'start'});}));
$('#search').addEventListener('input',renderGames);$('#create-room').onclick=$('#hero-create').onclick=()=>{if(current?.room){toast('Bạn đang ở một phòng. Hãy rời phòng trước khi tạo phòng mới.');$('#lobby').scrollIntoView({behavior:'smooth'});}else showModal('create');};$('#join-room').onclick=()=>showModal('join');$('#profile-button').onclick=()=>showModal('profile');$('#close-modal').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});$('#modal-form').addEventListener('submit',async e=>{e.preventDefault();const button=$('#modal-submit');button.disabled=true;$('#form-error').textContent='';try{const data=Object.fromEntries(new FormData(e.target));await api(modalMode==='create'?'rooms':modalMode,data);modal.close();toast(modalMode==='profile'?'Đã lưu biệt danh.':modalMode==='create'?'Phòng đã mở. Gửi mã cho bạn bè nhé!':'Bạn đã vào phòng.');}catch(err){$('#form-error').textContent=err.message||'Mất kết nối, bạn thử lại nhé.';}finally{button.disabled=false;}});
$('#year').textContent=new Date().getFullYear();renderGames();const events=new EventSource('/api/events');events.onopen=()=>setConnected(true);events.onmessage=e=>{try{applyState(JSON.parse(e.data));setConnected(true);}catch{toast('Chưa nhận được trạng thái sảnh.');}};events.onerror=()=>setConnected(false);
