import {SIZE,WALLS,AREAS,CLASSES,WEAPONS,createWorld,stepWorld,ability,jump,currentGun,gunInfo,switchWeapon,reload,heal,nearestLoot,pickup} from './battle-engine.js';
import {loadEquipment,awardBattle} from './beta-shop.js';
const $=s=>document.querySelector(s),canvas=$('#arena'),ctx=canvas.getContext('2d');let choice='vanguard',world=createWorld(choice),playing=false,paused=false,finished=false,last=0,keys=new Set(),mouse={x:550,y:340,fire:false},cam={x:0,y:0},move={x:0,y:0},aim={angle:0,fire:false},sound=false,audio=null,noticeTimer,hudTime=0,bagOpen=false;
function tone(f=400,d=.06){if(!sound||!audio||audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f/2,audio.currentTime+d);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d);}
function notice(t){$('#notice').textContent=t;$('#notice').style.opacity='1';clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').style.opacity='0',2700);}
function rect(x,y,w,h,color,r=0){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}function circle(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
const visible=(x,y,pad=100)=>x>cam.x-pad&&y>cam.y-pad&&x<cam.x+canvas.width+pad&&y<cam.y+canvas.height+pad;
// A small repeatable tile avoids redrawing thousands of terrain details each frame.
const tile=document.createElement('canvas');tile.width=tile.height=256;const tc=tile.getContext('2d');tc.fillStyle='#4b6250';tc.fillRect(0,0,256,256);for(let i=0;i<420;i++){const x=(i*83.31)%256,y=(i*37.79)%256;tc.fillStyle=['#516851','#455f4d','#607455','#415746'][i%4];tc.fillRect(x,y,2+i%5,1+i%3);}const terrain=ctx.createPattern(tile,'repeat');
function weapon(x,y,id,scale=1){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);const sniper=id==='sniper',shot=id==='shotgun',pistol=id==='pistol';rect(-17,-4,pistol?22:40,8,'#283139',2);rect(pistol?4:20,-2,sniper?25:shot?15:9,4,'#aeb4a8');rect(-15,4,7,10,'#ad8b60',2);if(!pistol){rect(-24,-5,11,10,'#8c7051',2);rect(-2,4,8,11,'#444e53');}if(sniper)rect(0,-9,19,5,'#d7b97d',2);ctx.restore();}
function draw(){const w=canvas.width,h=canvas.height,p=world.player;cam.x=Math.max(0,Math.min(SIZE-w,p.x-w/2));cam.y=Math.max(0,Math.min(SIZE-h,p.y-h/2));ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(-cam.x,-cam.y);ctx.fillStyle=terrain;ctx.fillRect(cam.x,cam.y,w,h);
// Roads, district paving, landmarks and cover share the collision map.
for(const n of [850,2400,3950]){rect(n-55,0,110,SIZE,'#69736b');rect(0,n-55,SIZE,110,'#69736b');ctx.strokeStyle='#c2b998';ctx.lineWidth=3;ctx.setLineDash([24,35]);ctx.beginPath();ctx.moveTo(n,cam.y);ctx.lineTo(n,cam.y+h);ctx.moveTo(cam.x,n);ctx.lineTo(cam.x+w,n);ctx.stroke();ctx.setLineDash([]);}
for(const [i,a]of AREAS.entries()){if(!visible(a.x,a.y,650))continue;rect(a.x-390,a.y-340,780,690,a.color,35);rect(a.x-350,a.y-300,700,610,'#263f3020',25);ctx.fillStyle='#ede1bb';ctx.font='bold 18px system-ui';ctx.textAlign='center';ctx.fillText(a.name,a.x,a.y-285);ctx.textAlign='left';for(let j=0;j<5;j++){rect(a.x-110+j*47,a.y-150,32,70,'#323b3b88',3);rect(a.x-114+j*47,a.y-157,32,65,j%2?'#85704f':'#687c79',3);rect(a.x-109+j*47,a.y-151,22,3,'#b4b098');}circle(a.x,a.y+32,72,'#a2a187');circle(a.x,a.y+32,66,'#707d6c');ctx.strokeStyle='#c4b68d';ctx.lineWidth=2;ctx.beginPath();ctx.arc(a.x,a.y+32,52,0,Math.PI*2);ctx.stroke();}
// Decorative trees are kept outside the play-space walls; their trunks are small landmarks.
for(let y=Math.floor(cam.y/310)*310;y<cam.y+h+310;y+=310)for(let x=Math.floor(cam.x/310)*310;x<cam.x+w+310;x+=310){if(AREAS.some(a=>Math.abs(a.x-x)<460&&Math.abs(a.y-y)<400)||[850,2400,3950].some(n=>Math.abs(n-x)<100||Math.abs(n-y)<100))continue;const xx=x+Math.sin(y)*45,yy=y+Math.cos(x)*40;circle(xx+12,yy+16,40,'#192e2666');circle(xx,yy,35,'#304f3e');circle(xx-12,yy-9,23,'#426348');circle(xx+13,yy-14,21,'#547653');circle(xx+2,yy+9,19,'#395d41');}
for(const a of WALLS){if(!visible(a.x,a.y,350))continue;rect(a.x+12,a.y+16,a.w,a.h,'#17261e70',5);rect(a.x,a.y,a.w,a.h,'#b0ad96',5);const roof=a.type==='house';rect(a.x+5,a.y+5,a.w-10,a.h-10,roof?['#aa8668','#74898a','#a2a19a'][a.tone]:['#657e7e','#9a815f','#6a788e'][a.tone],3);for(let x=a.x+14;x<a.x+a.w-10;x+=22)rect(x,a.y+8,2,a.h-16,'#233d3b44');if(roof){rect(a.x+8,a.y+a.h/2-3,a.w-16,6,'#dac5a255');rect(a.x+a.w-33,a.y+14,18,23,'#394d53',2);}else{rect(a.x+7,a.y+7,a.w-14,3,'#d5c7a46f');rect(a.x+7,a.y+a.h-10,a.w-14,3,'#142d3255');}}
for(const l of world.loot){if(!visible(l.x,l.y,50))continue;circle(l.x,l.y,23,'#16272bd0');ctx.strokeStyle=l.type==='weapon'?'#e1b671':'#9eb7ac';ctx.lineWidth=1;ctx.beginPath();ctx.arc(l.x,l.y,23,0,Math.PI*2);ctx.stroke();if(l.type==='weapon')weapon(l.x,l.y,l.weapon,.65);else{ctx.fillStyle=l.type==='med'?'#bbd4ad':'#d8c6a1';ctx.font='bold 19px system-ui';ctx.textAlign='center';ctx.fillText(l.type==='med'?'+':l.type==='armor'?'◇':'▥',l.x,l.y+7);ctx.textAlign='left';}}
for(const a of world.actors){if(!visible(a.x,a.y,120))continue;if(!a.alive){rect(a.x-12,a.y-9,24,18,'#705b44',3);continue;}circle(a.x+6,a.y+9,22,'#10221c75');ctx.save();ctx.translate(a.x,a.y);ctx.rotate(a.angle);rect(-12,-22,10,15,'#293e3f',4);rect(-12,7,10,15,'#293e3f',4);rect(-15,-16,29,32,a.color,7);rect(-17,-11,10,23,'#52644e',3);rect(-17,-8,7,17,'#899675',2);rect(0,-19,19,8,'#c7b597',3);rect(0,11,19,8,'#c7b597',3);weapon(21,2,currentGun(a)?.id||'pistol',.8);circle(-1,0,10,'#263e47');circle(-3,-2,8,a.bot?'#8a8e77':'#bed0ba');rect(4,-6,5,12,'#263f49',2);ctx.restore();if(a.air&&world.phase!=='flight'){const cy=a.y-62;ctx.strokeStyle='#e4d8b9';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a.x-55,cy);ctx.lineTo(a.x,a.y);ctx.lineTo(a.x+55,cy);ctx.stroke();ctx.fillStyle=a.bot?'#bd9874':'#d7c495';ctx.beginPath();ctx.ellipse(a.x,cy,60,30,0,Math.PI,Math.PI*2);ctx.fill();ctx.strokeStyle='#775d41';for(let j=-1;j<=1;j++){ctx.beginPath();ctx.moveTo(a.x+j*30,cy);ctx.lineTo(a.x+j*20,cy-25);ctx.stroke();}}
if(a.shield>0){ctx.strokeStyle='#b7d3e1';ctx.lineWidth=3;ctx.beginPath();ctx.arc(a.x,a.y,28,0,Math.PI*2);ctx.stroke();}if(!a.air){rect(a.x-21,a.y-34,42,5,'#152a26');rect(a.x-21,a.y-34,42*a.hp/a.maxHp,5,a.bot?'#d79e78':'#c7dba3');}if(!a.bot){ctx.fillStyle='#fff0ce';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.fillText('BẠN',a.x,a.y-44);ctx.textAlign='left';}}
for(const b of world.bullets){if(!visible(b.x,b.y))continue;ctx.strokeStyle=b.owner===0?'#ffe7af':'#f3a47c';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-b.vx*.013,b.y-b.vy*.013);ctx.stroke();}for(const e of world.effects){if(!visible(e.x,e.y,220))continue;ctx.globalAlpha=Math.min(1,e.life*3);if(e.nova){ctx.strokeStyle=e.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(e.x,e.y,210*(1-e.life/.65),0,Math.PI*2);ctx.stroke();}else for(let i=0;i<e.count;i++){const a=i*2.4,r=(.4-e.life)*95;circle(e.x+Math.cos(a)*r,e.y+Math.sin(a)*r,2,e.color);}}ctx.globalAlpha=1;
ctx.fillStyle='#66507865';ctx.beginPath();ctx.rect(0,0,SIZE,SIZE);ctx.arc(world.zone.x,world.zone.y,world.zone.r,0,Math.PI*2,true);ctx.fill('evenodd');ctx.strokeStyle='#c4ccd9';ctx.lineWidth=4;ctx.beginPath();ctx.arc(world.zone.x,world.zone.y,world.zone.r,0,Math.PI*2);ctx.stroke();
if(world.phase==='flight'){ctx.save();ctx.translate(p.x,p.y);rect(-75,-12,150,24,'#d8d8c3',9);rect(-15,-80,26,160,'#b4c1b5',5);rect(-61,-43,12,86,'#8b9d97',4);circle(60,0,10,'#9fb4b1');ctx.restore();}ctx.restore();
const mm=125,mx=w-mm-14,my=14;rect(mx-5,my-5,mm+10,mm+10,'#172832ee',5);rect(mx,my,mm,mm,'#4c654f');for(const a of AREAS)rect(mx+(a.x-300)/SIZE*mm,my+(a.y-300)/SIZE*mm,600/SIZE*mm,600/SIZE*mm,'#9f9778');ctx.save();ctx.beginPath();ctx.rect(mx,my,mm,mm);ctx.clip();ctx.strokeStyle='#ece5cb';ctx.lineWidth=1;ctx.beginPath();ctx.arc(mx+world.zone.x/SIZE*mm,my+world.zone.y/SIZE*mm,world.zone.r/SIZE*mm,0,Math.PI*2);ctx.stroke();if(world.phase==='flight'){ctx.strokeStyle='#e6bf73';ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(mx,my+mm/2);ctx.lineTo(mx+mm,my+mm/2);ctx.stroke();ctx.setLineDash([]);}circle(mx+p.x/SIZE*mm,my+p.y/SIZE*mm,3,'#ffffff');ctx.restore();ctx.fillStyle='#e4e3ca';ctx.font='9px system-ui';ctx.fillText('ĐẢO THANH VÂN · 4.800 × 4.800',mx-4,my+mm+17);
if(playing&&!paused&&!p.air&&!aim.fire){ctx.strokeStyle='#fff1d5';ctx.lineWidth=1;ctx.beginPath();ctx.arc(mouse.x,mouse.y,7,0,Math.PI*2);ctx.moveTo(mouse.x-12,mouse.y);ctx.lineTo(mouse.x+12,mouse.y);ctx.moveTo(mouse.x,mouse.y-12);ctx.lineTo(mouse.x,mouse.y+12);ctx.stroke();}}
function lootName(l){return l.type==='weapon'?WEAPONS[l.weapon].name:l.type==='med'?'Túi cứu thương':l.type==='armor'?'Giáp chiến thuật':'Đạn '+({light:'nhẹ',heavy:'trường',shell:'shotgun'}[l.ammo]);}
function hud(){const p=world.player,g=currentGun(p),s=gunInfo(p);$('#hp').textContent=Math.ceil(p.hp)+' / '+p.maxHp;$('#health').max=p.maxHp;$('#health').value=p.hp;$('#ammo').textContent=p.reload?'Đang nạp…':g.ammo+' / '+p.bag[s.ammo];$('#alive').textContent=world.actors.filter(a=>a.alive).length;$('#kills').textContent=p.kills+' / '+p.level;$('#zone').textContent=world.phase==='flight'?'TRÊN MÁY BAY':p.air?'ĐANG NHẢY DÙ':Math.round(world.zone.r)+' m';$('#armor').textContent=Math.ceil(p.armor);for(const [id,key,label]of [['dash','dash','Space'],['shield','shieldCd','Q'],['nova','novaCd','E']]){$('#'+id).textContent=p[key]>0?p[key].toFixed(1)+' giây':label+' · Sẵn sàng';document.querySelector('[data-skill="'+id+'"]').disabled=!playing||paused||p.air||p[key]>0;}for(let i=0;i<2;i++){const slot=p.slots[i],b=$('#slot'+i);b.textContent=(i+1)+' · '+(slot?WEAPONS[slot.id].name+'  '+slot.ammo:'Ô trống');b.classList.toggle('selected',p.active===i);b.setAttribute('aria-pressed',String(p.active===i));b.disabled=!slot||p.air;}
$('#jump').classList.toggle('hidden',!playing||world.phase!=='flight');$('#drop-info').textContent=p.air&&world.phase!=='flight'?'DÙ ĐANG HẠ · WASD / cần trái để chọn điểm đáp':'';const l=nearestLoot(world);$('#pickup').textContent=l?'F · Nhặt '+lootName(l):'F · Đến gần vật phẩm';$('#pickup').disabled=!l||p.air||!playing||paused;$('#med').textContent=p.healing?'Đang hồi máu…':'H · Hồi máu ('+p.bag.med+')';$('#bag-content').textContent='Đạn nhẹ: '+p.bag.light+' / 240\nĐạn trường: '+p.bag.heavy+' / 240\nĐạn shotgun: '+p.bag.shell+' / 240\nTúi cứu thương: '+p.bag.med+' / 5\nGiáp: '+Math.ceil(p.armor)+' / 100';}
function end(){finished=true;playing=false;mouse.fire=false;aim.fire=false;const reward=awardBattle(world.player.kills,world.status==='won');$('#menu').classList.remove('hidden');$('.classes').classList.remove('hidden');$('#menu h1').textContent=world.status==='won'?'CHIẾN THẮNG!':'HẸN Ở TRẬN TIẾP THEO.';$('#intro').textContent='Hạ '+world.player.kills+' đối thủ · Sống sót '+Math.floor(world.time)+' giây · +'+reward+' xu beta trên máy này.';$('#start').textContent='CHƠI LẠI ↗';$('#pause').textContent='Tạm dừng';}
function loop(t){const dt=last?Math.min(.04,(t-last)/1000):0;last=t;if(playing&&!paused){const p=world.player;stepWorld(world,dt,{x:move.x+(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0),y:move.y+(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0),angle:aim.fire?aim.angle:Math.atan2(mouse.y+cam.y-p.y,mouse.x+cam.x-p.x),fire:mouse.fire||aim.fire,reload:keys.has('r')});for(const e of world.events){if(e.type==='shot'&&e.actor===0)tone(150,.035);if(e.type==='pickup'&&e.actor===0){tone(700,.1);notice('Đã nhặt vật phẩm');}if(e.type==='land')notice('Đã đáp đất · F nhặt đồ · 1/2 đổi súng · B ba lô');if(e.type==='kill'&&e.source===0){tone(500,.16);notice('Hạ gục đối thủ!');}}if(world.status!=='playing'&&!finished)end();}draw();if(t-hudTime>100){hud();hudTime=t;}requestAnimationFrame(loop);}
async function start(){const b=$('#start');if(b.disabled)return;b.disabled=true;b.textContent='ĐANG CHUẨN BỊ…';try{const equipment=await loadEquipment();world=createWorld(choice);if(equipment.battle==='battle-cobalt')world.player.color='#5897c5';if(equipment.battle==='battle-ember')world.player.color='#d39456';playing=true;paused=false;finished=false;keys.clear();mouse.fire=false;aim.fire=false;move={x:0,y:0};$('#menu').classList.add('hidden');$('#pause').textContent='Tạm dừng';canvas.focus({preventScroll:true});if(sound)audio?.resume();notice('Chọn điểm nhảy · Bấm NHẢY DÙ hoặc J');}finally{b.disabled=false;b.textContent='VÀO TRẬN ↗';}}
function pause(){if(!playing)return;paused=!paused;keys.clear();mouse.fire=false;aim.fire=false;move={x:0,y:0};$('#pause').textContent=paused?'Tiếp tục':'Tạm dừng';if(paused){$('#menu').classList.remove('hidden');$('#menu h1').textContent='TẠM DỪNG';$('#intro').textContent='Trận đấu đã dừng. Bấm tiếp tục khi sẵn sàng.';$('.classes').classList.add('hidden');$('#start').textContent='TIẾP TỤC ↗';audio?.suspend();}else{$('#menu').classList.add('hidden');$('.classes').classList.remove('hidden');if(sound)audio?.resume();canvas.focus({preventScroll:true});}}
function act(fn){if(playing&&!paused){fn();hud();canvas.focus({preventScroll:true});}}$('#start').onclick=()=>paused?pause():start();$('#pause').onclick=pause;$('#jump').onclick=()=>act(()=>jump(world));$('#pickup').onclick=()=>act(()=>{if(pickup(world,world.player,nearestLoot(world)))notice('Đã nhặt vật phẩm');});$('#med').onclick=()=>act(()=>heal(world.player));$('#bag').onclick=()=>{bagOpen=!bagOpen;$('#inventory').classList.toggle('hidden',!bagOpen);$('#bag').setAttribute('aria-expanded',String(bagOpen));};$('#bag-close').onclick=()=>$('#bag').click();for(let i=0;i<2;i++)$('#slot'+i).onclick=()=>act(()=>switchWeapon(world.player,i));
$('#audio').onclick=()=>{sound=!sound;$('#audio').textContent='♫ Âm: '+(sound?'Bật':'Tắt');$('#audio').setAttribute('aria-pressed',String(sound));if(sound){try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{sound=false;$('#audio').textContent='Âm thanh không hỗ trợ';}}else audio?.suspend();};document.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{choice=b.dataset.class;document.querySelectorAll('[data-class]').forEach(c=>{c.classList.toggle('selected',c===b);c.setAttribute('aria-pressed',String(c===b));});});document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>act(()=>{if(ability(world,b.dataset.skill))tone(420,.15);}));$('#reload').onclick=()=>act(()=>reload(world.player));
canvas.onpointermove=e=>{const r=canvas.getBoundingClientRect();mouse.x=(e.clientX-r.left)*canvas.width/r.width;mouse.y=(e.clientY-r.top)*canvas.height/r.height;};canvas.onpointerdown=e=>{if(e.button!==0)return;canvas.onpointermove(e);mouse.fire=true;canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);};canvas.onpointerup=canvas.onpointercancel=()=>mouse.fire=false;
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea')||!playing)return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(['w','a','s','d','q','e','r','p',' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','f','j','b','h','1','2'].includes(k))e.preventDefault();keys.add(k);if(!e.repeat){if(k==='p')pause();else if(k==='b')$('#bag').click();else if(!paused){if(k==='j')jump(world);if(k==='f')pickup(world,world.player,nearestLoot(world));if(k==='h')heal(world.player);if(k==='1'||k==='2')switchWeapon(world.player,Number(k)-1);if([' ','q','e'].includes(k)&&ability(world,{' ':'dash',q:'shield',e:'nova'}[k]))tone(420,.15);}}});document.addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener('blur',()=>{if(playing&&!paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing&&!paused)pause();});
for(const [id,isAim]of [['move-pad',false],['aim-pad',true]]){const pad=$('#'+id);let active=null;function update(e){if(e.pointerId!==active)return;const r=pad.getBoundingClientRect(),dx=(e.clientX-r.left-r.width/2)/(r.width/2),dy=(e.clientY-r.top-r.height/2)/(r.height/2),n=Math.max(1,Math.hypot(dx,dy));pad.querySelector('i').style.transform='translate('+dx/n*25+'px,'+dy/n*25+'px)';if(isAim){aim.fire=Math.hypot(dx,dy)>.15;if(aim.fire)aim.angle=Math.atan2(dy,dx);}else move={x:dx/n,y:dy/n};}pad.onpointerdown=e=>{e.preventDefault();active=e.pointerId;pad.setPointerCapture(active);update(e);};pad.onpointermove=update;pad.onpointerup=pad.onpointercancel=e=>{if(e.pointerId!==active)return;active=null;pad.querySelector('i').style.transform='';if(isAim)aim.fire=false;else move={x:0,y:0};};}
function resize(){const r=canvas.getBoundingClientRect();canvas.width=r.width<650?700:1100;canvas.height=Math.round(canvas.width*r.height/r.width);}window.addEventListener('resize',resize);resize();requestAnimationFrame(loop);
