import {online,connectMatch,drawOnline} from './shooter-client.js';
import {ACTIONS,DEFAULT_KEYS,keyLabel,getSettings,saveSettings,bindKey,getRecords,recordBattle} from './battle-settings.js';
import {SIZE,WALLS,AREAS,ROADS,DIFFICULTIES,deployGlue,toggleVehicle,CLASSES,WEAPONS,createWorld,stepWorld,ability,jump,currentGun,gunInfo,switchWeapon,reload,heal,nearestLoot,pickup} from './battle-engine.js';
import {loadEquipment,awardBattle} from './beta-shop.js';
const settings=getSettings();const label=a=>keyLabel(settings.keys[a]);
const $=s=>document.querySelector(s),canvas=$('#arena'),ctx=canvas.getContext('2d');let choice='vanguard',world=createWorld(choice),playing=false,paused=false,finished=false,last=0,keys=new Set(),mouse={x:550,y:340,fire:false},cam={x:0,y:0},move={x:0,y:0},aim={angle:0,fire:false},sound=false,audio=null,noticeTimer,hudTime=0,bagOpen=false;
function tone(f=400,d=.06){if(!sound||!audio||audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f/2,audio.currentTime+d);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d);}
function notice(t){$('#notice').textContent=t;$('#notice').style.opacity='1';clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').style.opacity='0',2700);}
function rect(x,y,w,h,color,r=0){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}function circle(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
const visible=(x,y,pad=100)=>x>cam.x-pad&&y>cam.y-pad&&x<cam.x+canvas.width+pad&&y<cam.y+canvas.height+pad;
// A small repeatable tile avoids redrawing thousands of terrain details each frame.
const tile=document.createElement('canvas');tile.width=tile.height=256;const tc=tile.getContext('2d');tc.fillStyle='#4b6250';tc.fillRect(0,0,256,256);for(let i=0;i<420;i++){const x=(i*83.31)%256,y=(i*37.79)%256;tc.fillStyle=['#516851','#455f4d','#607455','#415746'][i%4];tc.fillRect(x,y,2+i%5,1+i%3);}const terrain=ctx.createPattern(tile,'repeat');
function weapon(x,y,id,scale=1){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);const sniper=id==='sniper',shot=id==='shotgun',pistol=id==='pistol';rect(-17,-4,pistol?22:40,8,'#283139',2);rect(pistol?4:20,-2,sniper?25:shot?15:9,4,'#aeb4a8');rect(-15,4,7,10,'#ad8b60',2);if(!pistol){rect(-24,-5,11,10,'#8c7051',2);rect(-2,4,8,11,'#444e53');}if(sniper)rect(0,-9,19,5,'#d7b97d',2);ctx.restore();}
function draw(){const w=canvas.width,h=canvas.height,p=world.player;cam.x=Math.max(0,Math.min(SIZE-w,p.x-w/2));cam.y=Math.max(0,Math.min(SIZE-h,p.y-h/2));ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(-cam.x,-cam.y);ctx.fillStyle=terrain;ctx.fillRect(cam.x,cam.y,w,h);
// Roads, district paving, landmarks and cover share the collision map.
for(const n of ROADS){rect(n-55,0,110,SIZE,'#69736b');rect(0,n-55,SIZE,110,'#69736b');ctx.strokeStyle='#c2b998';ctx.lineWidth=3;ctx.setLineDash([24,35]);ctx.beginPath();ctx.moveTo(n,cam.y);ctx.lineTo(n,cam.y+h);ctx.moveTo(cam.x,n);ctx.lineTo(cam.x+w,n);ctx.stroke();ctx.setLineDash([]);}
for(const [i,a]of AREAS.entries()){if(!visible(a.x,a.y,650))continue;rect(a.x-390,a.y-340,780,690,a.color,35);rect(a.x-350,a.y-300,700,610,'#263f3020',25);ctx.fillStyle='#ede1bb';ctx.font='bold 18px system-ui';ctx.textAlign='center';ctx.fillText(a.name,a.x,a.y-285);ctx.textAlign='left';for(let j=0;j<5;j++){rect(a.x-110+j*47,a.y-150,32,70,'#323b3b88',3);rect(a.x-114+j*47,a.y-157,32,65,j%2?'#85704f':'#687c79',3);rect(a.x-109+j*47,a.y-151,22,3,'#b4b098');}circle(a.x,a.y+32,72,'#a2a187');circle(a.x,a.y+32,66,'#707d6c');ctx.strokeStyle='#c4b68d';ctx.lineWidth=2;ctx.beginPath();ctx.arc(a.x,a.y+32,52,0,Math.PI*2);ctx.stroke();}
// Decorative trees are kept outside the play-space walls; their trunks are small landmarks.
for(let y=Math.floor(cam.y/310)*310;y<cam.y+h+310;y+=310)for(let x=Math.floor(cam.x/310)*310;x<cam.x+w+310;x+=310){if(AREAS.some(a=>Math.abs(a.x-x)<460&&Math.abs(a.y-y)<400)||ROADS.some(n=>Math.abs(n-x)<100||Math.abs(n-y)<100))continue;const xx=x+Math.sin(y)*45,yy=y+Math.cos(x)*40;circle(xx+12,yy+16,40,'#192e2666');circle(xx,yy,35,'#304f3e');circle(xx-12,yy-9,23,'#426348');circle(xx+13,yy-14,21,'#547653');circle(xx+2,yy+9,19,'#395d41');}
for(const a of WALLS){if(!visible(a.x,a.y,350))continue;rect(a.x+12,a.y+16,a.w,a.h,'#17261e70',5);rect(a.x,a.y,a.w,a.h,'#b0ad96',5);const roof=a.type==='house';rect(a.x+5,a.y+5,a.w-10,a.h-10,roof?['#aa8668','#74898a','#a2a19a'][a.tone]:['#657e7e','#9a815f','#6a788e'][a.tone],3);for(let x=a.x+14;x<a.x+a.w-10;x+=22)rect(x,a.y+8,2,a.h-16,'#233d3b44');if(roof){rect(a.x+8,a.y+a.h/2-3,a.w-16,6,'#dac5a255');rect(a.x+a.w-33,a.y+14,18,23,'#394d53',2);}else{rect(a.x+7,a.y+7,a.w-14,3,'#d5c7a46f');rect(a.x+7,a.y+a.h-10,a.w-14,3,'#142d3255');}}
for(const l of world.loot){if(!visible(l.x,l.y,50))continue;circle(l.x,l.y,23,'#16272bd0');ctx.strokeStyle=l.type==='weapon'?'#e1b671':'#9eb7ac';ctx.lineWidth=1;ctx.beginPath();ctx.arc(l.x,l.y,23,0,Math.PI*2);ctx.stroke();if(l.type==='weapon')weapon(l.x,l.y,l.weapon,.65);else{ctx.fillStyle=l.type==='med'?'#bbd4ad':'#d8c6a1';ctx.font='bold 19px system-ui';ctx.textAlign='center';ctx.fillText(l.type==='med'?'+':l.type==='armor'?'◇':l.type==='glue'?'▰':'▥',l.x,l.y+7);ctx.textAlign='left';}}
for(const c of world.covers){if(!visible(c.x,c.y,220))continue;rect(c.x+8,c.y+12,c.w,c.h,'#122b3655',8);rect(c.x,c.y,c.w,c.h,'#b5dad9',8);rect(c.x+5,c.y+5,c.w-10,c.h-10,'#608e9d',5);ctx.strokeStyle='#e4f4e7';ctx.lineWidth=2;ctx.strokeRect(c.x+8,c.y+8,c.w-16,c.h-16);rect(c.x,c.y-8,c.w*c.hp/c.maxHp,3,'#e4efce');}
for(const v of world.vehicles){if(!visible(v.x,v.y))continue;ctx.save();ctx.translate(v.x,v.y);ctx.rotate(v.angle);rect(-42,-27,84,54,'#14251f66',8);for(const x of [-26,20])for(const y of [-30,22])rect(x,y,17,10,'#172325',3);rect(-40,-23,80,46,v.hp>0?'#a38c59':'#454940',8);rect(-8,-20,27,40,'#52665e',4);rect(15,-17,10,34,'#9dbcb6',2);rect(-12,-16,5,32,'#788f83',2);rect(-34,-16,18,32,'#6d724f',2);rect(35,-20,7,8,'#f4dc9e',2);rect(35,12,7,8,'#f4dc9e',2);ctx.restore();}
for(const a of world.actors){if(a.inPlane||a.vehicle!==null)continue;if(!visible(a.x,a.y,120))continue;if(!a.alive){rect(a.x-12,a.y-9,24,18,'#705b44',3);continue;}circle(a.x+4,a.y+6,16,'#10221c75');ctx.save();ctx.translate(a.x,a.y);ctx.rotate(a.angle);ctx.scale(.75,.75);rect(-12,-22,10,15,'#293e3f',4);rect(-12,7,10,15,'#293e3f',4);rect(-15,-16,29,32,a.color,7);rect(-17,-11,10,23,'#52644e',3);rect(-17,-8,7,17,'#899675',2);rect(0,-19,19,8,'#c7b597',3);rect(0,11,19,8,'#c7b597',3);weapon(21,2,currentGun(a)?.id||'pistol',.8);circle(-1,0,10,'#263e47');circle(-3,-2,8,a.bot?'#8a8e77':'#bed0ba');rect(4,-6,5,12,'#263f49',2);ctx.restore();if(a.air&&world.phase!=='flight'){const cy=a.y-50;ctx.strokeStyle='#e4d8b9';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a.x-43,cy);ctx.lineTo(a.x,a.y);ctx.lineTo(a.x+43,cy);ctx.stroke();ctx.fillStyle=a.bot?'#bd9874':'#d7c495';ctx.beginPath();ctx.ellipse(a.x,cy,46,24,0,Math.PI,Math.PI*2);ctx.fill();ctx.strokeStyle='#775d41';for(let j=-1;j<=1;j++){ctx.beginPath();ctx.moveTo(a.x+j*23,cy);ctx.lineTo(a.x+j*16,cy-20);ctx.stroke();}}
if(a.shield>0||a.guard>0){ctx.strokeStyle='#b7d3e1';ctx.lineWidth=3;ctx.beginPath();ctx.arc(a.x,a.y,28,0,Math.PI*2);ctx.stroke();}if(!a.air){rect(a.x-21,a.y-34,42,5,'#152a26');rect(a.x-21,a.y-34,42*a.hp/a.maxHp,5,a.bot?'#d79e78':'#c7dba3');}if(a.id===p.id){ctx.fillStyle='#fff0ce';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.fillText('BẠN',a.x,a.y-44);ctx.textAlign='left';}}
if(online){for(const a of world.actors){if(!a.alive||a.inPlane||!visible(a.x,a.y))continue;ctx.fillStyle=a.team===p.team?'#bcefa4':'#f3c6b6';ctx.font='bold 11px system-ui';ctx.textAlign='center';ctx.fillText((a.id===p.id?'BẠN · ':'')+a.name+' · Đ'+(a.team+1),a.x,a.y-48);}}
for(const b of world.bullets){if(!visible(b.x,b.y))continue;ctx.strokeStyle=b.owner===0?'#ffe7af':'#f3a47c';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-b.vx*.013,b.y-b.vy*.013);ctx.stroke();}for(const e of world.effects){if(!visible(e.x,e.y,220))continue;ctx.globalAlpha=Math.min(1,e.life*3);if(e.nova){ctx.strokeStyle=e.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(e.x,e.y,210*(1-e.life/.65),0,Math.PI*2);ctx.stroke();}else for(let i=0;i<e.count;i++){const a=i*2.4,r=(.4-e.life)*95;circle(e.x+Math.cos(a)*r,e.y+Math.sin(a)*r,2,e.color);}}ctx.globalAlpha=1;
ctx.fillStyle='#66507865';ctx.beginPath();ctx.rect(0,0,SIZE,SIZE);ctx.arc(world.zone.x,world.zone.y,world.zone.r,0,Math.PI*2,true);ctx.fill('evenodd');ctx.strokeStyle='#c4ccd9';ctx.lineWidth=4;ctx.beginPath();ctx.arc(world.zone.x,world.zone.y,world.zone.r,0,Math.PI*2);ctx.stroke();
if(world.phase==='flight'){ctx.save();ctx.translate(p.x,p.y);rect(-75,-12,150,24,'#d8d8c3',9);rect(-15,-80,26,160,'#b4c1b5',5);rect(-61,-43,12,86,'#8b9d97',4);circle(60,0,10,'#9fb4b1');ctx.restore();}ctx.restore();
const mm=125,mx=w-mm-14,my=14;rect(mx-5,my-5,mm+10,mm+10,'#172832ee',5);rect(mx,my,mm,mm,'#4c654f');for(const a of AREAS)rect(mx+(a.x-300)/SIZE*mm,my+(a.y-300)/SIZE*mm,600/SIZE*mm,600/SIZE*mm,'#9f9778');ctx.save();ctx.beginPath();ctx.rect(mx,my,mm,mm);ctx.clip();ctx.strokeStyle='#ece5cb';ctx.lineWidth=1;ctx.beginPath();ctx.arc(mx+world.zone.x/SIZE*mm,my+world.zone.y/SIZE*mm,world.zone.r/SIZE*mm,0,Math.PI*2);ctx.stroke();if(world.phase==='flight'){ctx.strokeStyle='#e6bf73';ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(mx,my+mm/2);ctx.lineTo(mx+mm,my+mm/2);ctx.stroke();ctx.setLineDash([]);}circle(mx+p.x/SIZE*mm,my+p.y/SIZE*mm,3,'#ffffff');ctx.restore();ctx.fillStyle='#e4e3ca';ctx.font='9px system-ui';ctx.fillText('ĐẢO THANH VÂN · 16.000 × 16.000',mx-4,my+mm+17);
if(playing&&!paused&&!p.air&&!aim.fire){ctx.strokeStyle='#fff1d5';ctx.lineWidth=1;ctx.beginPath();ctx.arc(mouse.x,mouse.y,7,0,Math.PI*2);ctx.moveTo(mouse.x-12,mouse.y);ctx.lineTo(mouse.x+12,mouse.y);ctx.moveTo(mouse.x,mouse.y-12);ctx.lineTo(mouse.x,mouse.y+12);ctx.stroke();}}
function lootName(l){return l.type==='weapon'?WEAPONS[l.weapon].name:l.type==='med'?'Túi cứu thương':l.type==='armor'?'Giáp chiến thuật':l.type==='glue'?'Bom keo':'Đạn '+({light:'nhẹ',heavy:'trường',shell:'shotgun'}[l.ammo]);}
function hud(){const p=world.player,g=currentGun(p),s=gunInfo(p);$('#hp').textContent=Math.ceil(p.hp)+' / '+p.maxHp;$('#health').max=p.maxHp;$('#health').value=p.hp;$('#ammo').textContent=p.reload?'Đang nạp…':g.ammo+' / '+p.bag[s.ammo];$('#alive').textContent=world.actors.filter(a=>a.alive).length;$('#kills').textContent=p.kills+' / '+p.level;$('#zone').textContent=world.phase==='flight'?'BAY '+Math.round(world.flight/25*100)+'% · '+Math.max(0,Math.ceil(25-world.flight))+'s':p.air?'ĐANG NHẢY DÙ':'Bo '+world.zone.stage+' · '+(world.zone.shrinking?'Thu ':'Chờ ')+world.zone.remaining+'s';$('#armor').textContent=Math.ceil(p.armor);for(const [id,key,hint]of [['dash','dash',label('dash')],['shield','shieldCd',label('shield')],['nova','novaCd',label('nova')]]){$('#'+id).textContent=p[key]>0?p[key].toFixed(1)+' giây':hint+' · Sẵn sàng';document.querySelector('[data-skill="'+id+'"]').disabled=!playing||paused||p.air||p[key]>0;}for(let i=0;i<2;i++){const slot=p.slots[i],b=$('#slot'+i);b.textContent=label('slot'+i)+' · '+(slot?WEAPONS[slot.id].name+'  '+slot.ammo:'Ô trống');b.classList.toggle('selected',p.active===i);b.setAttribute('aria-pressed',String(p.active===i));b.disabled=!slot||p.air;}
$('#jump').classList.toggle('hidden',!playing||world.phase!=='flight');$('#drop-info').textContent=world.phase==='flight'&&playing?'MÁY BAY ĐANG BAY → · '+label('jump')+' để nhảy':p.air&&world.phase!=='flight'?'DÙ ĐANG HẠ · '+Math.ceil(p.altitude*18)+'s · Điều hướng đến khu nhà · Đáp đất mới nhặt đồ':'';const l=nearestLoot(world);$('#pickup').textContent=p.air?'Đáp đất để nhặt đồ':l?label('pickup')+' · Nhặt '+lootName(l):label('pickup')+' · Đến gần vật phẩm';$('#pickup').disabled=!l||p.air||!playing||paused;$('#med').textContent=p.healing?'Đang hồi máu…':label('heal')+' · Hồi máu ('+p.bag.med+')';$('#bag-content').textContent='Đạn nhẹ: '+p.bag.light+' / 240\nĐạn trường: '+p.bag.heavy+' / 240\nĐạn shotgun: '+p.bag.shell+' / 240\nTúi cứu thương: '+p.bag.med+' / 5\nBom keo: '+p.bag.glue+' / 6\nGiáp: '+Math.ceil(p.armor)+' / 100';$('#glue').textContent=label('glue')+' · Bom keo ('+p.bag.glue+')';$('#vehicle').textContent=label('vehicle')+' · '+(p.vehicle===null?'Lên xe':'Xuống xe');$('#bag').textContent=label('bag')+' · BA LÔ';$('#jump').textContent=label('jump')+' · NHẢY DÙ';$('#reload small').textContent=label('reload')+' · Nạp đạn';$('#match-state').textContent=DIFFICULTIES[world.difficulty].name+(p.vehicle!==null?' · Xe '+Math.ceil(world.vehicles[p.vehicle].hp)+' HP · Xăng '+Math.ceil(world.vehicles[p.vehicle].fuel/1.2)+'%':p.guard>0&&!p.air?' · Bảo vệ '+Math.ceil(p.guard)+'s (bắn sẽ hết)':' · '+Math.round(world.zone.r)+' m');}

function end(){finished=true;playing=false;mouse.fire=false;aim.fire=false;const saved=recordBattle({name:settings.name,difficulty:world.difficulty,kills:world.player.kills,seconds:world.time,won:world.status==='won'});if(!saved)notice('Trình duyệt không cho lưu thành tích.');const reward=awardBattle(world.player.kills,world.status==='won');$('#menu').classList.remove('hidden');$('.classes').classList.remove('hidden');$('#menu h1').textContent=world.status==='won'?'CHIẾN THẮNG!':'HẸN Ở TRẬN TIẾP THEO.';$('#intro').textContent='Hạ '+world.player.kills+' đối thủ · Sống sót '+Math.floor(world.time)+' giây · +'+reward+' xu beta trên máy này.';$('#start').textContent='CHƠI LẠI ↗';$('#pause').textContent='Tạm dừng';}
function loop(t){const dt=last?Math.min(.04,(t-last)/1000):0;last=t;if(playing&&!paused&&!online){const p=world.player;stepWorld(world,dt,{x:move.x+(keys.has(settings.keys.right)?1:0)-(keys.has(settings.keys.left)?1:0),y:move.y+(keys.has(settings.keys.down)?1:0)-(keys.has(settings.keys.up)?1:0),angle:aim.fire?aim.angle:Math.atan2(mouse.y+cam.y-p.y,mouse.x+cam.x-p.x),fire:mouse.fire||aim.fire,reload:keys.has(settings.keys.reload)});for(const e of world.events){if(e.type==='shot'&&e.actor===0)tone(150,.035);if(e.type==='pickup'&&e.actor===0){tone(700,.1);notice('Đã nhặt vật phẩm');}if(e.type==='land')notice('Đã đáp đất · '+label('pickup')+' nhặt đồ · '+label('glue')+' bom keo · '+label('vehicle')+' lên xe');if(e.type==='kill'&&e.source===0){tone(500,.16);notice('Hạ gục đối thủ!');}}if(world.status!=='playing'&&!finished)end();}if(!document.hidden)drawOnline(world,t,draw);if(!document.hidden&&t-hudTime>100){hud();hudTime=t;}requestAnimationFrame(loop);}
async function start(){if(online)return;const b=$('#start');if(b.disabled)return;b.disabled=true;b.textContent='ĐANG CHUẨN BỊ…';try{const equipment=await loadEquipment();settings.difficulty=$('#difficulty').value;settings.name=$('#player-name').value.trim().slice(0,24)||'Xanh';saveSettings(settings);world=createWorld(choice,Math.random,settings.difficulty);if(equipment.battle==='battle-cobalt')world.player.color='#5897c5';if(equipment.battle==='battle-ember')world.player.color='#d39456';playing=true;paused=false;finished=false;keys.clear();mouse.fire=false;aim.fire=false;move={x:0,y:0};$('#menu').classList.add('hidden');$('#pause').textContent='Tạm dừng';canvas.focus({preventScroll:true});if(sound)audio?.resume();notice('Chọn điểm nhảy · Bấm NHẢY DÙ hoặc '+label('jump'));}finally{b.disabled=false;b.textContent='VÀO TRẬN ↗';}}
function pause(){if(online){keys.clear();mouse.fire=false;aim.fire=false;move={x:0,y:0};notice('Trận online không tạm dừng. Dùng Về phòng để rời trận.');return;}if(!playing)return;paused=!paused;keys.clear();mouse.fire=false;aim.fire=false;move={x:0,y:0};$('#pause').textContent=paused?'Tiếp tục':'Tạm dừng';if(paused){$('#menu').classList.remove('hidden');$('#menu h1').textContent='TẠM DỪNG';$('#intro').textContent='Trận đấu đã dừng. Bấm tiếp tục khi sẵn sàng.';$('.classes').classList.add('hidden');$('#start').textContent='TIẾP TỤC ↗';audio?.suspend();}else{$('#menu').classList.add('hidden');$('.classes').classList.remove('hidden');if(sound)audio?.resume();canvas.focus({preventScroll:true});}}
function act(fn){if(playing&&!paused){fn();hud();canvas.focus({preventScroll:true});}}$('#start').onclick=()=>paused?pause():start();$('#pause').onclick=pause;$('#jump').onclick=()=>act(()=>jump(world));$('#pickup').onclick=()=>act(()=>{if(pickup(world,world.player,nearestLoot(world)))notice('Đã nhặt vật phẩm');});$('#med').onclick=()=>act(()=>heal(world.player));$('#bag').onclick=()=>{bagOpen=!bagOpen;$('#inventory').classList.toggle('hidden',!bagOpen);$('#bag').setAttribute('aria-expanded',String(bagOpen));};$('#bag-close').onclick=()=>$('#bag').click();for(let i=0;i<2;i++)$('#slot'+i).onclick=()=>act(()=>switchWeapon(world.player,i));
$('#audio').onclick=()=>{sound=!sound;$('#audio').textContent='♫ Âm: '+(sound?'Bật':'Tắt');$('#audio').setAttribute('aria-pressed',String(sound));if(sound){try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{sound=false;$('#audio').textContent='Âm thanh không hỗ trợ';}}else audio?.suspend();};document.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{choice=b.dataset.class;document.querySelectorAll('[data-class]').forEach(c=>{c.classList.toggle('selected',c===b);c.setAttribute('aria-pressed',String(c===b));});});document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>act(()=>{if(ability(world,b.dataset.skill))tone(420,.15);}));$('#reload').onclick=()=>act(()=>reload(world.player));
canvas.onpointermove=e=>{const r=canvas.getBoundingClientRect();mouse.x=(e.clientX-r.left)*canvas.width/r.width;mouse.y=(e.clientY-r.top)*canvas.height/r.height;};canvas.onpointerdown=e=>{if(e.button!==0)return;canvas.onpointermove(e);mouse.fire=true;canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);};canvas.onpointerup=canvas.onpointercancel=()=>mouse.fire=false;
let capture=null;
document.addEventListener('keydown',e=>{if(capture){e.preventDefault();if(e.code==='Escape'){capture=null;renderKeys();return;}const error=bindKey(settings.keys,capture,e.code);$('#key-status').textContent=error||'Đã lưu phím mới.';if(!error){capture=null;if(!saveSettings(settings))$('#key-status').textContent='Không lưu được trên trình duyệt này.';renderKeys();}return;}if(e.target.closest('input,textarea,select')||document.querySelector('dialog[open]')||!playing)return;const action=Object.keys(settings.keys).find(a=>settings.keys[a]===e.code);if(!action)return;e.preventDefault();keys.add(e.code);if(e.repeat)return;if(action==='pause'){pause();return;}if(paused)return;if(action==='bag')$('#bag').click();if(action==='jump')jump(world);if(action==='pickup')pickup(world,world.player,nearestLoot(world));if(action==='heal')heal(world.player);if(action==='slot0'||action==='slot1')switchWeapon(world.player,Number(action.slice(-1)));if(['dash','shield','nova'].includes(action))ability(world,action);if(action==='glue')$('#glue').click();if(action==='vehicle')$('#vehicle').click();});document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{if(playing&&!paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing&&!paused)pause();});
for(const [id,isAim]of [['move-pad',false],['aim-pad',true]]){const pad=$('#'+id);let active=null;function update(e){if(e.pointerId!==active)return;const r=pad.getBoundingClientRect(),dx=(e.clientX-r.left-r.width/2)/(r.width/2),dy=(e.clientY-r.top-r.height/2)/(r.height/2),n=Math.max(1,Math.hypot(dx,dy));pad.querySelector('i').style.transform='translate('+dx/n*25+'px,'+dy/n*25+'px)';if(isAim){aim.fire=Math.hypot(dx,dy)>.15;if(aim.fire)aim.angle=Math.atan2(dy,dx);}else move={x:dx/n,y:dy/n};}pad.onpointerdown=e=>{e.preventDefault();active=e.pointerId;pad.setPointerCapture(active);update(e);};pad.onpointermove=update;pad.onpointerup=pad.onpointercancel=e=>{if(e.pointerId!==active)return;active=null;pad.querySelector('i').style.transform='';if(isAim)aim.fire=false;else move={x:0,y:0};};}
function resize(){const r=canvas.getBoundingClientRect();canvas.width=r.width<650?700:1100;canvas.height=Math.round(canvas.width*r.height/r.width);}window.addEventListener('resize',resize);resize();requestAnimationFrame(loop);

$('#difficulty').value=settings.difficulty;$('#player-name').value=settings.name;
$('#glue').onclick=()=>act(()=>{if(!deployGlue(world))notice('Không dựng được: cần chỗ trống phía trước và bom keo.');else tone(240,.15);});
$('#vehicle').onclick=()=>act(()=>{if(!toggleVehicle(world))notice('Đến gần xe còn nguyên để lên xe; cần chỗ trống để xuống.');});
function openDialog(id){if(playing&&!paused)pause();keys.clear();$('#'+id).showModal();}
function renderKeys(){const list=$('#key-list');list.replaceChildren();for(const [id,name]of Object.entries(ACTIONS)){const b=document.createElement('button');b.textContent=name+' · '+(capture===id?'Ấn phím mới…':label(id));b.onclick=()=>{capture=id;$('#key-status').textContent='Ấn phím mới. Esc để hủy.';renderKeys();};list.append(b);}}
$('#controls').onclick=()=>{renderKeys();openDialog('key-dialog');};$('#reset-keys').onclick=()=>{settings.keys={...DEFAULT_KEYS};capture=null;saveSettings(settings);renderKeys();$('#key-status').textContent='Đã khôi phục phím mặc định.';};
for(const d of document.querySelectorAll('dialog')){d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>{capture=null;keys.clear();});}
function renderRanks(){const body=$('#rank-body');body.replaceChildren();const filter=$('#rank-filter').value;const rows=getRecords().filter(r=>filter==='all'||r.difficulty===filter);$('#rank-empty').hidden=rows.length>0;rows.slice(0,20).forEach((r,i)=>{const tr=document.createElement('tr');for(const val of [i+1,r.name,DIFFICULTIES[r.difficulty].name,r.won?'Thắng':'Kết thúc',r.kills,Math.floor(r.seconds/60)+':'+String(r.seconds%60).padStart(2,'0')]){const td=document.createElement('td');td.textContent=val;tr.append(td);}body.append(tr);});}
$('#rankings').onclick=()=>{renderRanks();openDialog('rank-dialog');};$('#rank-filter').onchange=renderRanks;
$('#overview').onclick=()=>{openDialog('map-dialog');const c=$('#map-canvas'),g=c.getContext('2d'),scale=c.width/SIZE;g.fillStyle='#415e4d';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#8d927d';g.lineWidth=4;for(const n of ROADS){g.beginPath();g.moveTo(n*scale,0);g.lineTo(n*scale,c.height);g.moveTo(0,n*scale);g.lineTo(c.width,n*scale);g.stroke();}g.textAlign='center';g.font='bold 11px system-ui';for(const a of AREAS){g.fillStyle='#9b9376';g.fillRect((a.x-700)*scale,(a.y-650)*scale,1400*scale,1300*scale);g.fillStyle='#f9edcb';g.fillText(a.name,a.x*scale,(a.y-800)*scale);}for(const v of world.vehicles){if(v.hp<=0)continue;g.fillStyle='#efc06c';g.fillRect(v.x*scale-3,v.y*scale-3,6,6);}g.strokeStyle='#e3dbea';g.lineWidth=3;g.beginPath();g.arc(world.zone.x*scale,world.zone.y*scale,world.zone.r*scale,0,Math.PI*2);g.stroke();g.fillStyle='#fff';g.beginPath();g.arc(world.player.x*scale,world.player.y*scale,5,0,Math.PI*2);g.fill();};

if(online){
$('#start').disabled=true;$('#intro').textContent='Đang kết nối trận online…';$('#difficulty').disabled=true;
connectMatch({game:'battle',notice,
receive:s=>{world={...s,player:s.actors[s.playerId]};playing=s.status==='playing';paused=false;$('#menu').classList.add('hidden');if(s.status!=='playing'){$('#menu').classList.remove('hidden');$('#menu h1').textContent=s.status==='won'?'ĐỘI BẠN CHIẾN THẮNG':'TRẬN ĐÃ KẾT THÚC';$('#intro').textContent='Bấm Về phòng để chơi trận tiếp theo.';}},
input:()=>({x:move.x+Number(keys.has(settings.keys.right))-Number(keys.has(settings.keys.left)),y:move.y+Number(keys.has(settings.keys.down))-Number(keys.has(settings.keys.up)),angle:aim.fire?aim.angle:Math.atan2(mouse.y+cam.y-world.player.y,mouse.x+cam.x-world.player.x),fire:mouse.fire||aim.fire,reload:keys.has(settings.keys.reload)}),
buttons:b=>({jump:'jump',pickup:'pickup',med:'heal',glue:'glue',vehicle:'vehicle',reload:'reload',slot0:'slot0',slot1:'slot1'}[b.id]||b.dataset.skill),
keyAction:code=>{if(capture)return null;const a=Object.keys(settings.keys).find(a=>settings.keys[a]===code);return ['jump','pickup','heal','slot0','slot1','dash','shield','nova','glue','vehicle'].includes(a)?a:null;}
});
}
