import assert from 'node:assert/strict';
import {SIZE,WALLS,WEAPONS,createWorld,stepWorld,ability,blocked,moveActor,lineClear,jump,pickup,switchWeapon,reload,heal,findPath,deployGlue,toggleVehicle,updateZone,DIFFICULTIES} from './battle-engine.js';
const w=createWorld('scout',()=>.5);assert.equal(SIZE,16000);assert.equal(w.actors.length,25);assert.equal(w.player.maxHp,235);assert.equal(w.phase,'flight');assert.equal(ability(w,'shield'),false);assert.equal(jump(w),true);for(let i=0;i<460;i++)stepWorld(w,.04,{});assert.equal(w.player.air,false);assert.equal(w.phase,'combat');assert.equal(ability(w,'shield'),true);assert.equal(ability(w,'shield'),false);
const wall=WALLS[0];assert.ok(blocked(wall.x+20,wall.y+20));assert.equal(lineClear({x:wall.x-60,y:wall.y+30},{x:wall.x+wall.w+60,y:wall.y+30}),false);assert.equal(lineClear({x:50,y:50},{x:200,y:50}),true);const path=findPath({x:wall.x-100,y:wall.y+40},{x:wall.x+wall.w+100,y:wall.y+40});assert.ok(path.length);assert.ok(path.every(p=>!blocked(p.x,p.y,26)));
const p=w.player;const loot={x:p.x,y:p.y,type:'weapon',weapon:'rifle'};assert.ok(pickup(w,p,loot));assert.equal(p.slots[1].id,'rifle');assert.equal(p.active,1);assert.equal(pickup(w,p,loot),false);assert.ok(switchWeapon(p,0));assert.equal(p.slots[0].id,'pistol');assert.ok(switchWeapon(p,1));p.slots[1].ammo=0;p.bag.heavy=7;assert.ok(reload(p));for(let i=0;i<60;i++)stepWorld(w,.04,{});assert.equal(p.slots[1].ammo,7);assert.equal(p.bag.heavy,0);p.hp=30;assert.ok(heal(p));for(let i=0;i<70;i++)stepWorld(w,.04,{});assert.equal(p.hp,95);assert.equal(p.bag.med,2);
const oldReserve=p.bag.light;assert.ok(pickup(w,p,{x:p.x,y:p.y,type:'weapon',weapon:'pistol',loaded:2,dropped:true}));assert.equal(p.slots[p.active].ammo,2);assert.equal(p.bag.light,oldReserve,'dropped guns must not generate free reserve ammo');
const duel=createWorld('ranger',()=>.5);duel.phase='combat';duel.actors.slice(2).forEach(a=>a.alive=false);Object.assign(duel.player,{x:100,y:100,air:false,guard:0});Object.assign(duel.actors[1],{x:350,y:100,air:false,guard:0,speed:0,cool:99,armor:0,bag:{light:0,heavy:0,shell:0,med:0,glue:0}});for(let i=0;i<1800&&duel.status==='playing';i++)stepWorld(duel,.016,{angle:0,fire:true,reload:true});assert.equal(duel.status,'won');assert.equal(duel.player.kills,1);
const danger=createWorld('vanguard',()=>.5);danger.phase='combat';danger.actors.slice(2).forEach(a=>a.alive=false);Object.assign(danger.player,{x:100,y:100,air:false,guard:0});Object.assign(danger.actors[1],{x:350,y:100,air:false,guard:0});for(let i=0;i<8000&&danger.status==='playing';i++)stepWorld(danger,.02,{});assert.equal(danger.status,'lost','bot must hit and defeat exposed idle player');
const sim=createWorld('vanguard',()=>.51);jump(sim);const started=performance.now();for(let i=0;i<30000&&sim.status==='playing';i++)stepWorld(sim,.04,{});assert.ok(['won','lost'].includes(sim.status));assert.ok(sim.bullets.length<200);assert.ok(sim.actors.every(a=>Number.isFinite(a.x)&&Number.isFinite(a.y)));console.log('Simulation ms:',Math.round(performance.now()-started));
let data={};globalThis.localStorage={getItem:k=>data[k]||null,setItem:(k,v)=>data[k]=v};const shop=await import('./beta-shop.js');assert.equal(shop.getSave().coins,300);shop.purchase('battle-cobalt');assert.equal(shop.getSave().coins,150);shop.purchase('battle-cobalt');assert.equal(shop.getSave().coins,150);assert.throws(()=>shop.purchase('battle-ember'));shop.equip('battle-cobalt');assert.equal(shop.getSave().equipped.battle,'battle-cobalt');assert.throws(()=>shop.equip('battle-ember'));shop.claimDaily();assert.throws(()=>shop.claimDaily());assert.equal(shop.awardBattle(8,true),150);
console.log('PASS: jump/landing, cover/pathfinding, finite ammo, loot/switching, healing, combat, bot accuracy, full simulation and shop.');

const safe=createWorld();jump(safe);for(let i=0;i<250;i++)stepWorld(safe,.04,{});assert.ok(safe.player.air,'parachute lasts longer than ten seconds');for(let i=0;i<225;i++)stepWorld(safe,.04,{});assert.ok(!safe.player.air);assert.ok(safe.player.guard>20);assert.ok(safe.actors.slice(1).every(a=>Math.hypot(a.x-safe.player.x,a.y-safe.player.y)>1000));
const wallWorld=createWorld();wallWorld.phase='combat';Object.assign(wallWorld.player,{air:false,x:1000,y:1000,angle:0});assert.ok(deployGlue(wallWorld));assert.equal(wallWorld.player.bag.glue,2);assert.equal(lineClear({x:1000,y:1000},{x:1300,y:1000},wallWorld),false);assert.ok(blocked(1110,1000,18,wallWorld.covers));assert.equal(deployGlue(wallWorld),false);
wallWorld.bullets.push({x:1200,y:1000,vx:-1000,vy:0,speed:1000,owner:1,damage:20,life:1});for(let i=0;i<4;i++)stepWorld(wallWorld,.04,{});assert.equal(wallWorld.covers[0].hp,460);wallWorld.covers[0].life=.01;stepWorld(wallWorld,.04,{});assert.equal(wallWorld.covers.length,0);
const carWorld=createWorld();carWorld.phase='combat';const car=carWorld.vehicles[0];Object.assign(carWorld.player,{air:false,x:car.x,y:car.y});assert.ok(toggleVehicle(carWorld));const oldX=car.x;stepWorld(carWorld,.04,{x:1});assert.ok(car.x>oldX+20);assert.ok(car.fuel<120);assert.equal(deployGlue(carWorld),false);assert.ok(toggleVehicle(carWorld));assert.equal(car.driver,null);assert.equal(carWorld.player.r,14);
const zoneWorld=createWorld();zoneWorld.time=50;updateZone(zoneWorld);const originalRadius=zoneWorld.zone.r;zoneWorld.time=230;updateZone(zoneWorld);assert.ok(zoneWorld.zone.r<originalRadius);assert.ok(zoneWorld.zone.shrinking);zoneWorld.time=1500;updateZone(zoneWorld);assert.equal(zoneWorld.zone.r,170);assert.ok(DIFFICULTIES.hard.damage>DIFFICULTIES.easy.damage);
const config=await import('./battle-settings.js');const settings=config.getSettings();assert.ok(config.bindKey(settings.keys,'glue','KeyW'));assert.equal(config.bindKey(settings.keys,'glue','KeyT'),'');assert.ok(config.saveSettings(settings));assert.equal(config.getSettings().keys.glue,'KeyT');data['xanh-battle-settings-v3']='bad';assert.equal(config.getSettings().keys.glue,'KeyG');assert.ok(config.recordBattle({name:'Xanh',difficulty:'easy',kills:2,seconds:90,won:false}));assert.ok(config.recordBattle({name:'Win',difficulty:'hard',kills:1,seconds:100,won:true}));assert.equal(config.getRecords()[0].name,'Win');data['xanh-battle-records-v3']='[null,{},123]';assert.deepEqual(config.getRecords(),[]);console.log('PASS: slow parachute, landing protection, glue collision/bullets/expiry, vehicles, staged zone, remapping and local rankings.');

const flightTest=createWorld();stepWorld(flightTest,.04,{});const flightStart=flightTest.player.x;for(let i=0;i<125;i++)stepWorld(flightTest,.04,{});assert.ok(flightTest.player.x>flightStart+2800);assert.equal(flightTest.phase,'flight');for(let i=0;i<510;i++)stepWorld(flightTest,.04,{});assert.equal(flightTest.phase,'drop');assert.ok(flightTest.player.air);console.log('PASS: aircraft crosses island and automatically starts parachute descent after 25 seconds.');

const airborne=createWorld();const airLoot={x:airborne.player.x,y:airborne.player.y,type:'weapon',weapon:'sniper'};assert.equal(pickup(airborne,airborne.player,airLoot),false);jump(airborne);airLoot.x=airborne.player.x;assert.equal(pickup(airborne,airborne.player,airLoot),false);assert.equal(airborne.player.r,14);console.log('PASS: airborne pickup blocked and compact actor collision radius.');
