const allied=(a,b)=>a&&b&&a.team!==undefined&&a.team===b.team;
export const SIZE=16000;
export const DIFFICULTIES={easy:{name:"Tập sự",damage:.55,spread:.16,reaction:.85,cadence:1.8,guard:25},normal:{name:"Thường",damage:.8,spread:.09,reaction:.5,cadence:1.35,guard:15},hard:{name:"Thử thách",damage:1,spread:.045,reaction:.28,cadence:1,guard:8}};
export const CLASSES={vanguard:{name:'Tiên phong',hp:260,speed:145,damageScale:1,color:'#74b8c5'},ranger:{name:'Xạ thủ',hp:220,speed:150,damageScale:1.15,color:'#dcb277'},scout:{name:'Trinh sát',hp:235,speed:170,damageScale:1,color:'#98bc81'}};
export const WEAPONS={pistol:{name:'P12',kind:'Súng ngắn',mag:12,damage:10,delay:.3,speed:950,range:670,spread:.035,reload:1.1,ammo:'light',rank:1},smg:{name:'Viper',kind:'Tiểu liên',mag:32,damage:7,delay:.13,speed:1050,range:640,spread:.065,reload:1.5,ammo:'light',rank:2},rifle:{name:'AR-7',kind:'Súng trường',mag:30,damage:12,delay:.16,speed:1300,range:1000,spread:.025,reload:1.8,ammo:'heavy',rank:3},sniper:{name:'S96',kind:'Bắn tỉa',mag:5,damage:42,delay:1.15,speed:1900,range:1900,spread:.006,reload:2.3,ammo:'heavy',rank:3},shotgun:{name:'Búa Sấm',kind:'Shotgun',mag:6,damage:6,delay:.85,speed:950,range:390,spread:.23,reload:1.9,ammo:'shell',rank:2}};
export const AREAS=[{x:850,y:850,name:'CẢNG ĐỒNG',color:'#897961'},{x:2400,y:850,name:'TRẠM RADAR',color:'#747e78'},{x:3900,y:900,name:'KHO VẬN',color:'#817866'},{x:1000,y:2550,name:'LÀNG THÔNG',color:'#737d61'},{x:2550,y:2400,name:'TRUNG TÂM',color:'#899181'},{x:3900,y:2550,name:'XƯỞNG CƠ KHÍ',color:'#898373'},{x:1050,y:4000,name:'ĐỒI GIÓ',color:'#6c7d61'},{x:2600,y:3950,name:'TRẠM TIẾP TẾ',color:'#8a8068'},{x:3980,y:4000,name:'TIỀN ĐỒN',color:'#778170'}];
for(const a of AREAS){a.x*=SIZE/4800;a.y*=SIZE/4800;}
export const ROADS=[850,2400,3950].map(n=>n*SIZE/4800);
export const WALLS=[];
for(const [i,p]of AREAS.entries()){for(const [j,v]of [[-260,-200,170,110],[160,-180,110,220],[-240,150,230,90],[170,210,160,100],[-650,-500,210,100],[500,-430,180,140],[-650,420,160,220],[540,430,260,100]].entries())WALLS.push({x:p.x+v[0],y:p.y+v[1],w:v[2],h:v[3],type:j%2?'house':'container',tone:i%3});}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));export const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export function blocked(x,y,r=17,extra=[]){return x<r||y<r||x>SIZE-r||y>SIZE-r||[...WALLS,...extra].some(w=>(x-clamp(x,w.x,w.x+w.w))**2+(y-clamp(y,w.y,w.y+w.h))**2<r*r);}
export function moveActor(a,dx,dy,w){if(!blocked(a.x+dx,a.y,a.r,w?.covers))a.x+=dx;if(!blocked(a.x,a.y+dy,a.r,w?.covers))a.y+=dy;}
export function lineClear(a,b,w){for(const r of [...WALLS,...(w?.covers||[])]){let lo=0,hi=1;const dx=b.x-a.x,dy=b.y-a.y;for(const [p,q]of [[-dx,a.x-r.x],[dx,r.x+r.w-a.x],[-dy,a.y-r.y],[dy,r.y+r.h-a.y]]){if(p===0){if(q<0){lo=2;break;}}else if(p<0)lo=Math.max(lo,q/p);else hi=Math.min(hi,q/p);}if(lo<=hi)return false;}return true;}
const CELL=100,N=SIZE/CELL,nav=Array.from({length:N*N},(_,i)=>!blocked((i%N+.5)*CELL,(Math.floor(i/N)+.5)*CELL,26));
export function findPath(a,b){const id=p=>clamp(Math.floor(p.y/CELL),0,N-1)*N+clamp(Math.floor(p.x/CELL),0,N-1),start=id(a),end=id(b),open=[start],came=new Map(),cost=new Map([[start,0]]),f=new Map([[start,0]]),closed=new Set();let last=start;for(let count=0;open.length&&count<900;count++){let bi=0;for(let i=1;i<open.length;i++)if(f.get(open[i])<f.get(open[bi]))bi=i;const cur=open.splice(bi,1)[0];last=cur;if(cur===end)break;closed.add(cur);const x=cur%N,y=Math.floor(cur/N);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,v=ny*N+nx;if(nx<0||ny<0||nx>=N||ny>=N||!nav[v]||closed.has(v))continue;const c=cost.get(cur)+1;if(c<(cost.get(v)??Infinity)){came.set(v,cur);cost.set(v,c);f.set(v,c+Math.abs(nx-end%N)+Math.abs(ny-Math.floor(end/N)));if(!open.includes(v))open.push(v);}}}const path=[];while(last!==start&&came.has(last)){path.push({x:(last%N+.5)*CELL,y:(Math.floor(last/N)+.5)*CELL});last=came.get(last);}return path.reverse();}
function gun(id){return {id,ammo:WEAPONS[id].mag};}export function currentGun(a){return a.slots[a.active];}export function gunInfo(a){return WEAPONS[currentGun(a)?.id]||null;}
export function createWorld(classId='vanguard',random=Math.random,difficulty='easy'){const difficultyId=Object.hasOwn(DIFFICULTIES,difficulty)?difficulty:'easy',diff=DIFFICULTIES[difficultyId];const c=CLASSES[classId]||CLASSES.vanguard;const actors=Array.from({length:25},(_,i)=>{const area=AREAS[i%AREAS.length],x=i?area.x+(i%3-1)*560:SIZE/2,y=i?area.y+((i*7)%3-1)*490:SIZE/2;return {id:i,x,y,r:14,hp:i?220:c.hp,maxHp:i?220:c.hp,speed:i?145:c.speed,damageScale:i?diff.damage:c.damageScale,angle:0,vx:0,vy:0,cool:0,reload:0,shield:0,dash:0,shieldCd:0,novaCd:0,kills:0,level:1,alive:true,color:i?['#b28872','#92a6ae','#c0ad77'][i%3]:c.color,bot:i>0,strafe:random()>.5?1:-1,think:0,react:diff.reaction+random()*.3,targetId:null,path:[],pathTime:0,slots:[gun('pistol'),null],active:0,bag:{light:60,heavy:0,shell:0,med:3,glue:3},armor:50,vehicle:null,guard:i?8:diff.guard,glueCd:0,healing:0,air:true,altitude:1,landTime:18+(i%6),goal:{x,y},seen:null};});const loot=[];for(const [i,p]of AREAS.entries())for(let j=0;j<36;j++){const angle=j*2.39996,r=50+(j%9)*85,x=p.x+Math.cos(angle)*r,y=p.y+Math.sin(angle)*r;if(blocked(x,y,24))continue;const type=j%5===0?'weapon':j%5===1?'med':j%5===2?'armor':j%7===0?'glue':'ammo';loot.push({id:loot.length,x,y,type,weapon:['rifle','smg','sniper','shotgun'][(i+j)%4],ammo:['heavy','light','shell'][(i+j)%3],amount:45});}return {actors,player:actors[0],bullets:[],effects:[],loot,time:0,zone:{x:SIZE/2,y:SIZE/2,r:SIZE*.72,stage:0,remaining:120},covers:[],vehicles:AREAS.map((a,i)=>({id:i,x:a.x+80,y:a.y-70,angle:0,hp:500,maxHp:500,fuel:120,driver:null,speed:620})),status:'playing',random,events:[],classId,phase:'flight',flight:0,difficulty:difficultyId,diff};}
export function jump(w){if(w.phase!=='flight')return false;w.phase='drop';w.player.x=800+w.flight*(SIZE-1600)/25;w.player.y=SIZE/2;w.player.altitude=1;w.events.push({type:'jump'});return true;}
export function switchWeapon(a,slot){if(slot<0||slot>1||!a.slots[slot])return false;a.active=slot;a.reload=0;return true;}
export function reload(a){const g=currentGun(a),s=gunInfo(a);if(a.air||!g||a.reload||g.ammo>=s.mag||a.bag[s.ammo]<=0)return false;a.reload=s.reload;return true;}
export function heal(a){if(a.air||a.healing||a.bag.med<1||a.hp>=a.maxHp)return false;a.healing=2.5;return true;}
export function pickup(w,a,l){if(!l||l.used||a.air||w.phase==='flight'||distance(a,l)>75)return false;if(l.type==='weapon'){let slot=a.slots.findIndex(x=>!x);if(slot<0)slot=a.active;const old=a.slots[slot];a.slots[slot]={id:l.weapon,ammo:l.dropped?clamp(l.loaded??0,0,WEAPONS[l.weapon].mag):WEAPONS[l.weapon].mag};a.active=slot;a.reload=0;if(!l.dropped)a.bag[WEAPONS[l.weapon].ammo]=Math.min(240,a.bag[WEAPONS[l.weapon].ammo]+WEAPONS[l.weapon].mag*2);if(old)w.loot.push({x:a.x+30,y:a.y,type:'weapon',weapon:old.id,loaded:old.ammo,dropped:true});}else if(l.type==='ammo'){if(a.bag[l.ammo]>=240)return false;a.bag[l.ammo]=Math.min(240,a.bag[l.ammo]+l.amount);}else if(l.type==='glue'){if(a.bag.glue>=6)return false;a.bag.glue++;}else if(l.type==='med'){if(a.bag.med>=5)return false;a.bag.med++;}else if(l.type==='armor'){if(a.armor>=100)return false;a.armor=100;}l.used=true;w.events.push({type:'pickup',actor:a.id});return true;}
export function nearestLoot(w,a=w.player){let best=null,d=76;for(const l of w.loot){const n=distance(a,l);if(!l.used&&n<d){best=l;d=n;}}return best;}
function fx(w,x,y,color,count=7){w.effects.push({x,y,color,life:.35,count});}
function hit(w,a,amount,source){if(!a.alive||a.air||a.guard>0||allied(a,source))return;let damage=a.shield>0?amount*.3:amount;const absorbed=Math.min(a.armor,damage*.45);a.armor-=absorbed;a.hp-=damage-absorbed;a.healing=0;fx(w,a.x,a.y,'#e8b57b');if(source)a.seen={x:source.x,y:source.y,until:w.time+4};if(a.hp>0)return;a.hp=0;a.alive=false;w.events.push({type:'kill',actor:a.id,source:source?.id});for(const [i,g]of a.slots.entries())if(g)w.loot.push({x:a.x+i*30,y:a.y,type:'weapon',weapon:g.id,loaded:g.ammo,dropped:true});w.loot.push({x:a.x,y:a.y+28,type:'med'});if(source&&source.id!==a.id){source.kills++;source.level=1+Math.floor(source.kills/2);}}
function shoot(w,a,angle){const g=currentGun(a),s=gunInfo(a);if(!a.alive||a.air||a.vehicle!==null||!g||a.cool>0||a.reload>0||a.healing>0)return;if(g.ammo<=0){reload(a);return;}g.ammo--;a.guard=0;a.cool=s.delay*(a.bot?w.diff.cadence:1);a.angle=angle;const pellets=g.id==='shotgun'?7:1;for(let i=0;i<pellets;i++){const d=angle+(w.random()-.5)*(s.spread+(a.bot?w.diff.spread:0));w.bullets.push({x:a.x+Math.cos(d)*27,y:a.y+Math.sin(d)*27,vx:Math.cos(d)*s.speed,vy:Math.sin(d)*s.speed,speed:s.speed,owner:a.id,damage:s.damage*a.damageScale,life:s.range/s.speed});}w.events.push({type:'shot',actor:a.id});}
export function ability(w,type){const p=w.player;if(w.status!=='playing'||!p.alive||p.air||p.vehicle!==null)return false;if(type==='dash'&&p.dash<=0){for(let i=0;i<18;i++)moveActor(p,Math.cos(p.angle)*9,Math.sin(p.angle)*9,w);p.dash=4;}else if(type==='shield'&&p.shieldCd<=0){p.shield=3;p.shieldCd=12;}else if(type==='nova'&&p.novaCd<=0){p.novaCd=16;for(const a of w.actors)if(a.id!==p.id&&!allied(a,p)&&a.alive&&distance(p,a)<210&&lineClear(p,a,w))hit(w,a,60,p);w.effects.push({x:p.x,y:p.y,color:'#e9b472',life:.65,count:210,nova:true});}else return false;return true;}
function botThink(w,a){let target=null,best=1000;for(const b of w.actors){if(b.id===a.id||allied(a,b)||!b.alive||b.air)continue;const d=distance(a,b);if(d<best&&lineClear(a,b,w)){best=d;target=b;}}if(a.targetId!==target?.id)a.react=w.diff.reaction+w.random()*.25;a.targetId=target?.id??null;const outside=distance(a,w.zone)>w.zone.r-500;if(outside){a.goal={x:w.zone.x,y:w.zone.y};a.mode='zone';}else if(target){a.seen={x:target.x,y:target.y,until:w.time+5};if(a.hp<95||a.reload>0){if(a.hp<95&&a.glueCd<=0)deployGlue(w,a);let cover=null,cd=Infinity;for(const wall of WALLS){for(const pos of [{x:wall.x-35,y:wall.y-35},{x:wall.x+wall.w+35,y:wall.y-35},{x:wall.x-35,y:wall.y+wall.h+35},{x:wall.x+wall.w+35,y:wall.y+wall.h+35}]){const d=distance(a,pos);if(d<cd&&d<600&&!blocked(pos.x,pos.y)&&!lineClear(pos,target,w)){cover=pos;cd=d;}}}a.goal=cover||{x:a.x+(a.x-target.x)*.4,y:a.y+(a.y-target.y)*.4};a.mode='cover';}else{const s=gunInfo(a),ideal=s?.range*.52||250,ang=Math.atan2(a.y-target.y,a.x-target.x)+a.strafe*.38;a.goal={x:target.x+Math.cos(ang)*Math.min(520,ideal),y:target.y+Math.sin(ang)*Math.min(520,ideal)};a.mode='fight';}}else{if(a.hp<a.maxHp*.65)heal(a);const useful=w.loot.filter(l=>!l.used&&distance(a,l)<850&&((l.type==='weapon'&&WEAPONS[l.weapon].rank>(gunInfo(a)?.rank||0))||(l.type==='armor'&&a.armor<30)||(l.type==='med'&&a.bag.med<2)||(l.type==='glue'&&a.bag.glue<2)||(l.type==='ammo'&&a.bag[l.ammo]<60))).sort((b,c)=>distance(a,b)-distance(a,c))[0];a.goal=useful?{x:useful.x,y:useful.y}:a.seen&&a.seen.until>w.time?a.seen:a.goal;a.mode=useful?'loot':'patrol';if(!useful&&distance(a,a.goal)<90){const p=AREAS[Math.floor(w.random()*AREAS.length)];a.goal={x:p.x,y:p.y};}}
a.goal.x=clamp(a.goal.x,50,SIZE-50);a.goal.y=clamp(a.goal.y,50,SIZE-50);if(a.pathTime<=0&&!lineClear(a,a.goal,w)){a.path=findPath(a,a.goal);a.pathTime=1.1+w.random()*.5;}else if(lineClear(a,a.goal,w))a.path=[];
}
export function stepWorld(w,dt,input={}){if(w.status!=='playing')return;dt=clamp(dt,0,.05);w.events=[];w.time+=dt;if(w.phase==='flight'){w.flight+=dt;w.player.x=800+w.flight*(SIZE-1600)/25;w.player.y=SIZE/2;if(input.jump||w.flight>=25)jump(w);return;}updateZone(w);for(const c of w.covers)c.life-=dt;w.covers=w.covers.filter(c=>c.life>0&&c.hp>0);const p=w.player;
for(const a of w.actors){if(!a.alive||a.inPlane)continue;const controls=w.network?(w.inputs?.[a.id]||{}):input;const old={x:a.x,y:a.y};if(a.air){a.altitude-=dt/(a.bot?a.landTime:18);const dx=a.bot?0:controls.x||0,dy=a.bot?0:controls.y||0;a.x=clamp(a.x+dx*170*dt,40,SIZE-40);a.y=clamp(a.y+dy*170*dt,40,SIZE-40);if(a.altitude<=0){a.air=false;a.altitude=0;for(let i=0;blocked(a.x,a.y)&&i<100;i++){a.x=clamp(a.x+18,30,SIZE-30);a.y=clamp(a.y+12,30,SIZE-30);}if(a.id===0){for(const enemy of w.actors.slice(1))if(!w.network&&distance(a,enemy)<1100){const ang=enemy.id*2.39996;enemy.x=clamp(a.x+Math.cos(ang)*1400,100,SIZE-100);enemy.y=clamp(a.y+Math.sin(ang)*1400,100,SIZE-100);for(let tries=0;blocked(enemy.x,enemy.y)&&tries<100;tries++)enemy.x=clamp(enemy.x+20,30,SIZE-30);enemy.goal={x:enemy.x,y:enemy.y};}w.phase='combat';w.events.push({type:'land'});}}continue;}
for(const k of ['cool','shield','dash','shieldCd','novaCd','react','pathTime','guard','glueCd'])a[k]=Math.max(0,a[k]-dt);if(a.healing>0){a.healing=Math.max(0,a.healing-dt);if(!a.healing&&a.bag.med>0){a.bag.med--;a.hp=Math.min(a.maxHp,a.hp+65);}}
if(a.reload>0){a.reload=Math.max(0,a.reload-dt);if(!a.reload){const g=currentGun(a),s=gunInfo(a),n=Math.min(s.mag-g.ammo,a.bag[s.ammo]);g.ammo+=n;a.bag[s.ammo]-=n;}}
if(distance(a,w.zone)>w.zone.r)hit(w,a,(w.time>600?12:4)*dt,null);if(!a.alive)continue;
if(!a.bot){const dx=controls.x||0,dy=controls.y||0,n=Math.max(1,Math.hypot(dx,dy));if(a.vehicle!==null){const v=w.vehicles[a.vehicle];if(!v||v.hp<=0){a.vehicle=null;a.r=14;}else{if(v.fuel>0){moveActor(a,dx/n*v.speed*dt,dy/n*v.speed*dt,w);if(dx||dy){v.angle=Math.atan2(dy,dx);v.fuel=Math.max(0,v.fuel-dt);}}v.x=a.x;v.y=a.y;}}else moveActor(a,dx/n*a.speed*dt,dy/n*a.speed*dt,w);if(Number.isFinite(controls.angle))a.angle=controls.angle;if(controls.reload)reload(a);if(controls.fire)shoot(w,a,a.angle);}else{a.think-=dt;if(a.think<=0){botThink(w,a);a.think=.18+(a.id%4)*.025;if(w.random()<.06)a.strafe*=-1;}const target=w.actors[a.targetId];if(target?.alive&&!target.air){const d=distance(a,target);let bestSlot=a.active,bestScore=-1;for(let si=0;si<2;si++){const gg=a.slots[si];if(!gg)continue;const spec=WEAPONS[gg.id];if(gg.ammo+a.bag[spec.ammo]===0)continue;const score=spec.damage/spec.delay*(d<spec.range?.8:.05)*(gg.id==='shotgun'?(d<200?4:.3):1);if(score>bestScore){bestSlot=si;bestScore=score;}}if(bestSlot!==a.active&&!a.reload)switchWeapon(a,bestSlot);const s=gunInfo(a),lead=Math.min(.65,d/(s?.speed||1000));a.angle=Math.atan2(target.y+target.vy*lead-a.y,target.x+target.vx*lead-a.x);if(a.react<=0&&d<(s?.range||0)*.94&&lineClear(a,target,w))shoot(w,a,a.angle);if(a.hp<65&&a.shieldCd<=0){a.shield=2;a.shieldCd=14;}}if(a.path.length&&distance(a,a.path[0])<38)a.path.shift();const dest=a.path[0]||a.goal,heading=Math.atan2(dest.y-a.y,dest.x-a.x);if(distance(a,dest)>24&&!a.healing){moveActor(a,Math.cos(heading)*a.speed*dt,Math.sin(heading)*a.speed*dt,w);if(distance(old,a)<.2){moveActor(a,Math.cos(heading+Math.PI/2*a.strafe)*a.speed*dt,Math.sin(heading+Math.PI/2*a.strafe)*a.speed*dt,w);a.pathTime=0;}}const l=nearestLoot(w,a);if(l&&(l.type!=='weapon'||WEAPONS[l.weapon].rank>(gunInfo(a)?.rank||0)))pickup(w,a,l);if((currentGun(a)?.ammo||0)<3)reload(a);}
a.vx=(a.x-old.x)/dt||0;a.vy=(a.y-old.y)/dt||0;}
for(const b of w.bullets){b.life-=dt;const sub=Math.max(1,Math.ceil(b.speed*dt/10));for(let i=0;i<sub&&b.life>0;i++){b.x+=b.vx*dt/sub;b.y+=b.vy*dt/sub;const cover=w.covers.find(c=>b.x>=c.x-3&&b.x<=c.x+c.w+3&&b.y>=c.y-3&&b.y<=c.y+c.h+3);if(cover){cover.hp-=b.damage;b.life=0;fx(w,b.x,b.y,'#afd5d9',5);break;}const vehicle=w.vehicles.find(v=>v.hp>0&&v.driver!==b.owner&&!allied(w.actors[v.driver],w.actors[b.owner])&&distance(v,b)<37);if(vehicle){vehicle.hp=Math.max(0,vehicle.hp-b.damage);b.life=0;fx(w,b.x,b.y,'#e5ba80',5);if(!vehicle.hp&&vehicle.driver!==null){const driver=w.actors[vehicle.driver];driver.vehicle=null;driver.r=14;vehicle.driver=null;hit(w,driver,35,w.actors[b.owner]);}break;}if(blocked(b.x,b.y,3)){b.life=0;fx(w,b.x,b.y,'#b7ad90',3);break;}const victim=w.actors.find(a=>a.alive&&!a.air&&a.id!==b.owner&&!allied(a,w.actors[b.owner])&&distance(a,b)<a.r+3);if(victim){hit(w,victim,b.damage,w.actors[b.owner]);b.life=0;}}}w.bullets=w.bullets.filter(b=>b.life>0);w.loot=w.loot.filter(l=>!l.used);for(const e of w.effects)e.life-=dt;w.effects=w.effects.filter(e=>e.life>0).slice(-100);if(!w.network){if(!p.alive)w.status='lost';else if(w.actors.filter(a=>a.alive).length===1)w.status='won';}}

export function updateZone(w){const phases=[{wait:120,shrink:120,r:SIZE*.39},{wait:60,shrink:100,r:SIZE*.22},{wait:50,shrink:90,r:SIZE*.105},{wait:35,shrink:90,r:SIZE*.045},{wait:20,shrink:90,r:170}];let t=Math.max(0,w.time-43),from=SIZE*.72;for(let i=0;i<phases.length;i++){const phase=phases[i];if(t<phase.wait){Object.assign(w.zone,{r:from,stage:i+1,remaining:Math.ceil(phase.wait-t),shrinking:false});return;}t-=phase.wait;if(t<phase.shrink){Object.assign(w.zone,{r:from+(phase.r-from)*t/phase.shrink,stage:i+1,remaining:Math.ceil(phase.shrink-t),shrinking:true});return;}t-=phase.shrink;from=phase.r;}Object.assign(w.zone,{r:170,stage:6,remaining:0,shrinking:false});}
export function deployGlue(w,a=w.player){if(w.status!=='playing'||!a.alive||a.air||a.vehicle!==null||a.bag.glue<1||a.glueCd>0||w.covers.length>=32)return false;const x=a.x+Math.cos(a.angle)*110,y=a.y+Math.sin(a.angle)*110,vertical=Math.abs(Math.cos(a.angle))>.7,c={x:x-(vertical?14:90),y:y-(vertical?90:14),w:vertical?28:180,h:vertical?180:28,hp:480,maxHp:480,life:55,owner:a.id};const intersects=r=>c.x<r.x+r.w&&c.x+c.w>r.x&&c.y<r.y+r.h&&c.y+c.h>r.y;if(c.x<20||c.y<20||c.x+c.w>SIZE-20||c.y+c.h>SIZE-20||[...WALLS,...w.covers].some(intersects)||w.actors.some(p=>p.alive&&p.x>c.x-25&&p.x<c.x+c.w+25&&p.y>c.y-25&&p.y<c.y+c.h+25)||w.vehicles.some(v=>v.hp>0&&v.x>c.x-45&&v.x<c.x+c.w+45&&v.y>c.y-45&&v.y<c.y+c.h+45))return false;w.covers.push(c);a.bag.glue--;a.glueCd=a.bot?12:.8;w.events.push({type:'glue',actor:a.id});return true;}
export function toggleVehicle(w){const p=w.player;if(w.status!=='playing'||!p.alive||p.air)return false;if(p.vehicle!==null){const v=w.vehicles[p.vehicle];for(const ang of [v.angle+Math.PI/2,v.angle-Math.PI/2,v.angle+Math.PI,v.angle]){const x=v.x+Math.cos(ang)*70,y=v.y+Math.sin(ang)*70;if(!blocked(x,y,18,w.covers)){p.x=x;p.y=y;p.r=14;p.vehicle=null;v.driver=null;return true;}}return false;}const v=w.vehicles.find(v=>v.hp>0&&v.driver===null&&distance(p,v)<100);if(!v)return false;p.vehicle=v.id;p.r=38;p.x=v.x;p.y=v.y;v.driver=p.id;p.healing=0;p.reload=0;return true;}
