import {SIZE,WALLS,CLASSES,createWorld,stepWorld,ability} from './battle-engine.js';
import {loadEquipment,awardBattle} from './beta-shop.js';
const $=s=>document.querySelector(s),canvas=$('#arena'),ctx=canvas.getContext('2d');let choice='vanguard',world=createWorld(choice),playing=false,paused=false,finished=false,last=0,keys=new Set(),mouse={x:700,y:340,fire:false},cam={x:350,y:560},move={x:0,y:0},aim={angle:0,fire:false},sound=false,audio=null,noticeTimer;
function tone(f=400,d=.06){if(!sound||!audio||audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f/2,audio.currentTime+d);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d);}
function notice(t){$('#notice').textContent=t;$('#notice').style.opacity='1';clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').style.opacity='0',2300);}
function rect(x,y,w,h,color,r=0){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}function circle(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function draw(){const w=canvas.width,h=canvas.height,p=world.player;cam.x=Math.max(0,Math.min(SIZE-w,p.x-w/2));cam.y=Math.max(0,Math.min(SIZE-h,p.y-h/2));ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(-cam.x,-cam.y);rect(0,0,SIZE,SIZE,'#49564a');
for(let y=0;y<SIZE;y+=70)for(let x=0;x<SIZE;x+=70){rect(x+1,y+1,68,68,(x/70+y/70)%3===0?'#4c594a':'#465247');const n=Math.sin(x*13+y*7);rect(x+18,y+25,2,7,n>0?'#738065':'#374b40');rect(x+36,y+47,8,2,'#667158');}
rect(850,0,100,SIZE,'#737569');rect(0,850,SIZE,100,'#737569');for(let n=0;n<SIZE;n+=60){rect(897,n,5,25,'#aeac8a');rect(n,897,25,5,'#aeac8a');}circle(900,900,160,'#5c645b');ctx.strokeStyle='#a6ac90';ctx.lineWidth=3;ctx.beginPath();ctx.arc(900,900,135,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#c2bea0';ctx.font='bold 18px sans-serif';ctx.fillText('TRẠM 07',860,860);
for(const wall of WALLS){rect(wall.x+9,wall.y+12,wall.w,wall.h,'#14201b55',4);rect(wall.x,wall.y,wall.w,wall.h,'#788082',4);rect(wall.x+5,wall.y+4,wall.w-10,wall.h-10,'#9ca096',3);rect(wall.x+10,wall.y+10,wall.w-20,wall.h-20,'#767f79',2);for(let x=wall.x+15;x<wall.x+wall.w-10;x+=35)rect(x,wall.y+12,2,wall.h-25,'#596966');}
for(const l of world.loot){circle(l.x,l.y,20,l.type==='med'?'#192f2388':'#20324288');rect(l.x-11,l.y-11,22,22,l.type==='med'?'#dde5cc':'#9cbed3',5);ctx.fillStyle='#3b6a4e';ctx.font='bold 22px sans-serif';ctx.textAlign='center';ctx.fillText(l.type==='med'?'+':'◇',l.x,l.y+7);ctx.textAlign='left';}
for(const a of world.actors){if(!a.alive){circle(a.x,a.y,12,'#29352b');continue;}circle(a.x+5,a.y+8,21,'#14201c66');ctx.save();ctx.translate(a.x,a.y);ctx.rotate(a.angle);rect(-13,-20,25,40,'#23353b',8);rect(-14,-15,29,30,a.color,9);rect(8,-6,31,10,'#2b3438',3);rect(26,-5,15,4,'#c3baa0');circle(-1,0,11,a.bot?'#694e43':'#dad4b9');rect(4,-7,7,14,'#293940',3);rect(-19,-11,7,22,'#4b5146',3);ctx.restore();if(a.shield>0){ctx.strokeStyle='#a3c9e2';ctx.lineWidth=3;ctx.beginPath();ctx.arc(a.x,a.y,26,0,Math.PI*2);ctx.stroke();}rect(a.x-20,a.y-32,40,5,'#192326');rect(a.x-20,a.y-32,40*a.hp/a.maxHp,5,a.bot?'#ce997c':'#b4cc9b');if(!a.bot){ctx.fillStyle='#fff0ce';ctx.font='bold 10px sans-serif';ctx.textAlign='center';ctx.fillText('BẠN · CẤP '+a.level,a.x,a.y-40);ctx.textAlign='left';}}
for(const b of world.bullets){ctx.strokeStyle=b.owner===0?'#ffe1a0':'#e8a284';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-b.vx*.014,b.y-b.vy*.014);ctx.stroke();}for(const e of world.effects){ctx.globalAlpha=Math.min(1,e.life*3);if(e.nova){ctx.strokeStyle=e.color;ctx.lineWidth=5;ctx.beginPath();ctx.arc(e.x,e.y,210*(1-e.life/.65),0,Math.PI*2);ctx.stroke();}else for(let i=0;i<e.count;i++){const a=i*2.4,r=(.4-e.life)*90;circle(e.x+Math.cos(a)*r,e.y+Math.sin(a)*r,2,e.color);}}ctx.globalAlpha=1;
// Even-odd fill shades the outside of the safe circle without covering its interior.
ctx.fillStyle='#5e3c7277';ctx.beginPath();ctx.rect(0,0,SIZE,SIZE);ctx.arc(900,900,world.zone.r,0,Math.PI*2,true);ctx.fill('evenodd');ctx.strokeStyle='#b5bed1';ctx.lineWidth=4;ctx.beginPath();ctx.arc(900,900,world.zone.r,0,Math.PI*2);ctx.stroke();ctx.restore();
const mm=112,mx=w-mm-16,my=16;rect(mx-5,my-5,mm+10,mm+10,'#18242de8',5);rect(mx,my,mm,mm,'#4c5b4a');for(const wall of WALLS)rect(mx+wall.x/SIZE*mm,my+wall.y/SIZE*mm,wall.w/SIZE*mm,wall.h/SIZE*mm,'#a1a699');ctx.strokeStyle='#d8cdaf';ctx.lineWidth=1;ctx.beginPath();ctx.arc(mx+mm/2,my+mm/2,Math.min(mm*.69,world.zone.r/SIZE*mm),0,Math.PI*2);ctx.stroke();for(const a of world.actors)if(a.alive)circle(mx+a.x/SIZE*mm,my+a.y/SIZE*mm,a.bot?2:3,a.bot?'#dd9f83':'#e7f4ce');
if(playing&&!paused&&!aim.fire){ctx.strokeStyle='#f0ead5';ctx.lineWidth=1;ctx.beginPath();ctx.arc(mouse.x,mouse.y,8,0,Math.PI*2);ctx.moveTo(mouse.x-13,mouse.y);ctx.lineTo(mouse.x+13,mouse.y);ctx.moveTo(mouse.x,mouse.y-13);ctx.lineTo(mouse.x,mouse.y+13);ctx.stroke();}}
function hud(){const p=world.player;$('#hp').textContent=Math.ceil(p.hp)+' / '+p.maxHp;$('#health').max=p.maxHp;$('#health').value=p.hp;$('#ammo').textContent=p.reload?'Đang nạp…':p.ammo+' / 24';$('#alive').textContent=world.actors.filter(a=>a.alive).length;$('#kills').textContent=p.kills+' / '+p.level;$('#zone').textContent=Math.round(world.zone.r)+' m';for(const [id,key,label]of [['dash','dash','Space'],['shield','shieldCd','Q'],['nova','novaCd','E']]){$('#'+id).textContent=p[key]>0?p[key].toFixed(1)+' giây':label+' · Sẵn sàng';document.querySelector('[data-skill="'+id+'"]').disabled=!playing||paused||p[key]>0;}}
function end(){finished=true;playing=false;mouse.fire=false;aim.fire=false;const reward=awardBattle(world.player.kills,world.status==='won');$('#menu').classList.remove('hidden');$('#menu h1').textContent=world.status==='won'?'CHIẾN THẮNG!':'HẸN Ở TRẬN TIẾP THEO.';$('#intro').textContent='Hạ '+world.player.kills+' đối thủ · Sống sót '+Math.floor(world.time)+' giây · +'+reward+' xu beta trên máy này.';$('#start').textContent='CHƠI LẠI ↗';$('#pause').textContent='Tạm dừng';}
function loop(t){const dt=last?Math.min(.04,(t-last)/1000):0;last=t;if(playing&&!paused){const p=world.player;const angle=aim.fire?aim.angle:Math.atan2(mouse.y+cam.y-p.y,mouse.x+cam.x-p.x);stepWorld(world,dt,{x:move.x+(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0),y:move.y+(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0),angle,fire:mouse.fire||aim.fire,reload:keys.has('r')});for(const e of world.events){if(e.type==='shot'&&e.actor===0)tone(150,.035);if(e.type==='pickup'){tone(700,.12);notice('Đã nhận tiếp tế');}if(e.type==='kill'&&e.source===0){tone(500,.16);notice('Hạ gục! '+(world.player.kills%2===0?'Tăng cấp — thêm máu và sát thương.':''));}}if(world.status!=='playing'&&!finished)end();}draw();hud();requestAnimationFrame(loop);}
async function start(){const b=$('#start');if(b.disabled)return;b.disabled=true;const equipment=await loadEquipment();b.disabled=false;world=createWorld(choice);const skin=equipment.battle;if(skin==='battle-cobalt')world.player.color='#5897c5';if(skin==='battle-ember')world.player.color='#d39456';playing=true;paused=false;finished=false;keys.clear();mouse.fire=false;aim.fire=false;$('#menu').classList.add('hidden');$('#pause').textContent='Tạm dừng';canvas.focus();if(sound)audio?.resume();notice('Trận BETA bắt đầu · 8 bot · Nhặt tiếp tế để sống sót');}
function pause(){if(!playing)return;paused=!paused;keys.clear();mouse.fire=false;aim.fire=false;move={x:0,y:0};$('#pause').textContent=paused?'Tiếp tục':'Tạm dừng';if(paused){$('#menu').classList.remove('hidden');$('#menu h1').textContent='TẠM DỪNG';$('#intro').textContent='Trận đấu đã dừng. Bấm tiếp tục khi sẵn sàng.';$('.classes').classList.add('hidden');$('#start').textContent='TIẾP TỤC ↗';audio?.suspend();}else{$('#menu').classList.add('hidden');$('.classes').classList.remove('hidden');if(sound)audio?.resume();canvas.focus();}}
$('#start').onclick=()=>paused?pause():start();$('#pause').onclick=pause;$('#audio').onclick=()=>{sound=!sound;$('#audio').textContent='♫ Âm: '+(sound?'Bật':'Tắt');$('#audio').setAttribute('aria-pressed',String(sound));if(sound){try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{sound=false;$('#audio').textContent='Âm thanh không hỗ trợ';}}else audio?.suspend();};document.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{choice=b.dataset.class;document.querySelectorAll('[data-class]').forEach(c=>{c.classList.toggle('selected',c===b);c.setAttribute('aria-pressed',String(c===b));});});document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>{if(!paused&&ability(world,b.dataset.skill))tone(420,.15);});$('#reload').onclick=()=>{if(playing&&!paused&&world.player.ammo<24&&!world.player.reload)world.player.reload=1.35;};
canvas.onpointermove=e=>{const r=canvas.getBoundingClientRect();mouse.x=(e.clientX-r.left)*canvas.width/r.width;mouse.y=(e.clientY-r.top)*canvas.height/r.height;};canvas.onpointerdown=e=>{if(e.button!==0)return;canvas.onpointermove(e);mouse.fire=true;canvas.focus();canvas.setPointerCapture(e.pointerId);};canvas.onpointerup=canvas.onpointercancel=()=>mouse.fire=false;
document.addEventListener('keydown',e=>{if(e.target.closest('button')||!playing)return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(['w','a','s','d','q','e','r','p',' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(k))e.preventDefault();keys.add(k);if(!e.repeat){if(k==='p')pause();else if(!paused&&[' ','q','e'].includes(k)){if(ability(world,{' ':'dash',q:'shield',e:'nova'}[k]))tone(420,.15);}}});document.addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener('blur',()=>{if(playing&&!paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing&&!paused)pause();});
for(const [id,isAim]of [['move-pad',false],['aim-pad',true]]){const pad=$('#'+id);let active=null;function update(e){if(e.pointerId!==active)return;const r=pad.getBoundingClientRect(),dx=(e.clientX-r.left-r.width/2)/(r.width/2),dy=(e.clientY-r.top-r.height/2)/(r.height/2),n=Math.max(1,Math.hypot(dx,dy));pad.querySelector('i').style.transform='translate('+dx/n*25+'px,'+dy/n*25+'px)';if(isAim){if(Math.hypot(dx,dy)>.15){aim.angle=Math.atan2(dy,dx);aim.fire=true;}}else move={x:dx/n,y:dy/n};}pad.onpointerdown=e=>{e.preventDefault();active=e.pointerId;pad.setPointerCapture(active);update(e);};pad.onpointermove=update;pad.onpointerup=pad.onpointercancel=e=>{if(e.pointerId!==active)return;active=null;pad.querySelector('i').style.transform='';if(isAim)aim.fire=false;else move={x:0,y:0};};}
function resize(){const r=canvas.getBoundingClientRect();canvas.width=r.width<650?700:1100;canvas.height=Math.round(canvas.width*r.height/r.width);}window.addEventListener('resize',resize);resize();requestAnimationFrame(loop);
