export const ITEMS=[{id:'battle-cobalt',slot:'battle',name:'Chiến binh Cobalt',price:150,color:'#5897c5',description:'Giáp xanh thép cho Xanh Battle.'},{id:'battle-ember',slot:'battle',name:'Chiến binh Hổ Phách',price:220,color:'#d39456',description:'Giáp hổ phách cho Xanh Battle.'},{id:'robot-cobalt',slot:'runner',name:'Robot Cobalt',price:120,color:'#5897c5',description:'Sơn xanh thép cho Robot phiêu lưu.'},{id:'robot-forest',slot:'runner',name:'Robot Kiểm Lâm',price:160,color:'#8db990',description:'Sơn xanh rừng cho Robot phiêu lưu.'},{id:'paddle-copper',slot:'paddle',name:'Thanh đỡ Đồng Đỏ',price:100,color:'#d39456',description:'Thanh đỡ màu đồng trong Phá gạch.'},{id:'board-slate',slot:'board',name:'Bàn cờ Đá Xám',price:180,color:'#8195a6',description:'Đổi bàn caro sang đá phiến.'}];
const KEY='xa_beta_wallet_v1';let fallback=null;
export function getSave(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Number.isSafeInteger(s.coins)&&s.coins>=0&&Array.isArray(s.owned)){const owned=s.owned.filter(id=>ITEMS.some(i=>i.id===id));const equipped={};for(const [slot,id]of Object.entries(s.equipped||{}))if(owned.includes(id)&&ITEMS.some(i=>i.id===id&&i.slot===slot))equipped[slot]=id;return {coins:s.coins,owned,equipped,daily:typeof s.daily==='string'?s.daily:''};}}catch{}return fallback||{coins:300,owned:[],equipped:{},daily:''};}
function save(s){fallback=s;try{localStorage.setItem(KEY,JSON.stringify(s));return true;}catch{return false;}}
export function purchase(id){const s=getSave(),item=ITEMS.find(x=>x.id===id);if(!item)throw Error('Không có vật phẩm này.');if(s.owned.includes(id))return s;if(s.coins<item.price)throw Error('Chưa đủ xu. Chơi Xanh Battle hoặc nhận quà hằng ngày nhé.');s.coins-=item.price;s.owned.push(id);if(!save(s))throw Error('Trình duyệt chặn lưu dữ liệu. Đồ chỉ giữ đến khi đóng trang.');return s;}
export function equip(id){const s=getSave(),item=ITEMS.find(x=>x.id===id);if(!item||!s.owned.includes(id))throw Error('Bạn chưa sở hữu vật phẩm này.');if(s.equipped[item.slot]===id)delete s.equipped[item.slot];else s.equipped[item.slot]=id;save(s);return s;}
export function claimDaily(){const s=getSave(),today=new Date().toISOString().slice(0,10);if(s.daily===today)throw Error('Đã nhận hôm nay. Quà mới mở lúc 07:00 giờ Việt Nam.');s.daily=today;s.coins+=75;save(s);return s;}
export function awardBattle(kills,won){const n=Math.min(150,Math.max(0,Math.floor(kills))*15+(won?30:0));const s=getSave();s.coins+=n;save(s);return n;}
if(typeof document!=='undefined'&&document.querySelector('#shop-grid')){
const $=s=>document.querySelector(s);let ownedOnly=false;function message(t){$('#shop-message').textContent=t;}
function render(){const s=getSave();$('#coins').textContent=s.coins;$('#owned-count').textContent=s.owned.length;$('#daily').disabled=s.daily===new Date().toISOString().slice(0,10);$('#daily').textContent=$('#daily').disabled?'Đã nhận hôm nay':'+75 xu · Nhận quà';const list=ITEMS.filter(i=>!ownedOnly||s.owned.includes(i.id));$('#shop-grid').innerHTML=list.length?list.map(i=>{const owned=s.owned.includes(i.id),active=s.equipped[i.slot]===i.id;return '<article><div class="item-art '+i.id+'"><span>'+({battle:'BATTLE',runner:'ROBOT',paddle:'PHÁ GẠCH',board:'CARO'}[i.slot])+'</span><div class="item-symbol">'+({battle:'◈',runner:'▣',paddle:'━',board:'▦'}[i.slot])+'</div></div><div class="item-info"><h2>'+i.name+'</h2><p>'+i.description+'</p><div><b>'+i.price+' xu</b><button data-item="'+i.id+'" data-owned="'+owned+'">'+(active?'Đang dùng · Tháo':owned?'Trang bị':'Mua vật phẩm')+'</button></div></div></article>';}).join(''):'<p>Tủ đồ đang trống. Ghé shop để chọn trang phục nhé.</p>';}
$('#shop-grid').onclick=e=>{const b=e.target.closest('[data-item]');if(!b)return;try{if(b.dataset.owned==='true'){equip(b.dataset.item);message('Đã cập nhật trang bị. Vào trận mới để sử dụng.');}else{purchase(b.dataset.item);message('Đã mua! Bấm Trang bị để dùng vật phẩm.');}}catch(err){message(err.message);}render();};$('#daily').onclick=()=>{try{claimDaily();message('Đã nhận 75 xu beta.');}catch(e){message(e.message);}render();};document.querySelectorAll('[data-shop-tab]').forEach(b=>b.onclick=()=>{ownedOnly=b.dataset.shopTab==='owned';document.querySelectorAll('[data-shop-tab]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));render();});window.addEventListener('storage',render);render();}
