// Native Canvas game rules. No Scratch VM or runtime project state is executed.
export const WIDTH=5760,HEIGHT=4320,TILE_W=480,TILE_H=360;
export const MODES={easy:{name:'Tập sự',damage:.5,spread:.18,delay:1.6},normal:{name:'Thường',damage:.75,spread:.1,delay:1.25},hard:{name:'Thử thách',damage:1,spread:.05,delay:1}};
const specs=[['standard pistol',12,9,.28,640,'light'],['crystal pistol',14,11,.26,700,'light'],['virtuous pistol',16,12,.26,740,'light'],['standard scattergun',6,5,.85,350,'shell',6],['crystal scattergun',7,6,.8,380,'shell',6],['virtuous scattergun',8,7,.85,410,'shell',6],['pump shotgun',5,8,1.05,390,'shell',7],['epic AR-15',30,11,.16,1050,'heavy'],['crystal M4',30,12,.16,1100,'heavy'],['virtuous scar',25,14,.2,1150,'heavy'],['p90',40,7,.1,650,'light'],['duals',24,8,.16,660,'light'],['deagle',7,24,.55,950,'heavy'],['bolt sniper',5,46,1.2,1800,'heavy'],['minigun',70,6,.085,950,'heavy'],['standard rocket launcher',1,55,1.8,1200,'rocket',1,105],['grenade launcher',4,38,1,850,'rocket',1,90],['flamethrower',50,4,.075,240,'light',1,0]];
export const GUNS=Object.fromEntries(specs.map(([id,mag,damage,delay,range,ammo,pellets=1,blast=0])=>[id,{id,mag,damage,delay,range,ammo,pellets,blast,speed:blast?550:1450,reload:blast?2.2:1.6}]));
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export function createTerrain(data,masks){const tiles=data.tiles;return {tiles,masks,point(x,y){if(x<480||x>=WIDTH-480||y<360||y>=HEIGHT-360)return true;const col=Math.floor(x/480),row=11-Math.floor(y/360),name=tiles[col*12+row],mask=masks[name];if(!mask)return false;const px=Math.floor((x%480)/8),py=Math.floor((y%360)/8);return mask[py*60+px]==='1';},tile(x,y){const col=clamp(Math.floor(x/480),0,11),row=clamp(11-Math.floor(y/360),0,11);return tiles[col*12+row];}};}
const inside=(p,r,pad=0)=>p.x>=r.x-pad&&p.x<=r.x+r.w+pad&&p.y>=r.y-pad&&p.y<=r.y+r.h+pad;
export function blocked(w,x,y,r=13){for(const [dx,dy]of [[0,0],[r,0],[-r,0],[0,r],[0,-r],[r*.7,r*.7],[-r*.7,r*.7],[r*.7,-r*.7],[-r*.7,-r*.7]])if(w.terrain.point(x+dx,y+dy))return true;return w.walls.some(a=>a.hp>0&&inside({x,y},a,r));}
export function safePoint(w,x,y){x=clamp(x,520,WIDTH-520);y=clamp(y,400,HEIGHT-400);if(!blocked(w,x,y,20))return {x,y};for(let r=24;r<900;r+=24)for(let k=0;k<16;k++){const a=k*Math.PI/8,xx=x+Math.cos(a)*r,yy=y+Math.sin(a)*r;if(!blocked(w,xx,yy,20))return {x:xx,y:yy};}throw Error('Không tìm được điểm đáp an toàn.');}
export function lineClear(w,a,b){const d=dist(a,b),steps=Math.ceil(d/8);for(let i=1;i<steps;i++){const x=a.x+(b.x-a.x)*i/steps,y=a.y+(b.y-a.y)*i/steps;if(w.terrain.point(x,y)||w.walls.some(c=>c.hp>0&&inside({x,y},c)))return false;}return true;}
function move(w,a,dx,dy){const steps=Math.max(1,Math.ceil(Math.max(Math.abs(dx),Math.abs(dy))/7));for(let i=0;i<steps;i++){if(!blocked(w,a.x+dx/steps,a.y,a.vehicle===null?13:28))a.x+=dx/steps;if(!blocked(w,a.x,a.y+dy/steps,a.vehicle===null?13:28))a.y+=dy/steps;}}
export const gun=a=>a.slots[a.slot];
const weapon=id=>({id,ammo:GUNS[id].mag});
function actor(i,p,mode){return {id:i,...p,hp:220,maxHp:220,armor:50,angle:0,alive:true,air:16+(i%5),guard:i?5:20,slots:[weapon(i%3?'standard pistol':'crystal M4'),null,null,null,null,null],slot:0,ammo:{light:90,heavy:90,shell:24,rocket:4},wood:40,med:3,grenades:3,vehicle:null,cool:0,reload:0,heal:0,think:0,goal:{...p},kills:0,skin:i%8,damage:i?MODES[mode].damage:1,vx:0,vy:0,stuck:0,strafe:i%2?1:-1,target:null,react:.7,tool:false,buildCd:0};}
export function createGame(data,masks,{difficulty='easy',skin=0,random=Math.random}={}){if(!Object.hasOwn(MODES,difficulty))difficulty='easy';const w={terrain:createTerrain(data,masks),difficulty,random,time:0,phase:'flight',flight:0,status:'playing',walls:[],bullets:[],effects:[],events:[],loot:[],trees:[],chests:[],cars:[],pads:[],actors:[],zone:{x:WIDTH/2,y:HEIGHT/2,r:3400,seconds:110,shrinking:false},tick:0};const seeds=data.spawns?.length?data.spawns:[{x:2000,y:2000}];w.actors=Array.from({length:25},(_,i)=>actor(i,safePoint(w,seeds[i%seeds.length].x,seeds[i%seeds.length].y),difficulty));w.player=w.actors[0];w.player.skin=clamp(skin,0,7);w.player.x=520;w.player.y=HEIGHT/2;w.player.air=16;
for(const [i,s]of seeds.entries()){const p=safePoint(w,s.x,s.y);for(let j=0;j<3;j++){const q=safePoint(w,p.x+Math.cos(j*2.1)*65,p.y+Math.sin(j*2.1)*65);w.loot.push({...q,id:i*3+j,type:j===0?'gun':j===1?'ammo':'med',gun:specs[i%specs.length][0],amount:30,ammo:['light','heavy','shell'][i%3]});}if(i%5===0)w.cars.push({...safePoint(w,p.x+110,p.y+50),id:w.cars.length,type:['motorcycle','shopping cart','skateboard','tank'][Math.floor(i/5)%4],hp:400,fuel:100,driver:null,angle:0});if(i%9===0)w.pads.push({...safePoint(w,p.x-100,p.y),cool:0});}
for(const p of data.trees||[])w.trees.push({...safePoint(w,p.x,p.y),hp:3,cherry:w.trees.length%3===0});for(let i=0;i<70;i++){const p=seeds[i%seeds.length],a=i*2.4;w.trees.push({...safePoint(w,p.x+Math.cos(a)*180,p.y+Math.sin(a)*180),hp:3,cherry:i%4===0});}
for(const p of data.chests||[])w.chests.push({...safePoint(w,p.x,p.y),open:false});return w;}
export function jump(w){if(w.phase!=='flight'||w.status!=='playing')return false;w.phase='drop';w.events.push({type:'jump'});return true;}
export function swap(w,index){const a=w.player;if(!Number.isInteger(index)||index<0||index>=6||!a.slots[index])return false;a.slot=index;a.reload=0;a.tool=false;return true;}
export function reload(a){const g=gun(a),s=g&&GUNS[g.id];if(!s||a.air>0||a.reload>0||g.ammo>=s.mag||a.ammo[s.ammo]<=0||a.tool)return false;a.reload=s.reload;return true;}
export function heal(a){if(a.air>0||a.med<=0||a.hp>=a.maxHp||a.heal>0)return false;a.heal=3;return true;}
export function nearby(w,a=w.player){if(a.air>0||w.phase==='flight'||a.vehicle!==null)return null;let best=null,d=80;for(const item of [...w.chests.filter(c=>!c.open),...w.loot]){const n=dist(a,item);if(n<d&&lineClear(w,a,item)){best=item;d=n;}}return best;}
export function collect(w,a=w.player,item=nearby(w,a)){if(!item||a.air>0||a.vehicle!==null||w.phase==='flight'||dist(a,item)>80||!lineClear(w,a,item))return false;if(Object.hasOwn(item,'open')){if(item.open)return false;item.open=true;const id=specs[Math.floor(w.random()*specs.length)][0];w.loot.push({x:item.x+25,y:item.y,type:'gun',gun:id},{x:item.x-25,y:item.y,type:'ammo',ammo:GUNS[id].ammo,amount:45},{x:item.x,y:item.y+30,type:'armor'});w.events.push({type:'chest'});return true;}const index=w.loot.indexOf(item);if(index<0)return false;if(item.type==='gun'){let slot=a.slots.findIndex(g=>!g);if(slot<0)slot=a.slot;const old=a.slots[slot];if(old)w.loot.push({x:a.x+25,y:a.y,type:'gun',gun:old.id,loaded:old.ammo});a.slots[slot]={id:item.gun,ammo:item.loaded??GUNS[item.gun].mag};a.slot=slot;a.reload=0;a.tool=false;if(item.loaded===undefined)a.ammo[GUNS[item.gun].ammo]=Math.min(300,a.ammo[GUNS[item.gun].ammo]+GUNS[item.gun].mag);}else if(item.type==='ammo'){if(a.ammo[item.ammo]>=300)return false;a.ammo[item.ammo]=Math.min(300,a.ammo[item.ammo]+item.amount);}else if(item.type==='armor'){if(a.armor>=100)return false;a.armor=100;}else if(item.type==='med'){if(a.med>=5)return false;a.med++;}else if(item.type==='wood'){a.wood=Math.min(200,a.wood+30);}w.loot.splice(index,1);w.events.push({type:'pickup',actor:a.id});return true;}
export function build(w){const a=w.player;if(a.air>0||w.phase==='flight'||a.vehicle!==null||a.wood<10||a.buildCd>0||w.walls.length>=80||w.status!=='playing')return false;const x=a.x+Math.cos(a.angle)*90,y=a.y+Math.sin(a.angle)*90,vertical=Math.abs(Math.cos(a.angle))>.7,c={x:x-(vertical?10:65),y:y-(vertical?65:10),w:vertical?20:130,h:vertical?130:20,hp:260,life:120};for(let xx=c.x;xx<=c.x+c.w;xx+=8)for(let yy=c.y;yy<=c.y+c.h;yy+=8)if(blocked(w,xx,yy,5))return false;if(w.actors.some(b=>b.alive&&inside(b,c,22))||w.cars.some(b=>b.hp>0&&inside(b,c,40)))return false;w.walls.push(c);a.wood-=10;a.buildCd=.4;w.events.push({type:'build'});return true;}
export function enterCar(w){const a=w.player;if(a.air>0||w.phase==='flight'||w.status!=='playing')return false;if(a.vehicle!==null){const c=w.cars[a.vehicle];for(let k=0;k<8;k++){const p={x:c.x+Math.cos(k*Math.PI/4)*65,y:c.y+Math.sin(k*Math.PI/4)*65};if(!blocked(w,p.x,p.y,14)){Object.assign(a,p);c.driver=null;a.vehicle=null;return true;}}return false;}const c=w.cars.find(c=>c.hp>0&&c.driver===null&&dist(a,c)<85&&!blocked(w,c.x,c.y,28));if(!c)return false;a.x=c.x;a.y=c.y;c.driver=a.id;a.vehicle=c.id;a.reload=0;a.heal=0;return true;}
function damage(w,a,n,owner){if(!a.alive||a.air>0||a.guard>0)return;const absorb=Math.min(a.armor,n*.45);a.armor-=absorb;a.hp=Math.max(0,a.hp-n+absorb);a.heal=0;if(a.hp===0){a.alive=false;if(a.vehicle!==null){w.cars[a.vehicle].driver=null;a.vehicle=null;}const killer=w.actors[owner];if(killer&&killer!==a)killer.kills++;for(const g of a.slots)if(g)w.loot.push({x:a.x+w.random()*30,y:a.y+w.random()*30,type:'gun',gun:g.id,loaded:g.ammo});w.events.push({type:'kill',actor:a.id,owner});}}
function explosion(w,b){const radius=b.blast;w.effects.push({x:b.x,y:b.y,r:radius,life:.5,type:'explosion'});for(const a of w.actors)if(dist(a,b)<radius&&lineClear(w,b,a))damage(w,a,b.damage*(1-dist(a,b)/radius*.6),b.owner);for(const c of w.walls)if(dist({x:c.x+c.w/2,y:c.y+c.h/2},b)<radius)c.hp-=b.damage;w.events.push({type:'boom'});}
export function throwGrenade(w){const a=w.player;if(a.air>0||a.vehicle!==null||w.phase==='flight'||a.grenades<1||a.cool>0||w.status!=='playing')return false;a.grenades--;a.cool=.6;a.guard=0;w.bullets.push({x:a.x+Math.cos(a.angle)*25,y:a.y+Math.sin(a.angle)*25,vx:Math.cos(a.angle)*350,vy:Math.sin(a.angle)*350,owner:0,damage:45,life:1,blast:125});return true;}
export function shoot(w,a){if(a.cool>0||a.reload>0||a.heal>0||a.air>0||!a.alive||a.vehicle!==null)return;if(a.tool){a.cool=.38;a.guard=0;const point={x:a.x+Math.cos(a.angle)*48,y:a.y+Math.sin(a.angle)*48};const tree=w.trees.find(t=>t.hp>0&&dist(t,point)<75&&lineClear(w,a,t));if(tree){tree.hp--;a.wood=Math.min(200,a.wood+10);w.events.push({type:'chop'});}for(const b of w.actors)if(b!==a&&dist(b,point)<55&&lineClear(w,a,b))damage(w,b,18,a.id);w.effects.push({...point,r:42,life:.2,type:'swing'});return;}const g=gun(a),s=g&&GUNS[g.id];if(!s)return;if(g.ammo<=0){reload(a);return;}g.ammo--;a.guard=0;a.cool=s.delay*(a.id?MODES[w.difficulty].delay:1);for(let i=0;i<s.pellets;i++){const spread=s.pellets>1?.38:s.id==='bolt sniper'?.005:.025,angle=a.angle+(w.random()-.5)*(spread+(a.id?MODES[w.difficulty].spread:0));w.bullets.push({x:a.x+Math.cos(angle)*24,y:a.y+Math.sin(angle)*24,vx:Math.cos(angle)*s.speed,vy:Math.sin(angle)*s.speed,owner:a.id,damage:s.damage*a.damage,life:s.range/s.speed,blast:s.blast});}w.events.push({type:'shot',actor:a.id});}
function bot(w,a,dt){a.think-=dt;const previous={x:a.x,y:a.y};if(a.think<=0){a.think=.25+(a.id%4)*.04;let target=null,d=950;for(const b of w.actors)if(b!==a&&b.alive&&b.air<=0&&dist(a,b)<d&&lineClear(w,a,b)){target=b;d=dist(a,b);}if(a.target!==target?.id)a.react=.6;a.target=target?.id??null;if(dist(a,w.zone)>w.zone.r-160)a.goal={x:w.zone.x,y:w.zone.y};else if(target){const angle=Math.atan2(a.y-target.y,a.x-target.x)+a.strafe*.5,range=GUNS[gun(a).id].range*.48;a.goal={x:target.x+Math.cos(angle)*Math.min(440,range),y:target.y+Math.sin(angle)*Math.min(440,range)};}else{const loot=w.loot.filter(l=>dist(a,l)<450&&(l.type==='gun'||l.type==='ammo'||l.type==='armor'&&a.armor<50)).sort((b,c)=>dist(a,b)-dist(a,c))[0];if(loot)a.goal={x:loot.x,y:loot.y};else if(dist(a,a.goal)<50)a.goal=safePoint(w,900+w.random()*(WIDTH-1800),700+w.random()*(HEIGHT-1400));if(a.hp<130)heal(a);}a.goal.x=clamp(a.goal.x,520,WIDTH-520);a.goal.y=clamp(a.goal.y,400,HEIGHT-400);}
const target=w.actors[a.target];if(target?.alive&&a.react<=0&&dist(a,target)<GUNS[gun(a).id].range&&lineClear(w,a,target)){const lead=dist(a,target)/1450;a.angle=Math.atan2(target.y+target.vy*lead-a.y,target.x+target.vx*lead-a.x);shoot(w,a);}let angle=Math.atan2(a.goal.y-a.y,a.goal.x-a.x);if(a.stuck>0)angle+=a.strafe*1.35;if(!a.heal&&dist(a,a.goal)>20){move(w,a,Math.cos(angle)*145*dt,Math.sin(angle)*145*dt);if(dist(a,previous)<.5){a.stuck=.8;if(w.random()<.1)a.strafe*=-1;}}if(!target)a.angle=angle;const item=nearby(w,a);if(item)collect(w,a,item);if(gun(a).ammo<2)reload(a);}
export function step(w,dt,input={}){if(w.status!=='playing'||!Number.isFinite(dt)||dt<=0)return;dt=Math.min(.05,dt);w.time+=dt;w.tick++;w.events=[];const p=w.player;if(w.phase==='flight'){w.flight+=dt;p.x=520+(WIDTH-1040)*Math.min(1,w.flight/22);p.y=HEIGHT/2;if(w.flight>=22)jump(w);return;}
const elapsed=Math.max(0,w.time-38),cycle=190,round=Math.min(4,Math.floor(elapsed/cycle)),radii=[3400,2300,1450,780,330,110],phase=elapsed%cycle,progress=clamp((phase-100)/90,0,1);w.zone.r=radii[round]+(radii[round+1]-radii[round])*progress;w.zone.seconds=Math.ceil(phase<100?100-phase:190-phase);w.zone.shrinking=phase>=100;if(elapsed>=950){w.zone.r=110;w.zone.seconds=0;}
for(const a of w.actors){if(!a.alive)continue;if(a.air>0){if(!a.id){const n=Math.max(1,Math.hypot(input.x||0,input.y||0));a.x=clamp(a.x+(input.x||0)/n*145*dt,520,WIDTH-520);a.y=clamp(a.y+(input.y||0)/n*145*dt,400,HEIGHT-400);}a.air=Math.max(0,a.air-dt);if(!a.air){Object.assign(a,safePoint(w,a.x,a.y));if(!a.id){w.phase='combat';for(const enemy of w.actors.slice(1))if(dist(a,enemy)<600)Object.assign(enemy,safePoint(w,a.x+Math.cos(enemy.id*2.4)*850,a.y+Math.sin(enemy.id*2.4)*850));w.events.push({type:'land'});}}continue;}
for(const k of ['cool','guard','react','buildCd','stuck'])a[k]=Math.max(0,a[k]-dt);if(a.reload>0){a.reload=Math.max(0,a.reload-dt);if(!a.reload){const g=gun(a),s=GUNS[g.id],n=Math.min(s.mag-g.ammo,a.ammo[s.ammo]);g.ammo+=n;a.ammo[s.ammo]-=n;}}
if(a.heal>0){a.heal=Math.max(0,a.heal-dt);if(!a.heal&&a.med>0){a.med--;a.hp=Math.min(a.maxHp,a.hp+80);}}if(dist(a,w.zone)>w.zone.r)damage(w,a,(elapsed>650?10:4)*dt,null);if(!a.alive)continue;const old={x:a.x,y:a.y};if(a.id)bot(w,a,dt);else{const n=Math.max(1,Math.hypot(input.x||0,input.y||0)),car=a.vehicle!==null?w.cars[a.vehicle]:null,speed=car?(car.fuel>0?car.type==='tank'?280:420:0):170;move(w,a,(input.x||0)/n*speed*dt,(input.y||0)/n*speed*dt);if(Number.isFinite(input.angle))a.angle=input.angle;if(car){car.x=a.x;car.y=a.y;if(input.x||input.y){car.angle=Math.atan2(input.y||0,input.x||0);car.fuel=Math.max(0,car.fuel-dt);}}if(input.fire)shoot(w,a);if(input.reload)reload(a);}
a.vx=(a.x-old.x)/dt;a.vy=(a.y-old.y)/dt;
for(const pad of w.pads)if(a.vehicle===null&&pad.cool<=0&&dist(a,pad)<28){a.air=5;pad.cool=6;w.events.push({type:'launch'});break;}}
for(const b of w.bullets){b.life-=dt;const n=Math.max(1,Math.ceil(Math.hypot(b.vx,b.vy)*dt/6));let impact=false;for(let i=0;i<n&&b.life>0;i++){b.x+=b.vx*dt/n;b.y+=b.vy*dt/n;const wall=w.walls.find(c=>c.hp>0&&inside(b,c,2));if(wall){wall.hp-=b.damage;b.life=0;impact=true;break;}if(w.terrain.point(b.x,b.y)){b.life=0;impact=true;break;}const car=w.cars.find(c=>c.hp>0&&c.driver!==b.owner&&dist(c,b)<30);if(car){car.hp=Math.max(0,car.hp-b.damage);b.life=0;impact=true;if(!car.hp&&car.driver!==null){const a=w.actors[car.driver];a.vehicle=null;car.driver=null;damage(w,a,30,b.owner);}break;}const a=w.actors.find(a=>a.alive&&a.air<=0&&a.id!==b.owner&&dist(a,b)<15);if(a){if(!b.blast)damage(w,a,b.damage,b.owner);b.life=0;impact=true;break;}}if(b.life<=0&&b.blast)explosion(w,b);else if(impact)w.effects.push({x:b.x,y:b.y,r:12,life:.15,type:'hit'});}
w.bullets=w.bullets.filter(b=>b.life>0).slice(-300);for(const a of w.walls)a.life-=dt;w.walls=w.walls.filter(a=>a.life>0&&a.hp>0);for(const p of w.pads)p.cool=Math.max(0,p.cool-dt);for(const e of w.effects)e.life-=dt;w.effects=w.effects.filter(e=>e.life>0).slice(-100);w.loot=w.loot.slice(-550);if(!p.alive)w.status='lost';else if(w.actors.filter(a=>a.alive).length===1)w.status='won';}
