import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createGame,step,jump,collect,nearby,swap,reload,heal,build,blocked,safePoint,lineClear,enterCar,throwGrenade,GUNS,WIDTH,HEIGHT} from './fortnite-engine.js';
const data=JSON.parse(fs.readFileSync(new URL('./fortnite-assets/world.json',import.meta.url))),masks=JSON.parse(fs.readFileSync(new URL('./fortnite-assets/collision.json',import.meta.url))),manifest=JSON.parse(fs.readFileSync(new URL('./fortnite-assets/manifest.json',import.meta.url)));
assert.equal(data.tiles.length,144);assert.equal(Object.keys(GUNS).length,18);for(const tile of data.tiles)assert.ok(manifest['tile-'+tile]);for(const meta of Object.values(manifest)){assert.match(meta.src,/^\/fortnite-assets\/[a-zA-Z0-9_-]+\.svg$/);const content=fs.readFileSync(new URL('.'+meta.src,import.meta.url),'utf8');assert.doesNotMatch(content,/<script|<foreignObject|onload\s*=/i);}
const fresh=()=>createGame(data,masks,{random:()=>.51});const w=fresh();assert.equal(w.actors.length,25);assert.equal(w.player.slots.length,6);step(w,.05);const x=w.player.x;for(let i=0;i<100;i++)step(w,.05);assert.ok(w.player.x>x+1000);assert.equal(collect(w,w.player,{x:w.player.x,y:w.player.y,type:'med'}),false);for(let i=0;i<350;i++)step(w,.05);assert.equal(w.phase,'drop');assert.ok(w.player.air>0);for(let i=0;i<330;i++)step(w,.05);assert.equal(w.player.air,0);assert.ok(!blocked(w,w.player.x,w.player.y));assert.ok(w.player.guard>18);
const p=w.player;w.actors.slice(1).forEach(a=>{a.air=999;});const item={x:p.x,y:p.y,type:'gun',gun:'bolt sniper'};w.loot.push(item);assert.ok(collect(w,p,item));assert.equal(p.slots[1].id,'bolt sniper');assert.equal(collect(w,p,item),false);assert.ok(swap(w,0));assert.ok(swap(w,1));p.slots[1].ammo=0;p.ammo.heavy=2;assert.ok(reload(p));for(let i=0;i<110;i++)step(w,.02);assert.equal(p.slots[1].ammo,2);assert.equal(p.ammo.heavy,0);p.hp=100;assert.ok(heal(p));for(let i=0;i<160;i++)step(w,.02);assert.equal(p.hp,180);assert.equal(p.med,2);
for(let i=0;i<6;i++)p.slots[i]={id:'standard pistol',ammo:3};p.slot=0;const reserve=p.ammo.light;const drop={x:p.x,y:p.y,type:'gun',gun:'crystal M4',loaded:4};w.loot.push(drop);assert.ok(collect(w,p,drop));assert.equal(p.slots[0].ammo,4);assert.equal(p.ammo.light,reserve);assert.ok(w.loot.some(l=>l.gun==='standard pistol'&&l.loaded===3));
const chest={x:p.x,y:p.y,open:false};w.chests.push(chest);assert.ok(collect(w,p,chest));assert.equal(collect(w,p,chest),false);
let built=false;for(const s of data.spawns){Object.assign(p,safePoint(w,s.x,s.y));for(let i=0;i<8;i++){p.angle=i*Math.PI/4;if(build(w)){built=true;break;}}if(built)break;}assert.ok(built);assert.equal(p.wood,30);const wall=w.walls[0];assert.ok(blocked(w,wall.x+wall.w/2,wall.y+wall.h/2));assert.equal(build(w),false);wall.life=.01;step(w,.02);assert.equal(w.walls.length,0);
let car=w.cars.find(c=>!blocked(w,c.x,c.y,28));assert.ok(car);Object.assign(p,{x:car.x,y:car.y});assert.ok(enterCar(w));assert.equal(p.vehicle,car.id);assert.equal(collect(w,p,{x:p.x,y:p.y,type:'med'}),false);const fuel=car.fuel;step(w,.02,{x:1});assert.ok(car.fuel<fuel);assert.ok(enterCar(w));assert.equal(car.driver,null);assert.equal(p.vehicle,null);
p.cool=0;const grenades=p.grenades;assert.ok(throwGrenade(w));assert.equal(p.grenades,grenades-1);assert.equal(throwGrenade(w),false);assert.ok(w.bullets.some(b=>b.blast===125));
const sim=fresh();jump(sim);const t=performance.now();for(let i=0;i<26000&&sim.status==='playing';i++)step(sim,.04,{x:i%300<150?.3:-.3,angle:0,fire:i%4===0});assert.ok(['won','lost'].includes(sim.status));assert.ok(sim.actors.every(a=>Number.isFinite(a.x)&&Number.isFinite(a.y)&&a.x>=0&&a.x<=WIDTH&&a.y>=0&&a.y<=HEIGHT));assert.ok(sim.bullets.length<=300);assert.ok(sim.effects.length<=100);assert.ok(sim.loot.length<=550);console.log('Fortnite simulation:',Math.round(performance.now()-t),'ms; match',Math.round(sim.time),'seconds; result',sim.status);
// Deliberately run a long storm-only match without shooting to verify eventual completion.
const storm=fresh();jump(storm);for(let i=0;i<28000&&storm.status==='playing';i++)step(storm,.05,{});assert.notEqual(storm.status,'playing');
console.log('PASS Fortnite Z: original asset routes, flight/descent, ground-only loot, 6 slots, ammo conservation, healing, one-time chests, wall collision/cost, vehicles/fuel, grenades, finite simulation and cleanup.');

// F must open a real map chest even when closer loose loot cannot be collected.
const cw=fresh();cw.phase='drop';const cp=cw.player;cp.air=0;cp.armor=100;cp.med=5;cp.wood=200;cp.ammo.light=300;
for(const c of cw.chests){
Object.assign(cp,{x:c.x,y:c.y});cw.loot=[{x:cp.x,y:cp.y,type:'armor'},{x:cp.x,y:cp.y,type:'med'},{x:cp.x,y:cp.y,type:'ammo',ammo:'light',amount:30},{x:cp.x,y:cp.y,type:'wood'}];
assert.equal(nearby(cw),c);assert.equal(collect(cw),true);assert.equal(c.open,true);assert.equal(collect(cw,cp,c),false);
}
cw.chests=[];cw.loot=[{x:cp.x,y:cp.y,type:'armor'},{x:cp.x,y:cp.y,type:'med'},{x:cp.x,y:cp.y,type:'ammo',ammo:'light',amount:30},{x:cp.x,y:cp.y,type:'wood'}];assert.equal(nearby(cw),null);assert.equal(collect(cw),false);
const cc={x:cp.x,y:cp.y,open:false};cw.chests=[cc];cp.air=1;assert.equal(collect(cw),false);cp.air=0;cp.vehicle=0;assert.equal(collect(cw),false);cp.vehicle=null;cw.walls=[{x:cp.x+10,y:cp.y-30,w:10,h:60,hp:100}];cc.x+=40;assert.equal(nearby(cw),null);assert.equal(collect(cw,cp,cc),false);
console.log('PASS chest priority, all map chests, full supplies, one-time rewards, airborne/vehicle/wall restrictions');

const priority=fresh();priority.phase='drop';priority.player.air=0;priority.terrain.point=()=>false;Object.assign(priority.player,{x:1000,y:1000,armor:100});const priorityChest={x:1060,y:1000,open:false};priority.chests=[priorityChest];priority.loot=[{x:1000,y:1000,type:'armor'}];assert.equal(nearby(priority),priorityChest);assert.equal(collect(priority),true);assert.equal(priorityChest.open,true);
