import {WIDTH,HEIGHT,GUNS,MODES,createGame,step,jump,gun,swap,reload,heal,nearby,collect,build,enterCar,throwGrenade,dist,clamp} from './fortnite-engine.js';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d'),keys=new Set(),sprites=new Map(),skins=['Yellow Guy','Pink Guy','Soldier','General Select','Cowboy','Samurai','Silver Soldier','Gold General'];
let world=null,data,masks,manifest,playing=false,paused=false,last=0,accumulator=0,hudAt=0,ended=false,cam={x:0,y:0},mouse={x:600,y:375,fire:false},touchMove={x:0,y:0},touchAim={angle:0,fire:false},noticeTimer,sound=false,audio;
const slotButtons=Array.from({length:6},(_,i)=>{const b=document.createElement('button');b.innerHTML='<img alt=""><b></b><small></small>';b.onclick=()=>act(()=>swap(world,i));b.setAttribute('aria-label','Ô súng '+(i+1));$('#slots').append(b);return b;});
function notice(text){$('#toast').textContent=text;$('#toast').style.opacity=1;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#toast').style.opacity=0,3000);}
function tone(type){if(!sound||!audio||audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain(),frequencies={shot:130,pickup:720,chest:560,build:230,chop:160,boom:65,land:280,kill:880,launch:430};o.type=type==='shot'||type==='boom'?'sawtooth':'triangle';o.frequency.setValueAtTime(frequencies[type]||300,audio.currentTime);o.frequency.exponentialRampToValueAtTime(45,audio.currentTime+.14);g.gain.setValueAtTime(type==='shot'?.025:.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.2);}
function rect(x,y,w,h,c,r=0){ctx.fillStyle=c;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}function circle(x,y,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function sprite(key,x,y,size,angle=0,alpha=1){const img=sprites.get(key);if(!img)return;const scale=size/Math.max(img.naturalWidth,img.naturalHeight);ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.globalAlpha=alpha;ctx.drawImage(img,-img.naturalWidth*scale/2,-img.naturalHeight*scale/2,img.naturalWidth*scale,img.naturalHeight*scale);ctx.restore();}
function tileDraw(key,x,y,alpha=1){const img=sprites.get(key),meta=manifest[key];if(!img||!meta)return;ctx.globalAlpha=alpha;ctx.drawImage(img,x+240-meta.cx,y+180-meta.cy);ctx.globalAlpha=1;}
const visible=(p,pad=100)=>p.x>cam.x-pad&&p.y>cam.y-pad&&p.x<cam.x+canvas.width+pad&&p.y<cam.y+canvas.height+pad;
function draw(){if(!world)return;const p=world.player,w=canvas.width,h=canvas.height;cam.x=clamp(p.x-w/2,0,WIDTH-w);cam.y=clamp(p.y-h/2,0,HEIGHT-h);ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(-cam.x,-cam.y);ctx.fillStyle='#477044';ctx.fillRect(cam.x,cam.y,w,h);const tiles=[];for(let col=Math.max(0,Math.floor(cam.x/480));col<=Math.min(11,Math.floor((cam.x+w)/480));col++)for(let row=Math.max(0,Math.floor(cam.y/360));row<=Math.min(11,Math.floor((cam.y+h)/360));row++){const name=data.tiles[col*12+11-row],x=col*480,y=row*360;tileDraw('tile-'+name,x,y);tiles.push({name,x,y});}
for(const pad of world.pads)if(visible(pad))sprite('launchpad',pad.x,pad.y,62);
for(const c of world.chests)if(visible(c)){circle(c.x+5,c.y+8,22,'#16351d55');sprite(c.open?'chest-open':'chest',c.x,c.y,40);if(!c.open){ctx.strokeStyle='#e3cb7a88';ctx.lineWidth=1;ctx.beginPath();ctx.arc(c.x,c.y,29+Math.sin(world.time*3)*2,0,Math.PI*2);ctx.stroke();}}
for(const item of world.loot)if(visible(item,40)){circle(item.x,item.y,19,'#11312399');const color=item.type==='gun'?GUNS[item.gun].blast?'#e6ba80':item.gun.includes('crystal')?'#8fe7e5':item.gun.includes('virtuous')?'#d5a0df':'#b9d1a0':'#bdcc93';ctx.strokeStyle=color;ctx.lineWidth=1;ctx.beginPath();ctx.arc(item.x,item.y,20,0,Math.PI*2);ctx.stroke();if(item.type==='gun')sprite('item-'+item.gun,item.x,item.y,31,-Math.PI/4);else if(item.type==='med')sprite('item-fruit',item.x,item.y,23);else{ctx.fillStyle=color;ctx.textAlign='center';ctx.font='bold 17px system-ui';ctx.fillText(item.type==='armor'?'◇':item.type==='wood'?'▥':'▤',item.x,item.y+6);}}
for(const a of world.actors){if(!a.alive||a.vehicle!==null||world.phase==='flight')continue;if(!visible(a))continue;circle(a.x+5,a.y+8,15,'#14271766');sprite('skin-'+skins[a.skin],a.x,a.y,31,a.angle+Math.PI/2);sprite('item-'+(a.tool?'axe':gun(a).id),a.x+Math.cos(a.angle)*15,a.y+Math.sin(a.angle)*15,31,a.angle+Math.PI/2);if(a.air>0){ctx.strokeStyle='#ece9ce';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(a.x-30,a.y-39);ctx.lineTo(a.x,a.y);ctx.lineTo(a.x+30,a.y-39);ctx.stroke();sprite(a.id%2?'skin-Brown':'skin-Crystal Blue',a.x,a.y-43,80);}else{rect(a.x-18,a.y-30,36,3,'#203022');rect(a.x-18,a.y-30,36*a.hp/a.maxHp,3,a.id?'#e3b183':'#d6e7a2');}if(!a.id){ctx.fillStyle='#fffbd9';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.fillText('BẠN',a.x,a.y-38);if(a.guard>0){ctx.strokeStyle='#d5eec67f';ctx.beginPath();ctx.arc(a.x,a.y,23,0,Math.PI*2);ctx.stroke();}}}
for(const c of world.cars)if(visible(c)){circle(c.x+7,c.y+10,34,'#13301e55');sprite('item-'+c.type,c.x,c.y,c.type==='tank'?88:68,c.angle+Math.PI/2,c.hp>0?1:.4);if(c.driver!==null)sprite('skin-'+skins[p.skin],c.x-8,c.y,24,c.angle+Math.PI/2);}
for(const wall of world.walls)if(visible({x:wall.x,y:wall.y},160)){const x=wall.x+wall.w/2,y=wall.y+wall.h/2;sprite('wall',x,y,135,wall.w>wall.h?0:Math.PI/2);rect(wall.x,wall.y-9,Math.max(wall.w,32)*wall.hp/260,3,'#dccca3');}
for(const t of world.trees)if(t.hp>0&&visible(t,160)){circle(t.x+14,t.y+20,43,'#12322040');sprite(t.cherry?'tree-cherry':'tree',t.x,t.y,104,0,dist(t,p)<75?.48:1);}
for(const t of tiles)if(sprites.has('roof-'+t.name)){const near=p.x>t.x&&p.x<t.x+480&&p.y>t.y&&p.y<t.y+360&&p.air<=0;tileDraw('roof-'+t.name,t.x,t.y,near?.15:.92);}
for(const b of world.bullets)if(visible(b)){ctx.strokeStyle=b.blast?'#f6ad52':b.owner?'#f7b18d':'#fff5ba';ctx.lineWidth=b.blast?5:2;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-b.vx*.014,b.y-b.vy*.014);ctx.stroke();}
for(const e of world.effects)if(visible(e,130)){ctx.globalAlpha=Math.min(1,e.life*3);circle(e.x,e.y,e.r*(1-e.life/.6),e.type==='explosion'?'#efb76d':'#eee8b2');ctx.globalAlpha=1;}
ctx.fillStyle='#705c895c';ctx.beginPath();ctx.rect(0,0,WIDTH,HEIGHT);ctx.arc(world.zone.x,world.zone.y,world.zone.r,0,Math.PI*2,true);ctx.fill('evenodd');ctx.strokeStyle='#decbed';ctx.lineWidth=3;ctx.beginPath();ctx.arc(world.zone.x,world.zone.y,world.zone.r,0,Math.PI*2);ctx.stroke();
if(world.phase==='flight'){circle(p.x+35,p.y+50,70,'#17362b35');sprite('plane',p.x,p.y,220,Math.PI/2);ctx.strokeStyle='#eaf6d950';ctx.lineWidth=3;for(const dy of [-35,35]){ctx.beginPath();ctx.moveTo(p.x-75,p.y+dy);ctx.lineTo(p.x-160,p.y+dy);ctx.stroke();}}
ctx.restore();const miniW=150,miniH=miniW*HEIGHT/WIDTH,x=w-miniW-16,y=16;rect(x-5,y-5,miniW+10,miniH+10,'#173025e8',6);ctx.fillStyle='#548248';ctx.fillRect(x,y,miniW,miniH);for(const car of world.cars)if(car.hp>0)rect(x+car.x/WIDTH*miniW,y+car.y/HEIGHT*miniH,3,3,'#efce78');ctx.save();ctx.beginPath();ctx.rect(x,y,miniW,miniH);ctx.clip();ctx.strokeStyle='#f0d9e3';ctx.lineWidth=1;ctx.beginPath();ctx.arc(x+world.zone.x/WIDTH*miniW,y+world.zone.y/HEIGHT*miniH,world.zone.r/WIDTH*miniW,0,Math.PI*2);ctx.stroke();circle(x+p.x/WIDTH*miniW,y+p.y/HEIGHT*miniH,3,'#fffade');ctx.restore();ctx.fillStyle='#e6e6ba';ctx.textAlign='left';ctx.font='9px system-ui';ctx.fillText('ĐẢO GỐC · FORTNITE Z',x,y+miniH+17);
if(playing&&!paused&&!p.air){ctx.strokeStyle='#fff6cd';ctx.lineWidth=1;ctx.beginPath();ctx.arc(mouse.x,mouse.y,6,0,Math.PI*2);ctx.stroke();}}
function hud(){if(!world)return;const p=world.player,g=gun(p);$('#hp').textContent=Math.ceil(p.hp);$('#hp-bar').value=p.hp;$('#armor').textContent=Math.ceil(p.armor);$('#armor-bar').value=p.armor;$('#kills').textContent=p.kills;$('#wood').textContent=p.wood;$('#ammo').textContent=p.reload?'Nạp…':p.tool?'RÌU':g.ammo+' / '+p.ammo[GUNS[g.id].ammo];$('#survivors').textContent=world.actors.filter(a=>a.alive).length+' CÒN SỐNG · '+MODES[world.difficulty].name.toUpperCase();$('#phase').textContent=world.phase==='flight'?'BAY '+Math.round(world.flight/22*100)+'% · NHẢY TRONG '+Math.ceil(22-world.flight)+'s':p.air>0?'ĐANG HẠ DÙ · '+Math.ceil(p.air)+'s':(world.zone.shrinking?'BO ĐANG THU':'BO SẼ THU')+' · '+world.zone.seconds+'s'+(p.guard>0?' · BẢO VỆ '+Math.ceil(p.guard)+'s':'');$('#jump').classList.toggle('hidden',!playing||paused||world.phase!=='flight');
for(let i=0;i<6;i++){const b=slotButtons[i],g=p.slots[i],image=b.querySelector('img');const url=g?manifest['item-'+g.id]?.src:'';if(image.getAttribute('src')!==url){if(url)image.src=url;else image.removeAttribute('src');}image.hidden=!g;b.querySelector('b').textContent=(i+1)+' · '+(g?g.id:'Ô trống');b.querySelector('small').textContent=g?g.ammo+' viên':'';b.classList.toggle('selected',p.slot===i&&!p.tool);b.setAttribute('aria-pressed',String(p.slot===i&&!p.tool));b.disabled=!g||!playing||paused||p.air>0;}
const item=nearby(world);$('#interact').textContent=p.air>0||world.phase==='flight'?'Đáp đất để nhặt':item?'F · '+(Object.hasOwn(item,'open')?'Mở rương':item.type==='gun'?item.gun:item.type==='ammo'?'Nhặt đạn':item.type==='armor'?'Nhặt giáp':'Nhặt đồ'):'F · Đến gần đồ / rương';$('#interact').disabled=!item||!playing||paused;$('#med').textContent=p.heal?'Đang hồi máu…':'H · Hồi máu ('+p.med+')';$('#grenade').textContent='Q · Lựu đạn ('+p.grenades+')';$('#car').textContent=p.vehicle===null?'V · Lên xe':'V · Xuống xe';const c=p.vehicle!==null?world.cars[p.vehicle]:null;$('#car-state').textContent=c?c.type.toUpperCase()+' · '+Math.ceil(c.hp)+' HP · '+Math.ceil(c.fuel)+'% XĂNG':'ĐI BỘ';$('#axe').setAttribute('aria-pressed',String(p.tool));}
function readSave(){try{const s=JSON.parse(localStorage.getItem('fortnite-z-native-v1'));return s&&Array.isArray(s.records)?s:{records:[]};}catch{return {records:[]};}}
function saveResult(){const s=readSave(),p=world.player;const row={name:$('#nickname').value.trim().slice(0,24)||'Xanh',won:world.status==='won',kills:p.kills,seconds:Math.floor(world.time),difficulty:world.difficulty};s.records=[row,...s.records.filter(r=>r&&typeof r.name==='string'&&Number.isFinite(r.kills)&&Number.isFinite(r.seconds)&&Object.hasOwn(MODES,r.difficulty))].sort((a,b)=>Number(b.won)-Number(a.won)||b.kills-a.kills||b.seconds-a.seconds).slice(0,30);try{localStorage.setItem('fortnite-z-native-v1',JSON.stringify(s));}catch{notice('Không lưu được thành tích trên trình duyệt này.');}}
function finish(){ended=true;playing=false;clearInput();saveResult();$('#overlay').classList.remove('hidden');$('#overlay-title').textContent=world.status==='won'?'VICTORY · SỐNG SÓT CUỐI CÙNG':'TRẬN ĐẤU KẾT THÚC';$('#overlay-info').textContent='Hạ '+world.player.kills+' đối thủ · Sống sót '+Math.floor(world.time)+' giây. Thành tích đã ghi trên máy này nếu trình duyệt cho phép lưu.';$('#resume').classList.add('hidden');$('#restart').textContent='Về sảnh / Chơi lại';}
function clearInput(){keys.clear();mouse.fire=false;touchAim.fire=false;touchMove={x:0,y:0};accumulator=0;}
function frame(t){const dt=last?Math.min(.1,(t-last)/1000):0;last=t;if(playing&&!paused){accumulator+=dt;let n=0;while(accumulator>=1/60&&n++<6){const p=world.player;step(world,1/60,{x:touchMove.x+(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),y:touchMove.y+(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0),angle:touchAim.fire?touchAim.angle:Math.atan2(mouse.y+cam.y-p.y,mouse.x+cam.x-p.x),fire:mouse.fire||touchAim.fire,reload:keys.has('KeyR')});accumulator-=1/60;for(const e of world.events){if(e.type!=='shot'||e.actor===0)tone(e.type);if(e.type==='land')notice('Đã đáp đất · F nhặt / mở rương · T dùng rìu · G xây tường');if(e.type==='kill'&&e.owner===0)notice('Hạ gục!');}if(world.status!=='playing'&&!ended){finish();break;}}}draw();if(t-hudAt>100){hud();hudAt=t;}requestAnimationFrame(frame);}
function act(fn){if(playing&&!paused&&world.status==='playing'){fn();hud();canvas.focus({preventScroll:true});}}
function start(){world=createGame(data,masks,{difficulty:$('#difficulty').value,skin:Number($('#skin').value)});playing=true;paused=false;ended=false;clearInput();$('#lobby').classList.add('hidden');$('#overlay').classList.add('hidden');$('#pause').textContent='Tạm dừng';canvas.focus({preventScroll:true});hud();notice('Máy bay Tac-Z đang bay. Bấm J để chọn điểm nhảy.');}
function pause(){if(!playing)return;paused=!paused;clearInput();$('#overlay').classList.toggle('hidden',!paused);$('#overlay-title').textContent='TẠM DỪNG';$('#overlay-info').textContent='Trận đấu đã dừng. Tiếp tục khi Xanh sẵn sàng.';$('#resume').classList.remove('hidden');$('#pause').textContent=paused?'Tiếp tục':'Tạm dừng';if(paused)audio?.suspend();else{if(sound)audio?.resume();canvas.focus({preventScroll:true});}}
$('#start').onclick=start;$('#pause').onclick=pause;$('#resume').onclick=pause;$('#restart').onclick=()=>{playing=false;paused=false;clearInput();$('#overlay').classList.add('hidden');$('#lobby').classList.remove('hidden');$('#jump').classList.add('hidden');$('#pause').textContent='Tạm dừng';};$('#jump').onclick=()=>act(()=>jump(world));$('#interact').onclick=()=>act(()=>collect(world));$('#axe').onclick=()=>act(()=>{world.player.tool=!world.player.tool;world.player.reload=0;});$('#build').onclick=()=>act(()=>{if(!build(world))notice('Cần 10 gỗ và khoảng trống phía trước để dựng tường.');});$('#car').onclick=()=>act(()=>{if(!enterCar(world))notice('Đến gần xe còn nguyên, ở chỗ rộng, rồi bấm V.');});$('#med').onclick=()=>act(()=>heal(world.player));$('#grenade').onclick=()=>act(()=>throwGrenade(world));$('#reload').onclick=()=>act(()=>reload(world.player));
$('#sound').onclick=()=>{sound=!sound;try{if(sound){audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();}else audio?.suspend();}catch{sound=false;}$('#sound').textContent='Âm thanh: '+(sound?'Bật':'Tắt');$('#sound').setAttribute('aria-pressed',String(sound));};
canvas.onpointermove=e=>{const r=canvas.getBoundingClientRect();mouse.x=(e.clientX-r.left)*canvas.width/r.width;mouse.y=(e.clientY-r.top)*canvas.height/r.height;};canvas.onpointerdown=e=>{if(e.button!==0)return;canvas.onpointermove(e);mouse.fire=true;canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);};canvas.onpointerup=canvas.onpointercancel=()=>mouse.fire=false;
document.addEventListener('keydown',e=>{if(e.target.closest('input,select,textarea')||$('#info-dialog').open||!playing)return;const code=e.code;if(['KeyW','KeyA','KeyS','KeyD','KeyF','KeyT','KeyG','KeyV','KeyH','KeyQ','KeyR','KeyJ','KeyP','Digit1','Digit2','Digit3','Digit4','Digit5','Digit6'].includes(code)){e.preventDefault();keys.add(code);}if(e.repeat)return;if(code==='KeyP'){pause();return;}if(paused)return;const actions={KeyF:'interact',KeyT:'axe',KeyG:'build',KeyV:'car',KeyH:'med',KeyQ:'grenade',KeyR:'reload',KeyJ:'jump'};if(actions[code])$('#'+actions[code]).click();if(/^Digit[1-6]$/.test(code))swap(world,Number(code.slice(-1))-1);});document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{if(playing&&!paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing&&!paused)pause();});
for(const [id,aim]of [['move-pad',false],['aim-pad',true]]){const pad=$('#'+id);let active=null;function update(e){if(e.pointerId!==active)return;const r=pad.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/(r.width/2),y=(e.clientY-r.top-r.height/2)/(r.height/2),n=Math.max(1,Math.hypot(x,y));pad.querySelector('i').style.transform='translate('+x/n*23+'px,'+y/n*23+'px)';if(aim){touchAim.fire=Math.hypot(x,y)>.18;if(touchAim.fire)touchAim.angle=Math.atan2(y,x);}else touchMove={x:x/n,y:y/n};}pad.onpointerdown=e=>{active=e.pointerId;pad.setPointerCapture(active);update(e);};pad.onpointermove=update;pad.onpointerup=pad.onpointercancel=e=>{if(e.pointerId!==active)return;active=null;pad.querySelector('i').style.transform='';if(aim)touchAim.fire=false;else touchMove={x:0,y:0};};}
function dialog(title){if(playing&&!paused)pause();$('#dialog-title').textContent=title;$('#dialog-content').replaceChildren();$('#info-dialog').showModal();return $('#dialog-content');}$('.close').onclick=()=>$('#info-dialog').close();
$('#help').onclick=()=>{const d=dialog('CẨM NANG SINH TỒN');const ul=document.createElement('ul');for(const text of ['J: nhảy khỏi máy bay. Dùng WASD / cần trái điều hướng dù; chỉ nhặt đồ sau khi đáp.','F: nhặt vật phẩm hoặc mở rương vàng. Có 6 ô súng, bấm 1–6 để đổi. Đầy túi sẽ thay súng đang cầm.','R: nạp đạn từ kho. Các súng dùng đạn nhẹ, đạn trường, shotgun hoặc rocket.','T: chọn rìu; ngắm vào cây rồi giữ chuột trái để lấy gỗ. G: dựng tường, tốn 10 gỗ.','V: lên/xuống xe. Xe cần xăng và có thể bị phá hủy. Bệ phóng đưa người chơi lên dù.','H: dùng túi hồi 80 máu. Q: ném lựu đạn. Tránh vùng bo tím.','Điện thoại: cần trái di chuyển, cần phải ngắm và bắn; chạm các nút bên dưới.','P: tạm dừng. Chuyển tab sẽ tự dừng để tránh chết khi không chơi.','Bản chuyển thể BETA: 24 bot, thành tích lưu trên máy. Chế độ cloud, trailer và mã lưu Scratch cũ chưa chuyển.']){const li=document.createElement('li');li.textContent=text;ul.append(li);}d.append(ul);};
$('#map').onclick=()=>{if(!world)return;const d=dialog('BẢN ĐỒ FORTNITE Z'),c=document.createElement('canvas');c.width=720;c.height=540;const g=c.getContext('2d');g.fillStyle='#426745';g.fillRect(0,0,720,540);for(let col=0;col<12;col++)for(let row=0;row<12;row++){const img=sprites.get('tile-'+data.tiles[col*12+11-row]);if(img)g.drawImage(img,col*60,row*45,60,45);}g.strokeStyle='#ffe1ee';g.lineWidth=2;g.beginPath();g.arc(world.zone.x/8,world.zone.y/8,world.zone.r/8,0,Math.PI*2);g.stroke();for(const car of world.cars){if(!car.hp)continue;g.fillStyle='#ffd475';g.fillRect(car.x/8-2,car.y/8-2,4,4);}g.fillStyle='#fff';g.beginPath();g.arc(world.player.x/8,world.player.y/8,5,0,Math.PI*2);g.fill();d.append(c);const p=document.createElement('p');p.textContent='Chấm trắng: bạn · Ô vàng: xe · Vòng sáng: vùng an toàn. Trận đấu đang tạm dừng.';d.append(p);};
$('#ranks').onclick=()=>{const d=dialog('THÀNH TÍCH TRÊN MÁY'),rows=readSave().records.filter(r=>r&&typeof r.name==='string'&&Number.isFinite(r.kills)&&Number.isFinite(r.seconds)&&Object.hasOwn(MODES,r.difficulty)).slice(0,20),p=document.createElement('p');p.textContent=rows.length?'Ưu tiên chiến thắng, số hạ gục rồi thời gian sống. Chưa đồng bộ online.':'Chơi hết một trận để ghi thành tích đầu tiên.';d.append(p);const wrap=document.createElement('div');wrap.className='table-scroll';const table=document.createElement('table');for(const row of [['Hạng','Tên','Độ khó','Kết quả','Hạ gục','Giây'],...rows.map((r,i)=>[i+1,r.name,MODES[r.difficulty].name,r.won?'Thắng':'Kết thúc',r.kills,r.seconds])]){const tr=document.createElement('tr');for(const val of row){const td=document.createElement('td');td.textContent=val;tr.append(td);}table.append(tr);}wrap.append(table);d.append(wrap);};
function resize(){const r=canvas.getBoundingClientRect();canvas.width=r.width<600?800:1200;canvas.height=Math.round(canvas.width*r.height/r.width);}window.addEventListener('resize',resize);resize();
async function json(path){const response=await fetch(path,{signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('Không tải được dữ liệu game.');return response.json();}
async function load(){try{[manifest,data,masks]=await Promise.all(['/fortnite-assets/manifest.json','/fortnite-assets/world.json','/fortnite-assets/collision.json'].map(json));const entries=Object.entries(manifest);let index=0,done=0;await Promise.all(Array.from({length:8},async()=>{while(index<entries.length){const [key,meta]=entries[index++];await new Promise((resolve,reject)=>{const img=new Image(),timer=setTimeout(()=>reject(Error('Tải hình quá lâu.')),20000);img.onload=()=>{clearTimeout(timer);sprites.set(key,img);resolve();};img.onerror=()=>{clearTimeout(timer);reject(Error('Không tải được hình '+key));};img.src=meta.src;});done++;$('#loading').textContent='Đang tải hình '+done+' / '+entries.length;}}));world=createGame(data,masks);$('#start').disabled=false;$('#start').textContent='VÀO ĐẢO ↗';$('#loading').textContent='Sẵn sàng · Không cần tải bộ chạy Scratch';hud();requestAnimationFrame(frame);}catch(e){$('#loading').textContent=e.message+' Bấm tải lại để thử lại.';$('#start').disabled=false;$('#start').textContent='TẢI LẠI';$('#start').onclick=()=>location.reload();}}
load();
