import {winningLine,overlaps,brickHit} from './game-rules.js';
const $=s=>document.querySelector(s),dialog=$('#game-modal'),canvas=$('#game-canvas'),ctx=canvas.getContext('2d');
let mode=null,online=false,roomState=null,sendMove=null,raf=0,last=0,elapsed=0,running=false,paused=false,ended=false,sound=false,audio=null,keys=new Set(),particles=[],game={},board=[],turn='X',line=[],lastCell=null,caroStatus='playing',pending=false;
const images={};for(const name of ['runner','space']){const im=new Image();im.src='/background-'+name+'-v2.webp';images[name]=im;}
function beep(freq=440,duration=.1,type='sine',end=freq){if(!sound||!audio||audio.state!=='running')return;const osc=audio.createOscillator(),gain=audio.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(Math.max(end,20),audio.currentTime+duration);gain.gain.setValueAtTime(.0001,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.075,audio.currentTime+.01);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration+.02);}
async function unlockSound(){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();await audio.resume();}catch{sound=false;updateSound();}}
function updateSound(){$('#sound-button').textContent='♫ Âm thanh: '+(sound?'Bật':'Tắt');$('#sound-button').setAttribute('aria-pressed',String(sound));}
$('#sound-button').onclick=async()=>{sound=!sound;updateSound();if(sound){await unlockSound();beep(660,.15);}else audio?.suspend();};
function best(value){let previous=0;try{previous=Number(localStorage.getItem('xa_best_'+mode))||0;if(value>previous){previous=value;localStorage.setItem('xa_best_'+mode,String(value));}}catch{}return previous;}
function status(text){$('#play-status').textContent=text;}
function overlay(title,description,label='Bắt đầu chơi ↗'){$('#game-overlay').classList.remove('hidden');$('#overlay-title').textContent=title;$('#overlay-description').textContent=description;$('#start-game').textContent=label;}
function round(x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function gradient(y,h,top,bottom){const g=ctx.createLinearGradient(0,y,0,y+h);g.addColorStop(0,top);g.addColorStop(1,bottom);return g;}
function burst(x,y,color,n=12){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*220,vy:(Math.random()-.7)*230,life:.3+Math.random()*.4,color});}
function drawParticles(dt){for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=270*dt;ctx.globalAlpha=Math.max(0,Math.min(1,p.life*2));round(p.x,p.y,4,4,1,p.color);}ctx.globalAlpha=1;particles=particles.filter(p=>p.life>0);}
function background(name){const im=images[name];if(im.complete&&im.naturalWidth)ctx.drawImage(im,0,0,960,540);else{ctx.fillStyle=name==='runner'?'#52646c':'#102338';ctx.fillRect(0,0,960,540);}}
function robot(x,feet,t,jumping){ctx.save();ctx.translate(x,feet);ctx.fillStyle='#11192244';ctx.beginPath();ctx.ellipse(0,5,28,6,0,0,Math.PI*2);ctx.fill();const swing=jumping?.4:Math.sin(t*18)*.6;for(const sign of [-1,1]){ctx.save();ctx.translate(sign*10,-19);ctx.rotate(sign*swing);round(-7,0,13,22,5,'#8899a4');round(-7,16,20,10,4,'#dedbd1');ctx.restore();}round(-20,-60,40,43,10,gradient(-60,43,'#fcf0da','#adb8bd'));round(-23,-53,8,23,4,'#cf7f39');round(15,-53,8,23,4,'#cf7f39');round(-26,-89,52,35,12,gradient(-89,35,'#fff7e5','#c1cbd0'));round(-20,-79,42,16,6,'#1b3347');round(1,-74,6,5,2,'#a9d6e2');round(12,-74,6,5,2,'#a9d6e2');round(-9,-51,21,7,2,'#d88438');round(-5,-37,10,10,3,'#314f63');ctx.restore();}
function resetRunner(){game={y:438,vy:0,speed:320,distance:0,coins:0,objects:[],spawn:1.3};}
function jump(){if(!running||paused||mode!=='runner')return;if(game.y>=437){game.vy=-700;beep(230,.14,'triangle',640);burst(150,438,'#c9b897',6);}}
function runner(dt){if(dt){game.distance+=game.speed*dt;game.speed=Math.min(570,320+game.distance/95);game.vy+=1700*dt;game.y=Math.min(438,game.y+game.vy*dt);if(game.y===438)game.vy=0;game.spawn-=dt;if(game.spawn<=0){const h=38+Math.random()*27;game.objects.push({x:1030,y:438-h,w:38+Math.random()*16,h,type:'rock'});game.objects.push({x:1050,y:292,w:24,h:24,type:'coin'});game.spawn=1.65+Math.random()*.7;}
 for(const o of game.objects){o.x-=game.speed*dt;if(overlaps({x:134,y:game.y-79,w:31,h:76},o)){if(o.type==='rock'){endGame('Chuyến đi kết thúc',Math.floor(game.distance/10)+game.coins*25);break;}else{o.x=-100;game.coins++;beep(740,.14,'sine',1100);burst(160,game.y-55,'#f5ce7a');}}}game.objects=game.objects.filter(o=>o.x>-100);}
 background('runner');ctx.fillStyle='#1a2b331c';ctx.fillRect(0,0,960,540);
 // Moving mist, foreground shrubs and stonework give separate depths without scrolling seams.
 ctx.fillStyle='#e5e7d713';for(let i=0;i<5;i++){const x=((i*280-game.distance*.08)%1400+1400)%1400-220;ctx.beginPath();ctx.ellipse(x,270+i%2*35,170,15,0,0,Math.PI*2);ctx.fill();}
 ctx.fillStyle=gradient(437,103,'#9a907e','#343b3d');ctx.fillRect(0,437,960,103);ctx.fillStyle='#d5c9ad';ctx.fillRect(0,435,960,7);ctx.fillStyle='#303739';for(let row=0;row<3;row++){const offset=-(game.distance%(115))+row%2*57;for(let x=offset-115;x<960;x+=115){ctx.fillRect(x,449+row*34,110,2);ctx.fillRect(x,449+row*34,2,30);}}for(let i=0;i<12;i++){const x=((i*111-game.distance*.8)%1332+1332)%1332-80;ctx.fillStyle='#3f5545';ctx.fillRect(x,429,3,8);ctx.fillRect(x+5,432,3,5);}
 for(const o of game.objects){if(o.type==='coin'){ctx.save();ctx.translate(o.x+12,o.y+12);ctx.scale(.75+Math.sin(elapsed*6)*.2,1);ctx.fillStyle='#b57930';ctx.beginPath();ctx.arc(0,0,14,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f1cc72';ctx.beginPath();ctx.arc(-2,-2,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#9a6d2a';ctx.font='bold 14px sans-serif';ctx.fillText('✦',-8,4);ctx.restore();}else{round(o.x,o.y,o.w,o.h,5,gradient(o.y,o.h,'#c0b3a0','#625e56'));round(o.x+5,o.y+5,o.w-12,8,2,'#dcd0b8');ctx.strokeStyle='#635e54';ctx.beginPath();ctx.moveTo(o.x+o.w*.6,o.y+10);ctx.lineTo(o.x+o.w*.4,o.y+o.h*.6);ctx.lineTo(o.x+o.w*.7,o.y+o.h);ctx.stroke();}}
 robot(150,game.y,elapsed,game.y<438);drawParticles(dt);status('Quãng đường '+Math.floor(game.distance/10)+' m · '+game.coins+' xu · Điểm '+(Math.floor(game.distance/10)+game.coins*25));
}
function bricksForLevel(level){const bricks=[];for(let row=0;row<5;row++)for(let col=0;col<10;col++)bricks.push({x:55+col*86,y:65+row*35,w:78,h:26,hp:level>1&&row<2?2:1,row});return bricks;}
function resetBlocks(){game={paddle:480,ball:{x:480,y:471,vx:210,vy:-300,r:8},launched:false,lives:3,score:0,level:1,bricks:bricksForLevel(1),trail:[]};}
function launch(){if(mode==='runner'){jump();return;}if(mode==='blocks'&&running&&!paused&&!game.launched){game.launched=true;beep(330,.12,'triangle',500);}}
function blocks(dt){const b=game.ball;if(dt){const direction=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0);game.paddle=Math.max(65,Math.min(895,game.paddle+direction*640*dt));if(!game.launched){b.x=game.paddle;b.y=470;}else{const steps=Math.max(1,Math.ceil(Math.max(Math.abs(b.vx),Math.abs(b.vy))*dt/6)),step=dt/steps;for(let n=0;n<steps;n++){const oldX=b.x,oldY=b.y;b.x+=b.vx*step;b.y+=b.vy*step;if(b.x<24+b.r){b.x=24+b.r;b.vx=Math.abs(b.vx);beep(230,.04);}if(b.x>936-b.r){b.x=936-b.r;b.vx=-Math.abs(b.vx);beep(230,.04);}if(b.y<24+b.r){b.y=24+b.r;b.vy=Math.abs(b.vy);beep(250,.04);}if(b.vy>0&&b.y+b.r>=482&&oldY+b.r<=482&&Math.abs(b.x-game.paddle)<65+b.r){const hit=Math.max(-1,Math.min(1,(b.x-game.paddle)/65));const speed=Math.min(640,Math.hypot(b.vx,b.vy)+8);b.vx=hit*speed*.83;b.vy=-Math.sqrt(speed*speed-b.vx*b.vx);b.y=473;beep(360,.08,'triangle');burst(b.x,483,'#cbd6df',5);}
 for(const brick of game.bricks){if(!brick.hp||!brickHit(b,brick))continue;brick.hp--;game.score+=brick.hp?5:10;if(oldY+b.r<=brick.y||oldY-b.r>=brick.y+brick.h)b.vy=-b.vy;else b.vx=-b.vx;b.x=oldX;b.y=oldY;burst(b.x,b.y,brick.row%2?'#d7995c':'#83a4c8');beep(450+brick.row*85,.08,'sine',650);break;}
 if(b.y>550){game.lives--;beep(180,.3,'triangle',65);if(!game.lives){endGame('Hết lượt chơi',game.score);break;}game.launched=false;b.x=game.paddle;b.y=470;b.vx=210;b.vy=-300;game.trail=[];break;}
 if(game.bricks.every(x=>x.hp===0)){if(game.level===3){endGame('Chinh phục quỹ đạo!',game.score);break;}game.level++;game.bricks=bricksForLevel(game.level);game.launched=false;b.vx=240;b.vy=-340;beep(600,.3,'triangle',1000);break;}
 }}game.trail.push({x:b.x,y:b.y});if(game.trail.length>12)game.trail.shift();}
 background('space');ctx.fillStyle='#050c1833';ctx.fillRect(0,0,960,540);for(const brick of game.bricks){if(!brick.hp)continue;const colors=brick.row%2?['#f2bd85','#995e34']:['#adc0d7','#48688c'];round(brick.x,brick.y+4,brick.w,brick.h,5,'#050a16aa');round(brick.x,brick.y,brick.w,brick.h,5,gradient(brick.y,brick.h,...colors));round(brick.x+4,brick.y+3,brick.w-8,3,1,'#ffffff66');if(brick.hp===2){ctx.fillStyle='#e8edf4';ctx.fillRect(brick.x+brick.w/2-6,brick.y+12,12,3);}}
 game.trail.forEach((p,i)=>{ctx.globalAlpha=i/game.trail.length*.3;ctx.fillStyle='#cce5ef';ctx.beginPath();ctx.arc(p.x,p.y,b.r*i/game.trail.length,0,Math.PI*2);ctx.fill();});ctx.globalAlpha=1;round(game.paddle-65,486,130,16,7,'#030813aa');round(game.paddle-65,482,130,14,6,gradient(482,14,'#e3edf1','#687d91'));round(game.paddle-20,482,40,14,4,gradient(482,14,'#f2bb7d','#a26332'));ctx.fillStyle='#fbf1d9';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(b.x-2,b.y-2,3,0,Math.PI*2);ctx.fill();drawParticles(dt);status('Điểm '+game.score+' · '+game.lives+' mạng · Màn '+game.level+'/3'+(!game.launched?' · Chạm để thả bóng':''));
}
function endGame(title,score){running=false;ended=true;$('#play-best').textContent='Kỷ lục: '+best(score);overlay(title,'Bạn đạt '+score+' điểm. Thử lại để phá kỷ lục nhé!','Chơi lại ↗');beep(200,.4,'triangle',65);}
function frame(time){const dt=last?Math.min((time-last)/1000,.035):0;last=time;if(!dialog.open||!mode||mode==='caro')return;const active=running&&!paused;elapsed+=active?dt:0;if(mode==='runner')runner(active?dt:0);else blocks(active?dt:0);raf=requestAnimationFrame(frame);}
function start(){unlockSound();resetArcade();running=true;paused=false;ended=false;$('#game-overlay').classList.add('hidden');$('#pause-button').textContent='Tạm dừng';canvas.focus();beep(440,.12,'triangle',660);}
function resetArcade(){particles=[];elapsed=0;mode==='runner'?resetRunner():resetBlocks();}
function pause(){if(mode==='caro'||ended||!running)return;paused=!paused;keys.clear();$('#pause-button').textContent=paused?'Tiếp tục':'Tạm dừng';if(paused){overlay('Tạm nghỉ một chút','Sẵn sàng rồi thì tiếp tục nhé.','Tiếp tục ↗');audio?.suspend();}else{$('#game-overlay').classList.add('hidden');unlockSound();canvas.focus();}}
function renderCaro(){const m=online?roomState?.room?.match:null;if(online){if(!m){status('Chưa có ván đang chơi. Trở về phòng để bắt đầu.');board=Array(225).fill(null);caroStatus='waiting';line=[];}else{board=m.board;turn=m.turn;line=m.line;lastCell=m.last;caroStatus=m.status;}}
 const myRole=roomState?.me?.role;status(caroStatus==='won'?'Quân '+(m?.winner||board[lastCell])+' thắng!':caroStatus==='draw'?'Ván cờ hòa.':caroStatus==='aborted'?'Ván dừng vì một người chơi đã rời phòng.':caroStatus==='waiting'?'Về phòng, hai người sẵn sàng rồi chủ phòng bắt đầu.':'Lượt quân '+turn+(online?' · Bạn: '+(myRole||'Khán giả'):' · Hai người trên cùng máy'));
 $('#play-best').textContent=online?'TRỰC TUYẾN':'CÙNG MÁY';const can=caroStatus==='playing'&&(!online||myRole===turn)&&!pending;
 $('#caro-board').innerHTML=board.map((v,i)=>'<button class="cell '+(v==='O'?'o ':'')+(lastCell===i?'last ':'')+(line.includes(i)?'won':'')+'" data-cell="'+i+'" aria-label="Hàng '+(Math.floor(i/15)+1)+', cột '+(i%15+1)+': '+(v||'trống')+'" '+(!can||v?'disabled':'')+'>'+ (v||'')+'</button>').join('');$('#restart-game').classList.toggle('hidden',online);
}
$('#caro-board').onclick=async e=>{const cell=e.target.closest('[data-cell]');if(!cell||cell.disabled)return;const i=Number(cell.dataset.cell);if(online){pending=true;renderCaro();try{await sendMove(i);beep(420,.1,'triangle');}catch(err){status(err.message);}finally{pending=false;renderCaro();}}else{if(board[i]||caroStatus!=='playing')return;board[i]=turn;lastCell=i;line=winningLine(board,i);if(line.length){caroStatus='won';beep(520,.3,'triangle',900);}else if(board.every(Boolean))caroStatus='draw';else turn=turn==='X'?'O':'X';beep(turn==='X'?420:520,.09,'triangle');renderCaro();const next=$('#caro-board').querySelector('[data-cell="'+Math.min(224,i+1)+'"]:not(:disabled)');next?.focus();}};
export function updateOnline(state){roomState=state;if(mode==='caro'&&online&&dialog.open)renderCaro();}
export function openGame(id,options={}){mode=id;online=Boolean(options.online);sendMove=options.sendMove;roomState=options.state||roomState;running=false;paused=false;ended=false;keys.clear();cancelAnimationFrame(raf);last=0;$('#play-title').textContent={runner:'Robot phiêu lưu',blocks:'Phá gạch quỹ đạo',caro:'Cờ caro'}[id];$('#canvas-wrap').classList.toggle('hidden',id==='caro');$('#caro-wrap').classList.toggle('hidden',id!=='caro');$('#pause-button').classList.toggle('hidden',id==='caro');$('#touch-action').classList.toggle('hidden',id==='caro');$('#restart-game').classList.toggle('hidden',online);$('#pause-button').textContent='Tạm dừng';$('#play-help').textContent=id==='runner'?'Space / ↑ / chạm màn chơi để nhảy. Vượt đá, lấy xu. P để tạm dừng.':id==='blocks'?'Di chuột, kéo tay hoặc ← → để điều khiển. Chạm / Space thả bóng. P để tạm dừng.':'Nối ít nhất 5 quân liên tiếp để thắng; không xét chặn hai đầu. Bàn 15 × 15, có thể cuộn ngang trên điện thoại.';$('#touch-action').textContent=id==='runner'?'Nhảy ↑':'Thả bóng ↗';if(!dialog.open)dialog.showModal();unlockSound();if(id==='caro'){board=Array(225).fill(null);turn='X';line=[];lastCell=null;caroStatus='playing';renderCaro();}else{resetArcade();$('#play-best').textContent='Kỷ lục: '+best(0);overlay(id==='runner'?'Băng qua thành cổ':'Chinh phục quỹ đạo',id==='runner'?'Nhảy qua chướng ngại vật, thu thập xu. Tốc độ sẽ tăng dần.':'Điều khiển thanh đỡ, phá hết gạch trong 3 màn. Bạn có 3 mạng.');raf=requestAnimationFrame(frame);}}
function close(){dialog.close();cancelAnimationFrame(raf);running=false;mode=null;keys.clear();audio?.suspend();}
$('#close-game').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});dialog.addEventListener('close',()=>{cancelAnimationFrame(raf);running=false;mode=null;keys.clear();audio?.suspend();});$('#start-game').onclick=()=>paused?pause():start();$('#pause-button').onclick=pause;$('#restart-game').onclick=()=>{if(mode==='caro'){board=Array(225).fill(null);turn='X';line=[];lastCell=null;caroStatus='playing';renderCaro();}else start();};$('#touch-action').onclick=launch;
canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.focus();canvas.setPointerCapture(e.pointerId);if(mode==='blocks'){const r=canvas.getBoundingClientRect();game.paddle=Math.max(65,Math.min(895,(e.clientX-r.left)*960/r.width));}launch();});canvas.addEventListener('pointermove',e=>{if(mode!=='blocks'||paused)return;const r=canvas.getBoundingClientRect();game.paddle=Math.max(65,Math.min(895,(e.clientX-r.left)*960/r.width));});
document.addEventListener('keydown',e=>{if(!dialog.open||mode==='caro'||e.target.closest('button'))return;if([' ','ArrowUp','ArrowLeft','ArrowRight','a','d','p','P'].includes(e.key)){e.preventDefault();keys.add(e.key);if(e.repeat)return;if(e.key==='p'||e.key==='P')pause();else if(e.key===' '||e.key==='ArrowUp')launch();}});document.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>{keys.clear();if(running&&!paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();if(running&&!paused)pause();audio?.suspend();}});
