import {roomAPI} from './shooter-client.js';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),names={battle:'Xanh Battle',fortnite:'Fortnite Z'},levels={easy:'Tập sự',normal:'Thường',hard:'Thử thách'};let current=null,busy=false;
if(params.get('game') in names)$('game').value=params.get('game');if(params.get('code'))$('code').value=params.get('code').slice(0,6);
function link(room){return '/'+(room.game==='battle'?'battle':'fortnite-z')+'?online=1';}
function render(value){current=value.room;$('entry').hidden=!!current;$('lobby').hidden=!current;if(!current){$('list').replaceChildren();for(const r of value.rooms){const b=document.createElement('button');b.textContent=names[r.game]+' · '+r.code+' · '+r.count+'/25 · '+(r.mode==='squad'?'Đội 4':'Solo');b.onclick=()=>run('join',{code:r.code,name:$('name').value});$('list').append(b);}return;}
const r=current;$('title').textContent=names[r.game]+' · '+r.code;$('summary').textContent=r.humans+' người thật + '+r.bots+' bot = 25 · '+levels[r.difficulty]+(r.locked?' · ĐÃ KHÓA CẤU HÌNH':' · Đang chờ')+(r.mode==='squad'?' · 6 đội 4 vị trí + đội cuối 1 vị trí':'');$('host-settings').hidden=!r.host;$('room-mode').value=r.mode;$('room-difficulty').value=r.difficulty;for(const id of ['room-mode','room-difficulty','save'])$(id).disabled=r.locked;$('ready').disabled=r.locked;$('ready').textContent=r.members.find(m=>m.me)?.ready?'Hủy sẵn sàng':'Sẵn sàng';$('start').hidden=!r.host;$('start').disabled=r.locked||r.members.some(m=>!m.host&&!m.ready);$('return').hidden=!r.locked;$('return').href=link(r);$('teams').replaceChildren();
for(let t=0;t<r.teamCapacities.length;t++){const div=document.createElement('div');div.className='team';const h=document.createElement('h3');h.textContent=r.mode==='squad'?'Đội '+(t+1):'Vị trí '+(t+1);div.append(h);const members=r.members.filter(m=>m.team===t);for(const m of members){const p=document.createElement('p');p.textContent=m.name+(m.me?' · BẠN':'')+(m.host?' ★':'')+(m.ready?' ✓':' · Chưa sẵn sàng');div.append(p);}for(let i=members.length;i<r.teamCapacities[t];i++){const p=document.createElement('p');p.className='bot';p.textContent='🤖 Bot sẽ vào vị trí này';div.append(p);}if(r.mode==='squad'){const b=document.createElement('button');b.className='secondary';b.textContent='Vào đội '+(t+1);b.disabled=r.locked||members.length>=r.teamCapacities[t]||members.some(m=>m.me);b.onclick=()=>run('team',{team:t});div.append(b);}$('teams').append(div);}
if(r.locked&&!params.has('stay'))location.href=link(r);}
async function run(op,d={}){if(busy)return;busy=true;$('status').textContent='Đang xử lý…';try{render(await roomAPI(op,d));$('status').textContent='';}catch(e){$('status').textContent=e.message;}finally{busy=false;}}
$('create').onclick=()=>run('create',{game:$('game').value,mode:$('mode').value,difficulty:$('difficulty').value,name:$('name').value});$('join').onclick=()=>run('join',{code:$('code').value,name:$('name').value});$('leave').onclick=()=>run('leave');$('save').onclick=()=>run('settings',{mode:$('room-mode').value,difficulty:$('room-difficulty').value});$('ready').onclick=()=>run('ready');$('start').onclick=()=>run('start');$('copy').onclick=async()=>{const url=location.origin+'/rooms?code='+current.code;try{await navigator.clipboard.writeText(url);$('status').textContent='Đã sao chép link mời.';}catch{$('status').textContent=url;}};
try{render(await roomAPI('state'));const es=new EventSource('/api/shooter/events');es.addEventListener('room',e=>render(JSON.parse(e.data)));es.onerror=()=>{$('status').textContent='Đang nối lại phòng…';};setInterval(()=>roomAPI('state').then(render).catch(e=>{$('status').textContent=e.message;}),20000);}catch(e){$('status').textContent=e.message;}
