import {createNetworkMotion} from './network-motion.js';
import {RESOURCE_PROTOCOL,detectResourceCapabilities,createDutyCycleScheduler,runResourceTask} from './resource-sharing.js';
const motion=createNetworkMotion();
const networkStats={rtt:null,packetAt:null,jitter:0};
export function getNetworkStats(now=performance.now()){const age=networkStats.packetAt===null?null:now-networkStats.packetAt;return {rtt:age!==null&&age<2500?networkStats.rtt:null,age,jitter:networkStats.jitter};}
export function drawOnline(world,time,render){if(online)motion.draw(world,time,render);else render();}
export const online=new URLSearchParams(location.search).get('online')==='1';
export async function roomAPI(op,data){const r=await fetch('/api/shooter/'+op,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const value=await r.json();if(!r.ok)throw Error(value.error||'Lỗi kết nối');return value;}
export function connectMatch({game,receive,input,buttons,keyAction,notice}){
 if(!online)return;
 const strip=document.createElement('aside');strip.className='online-strip';strip.setAttribute('aria-live','polite');const label=document.createElement('span'),back=document.createElement('a');back.href='/rooms?stay=1&game='+game;back.textContent='Về phòng';strip.append(label,back);document.querySelector('main').prepend(strip);label.textContent='Đang kết nối phòng…';
  let snapshot=null,actions=[],seq=0,busy=false,lastPacket=0,room=null,stopped=false,resourceHost=false,capabilitySentFor='',lastResourcePing=0,resourcePings=0,resourceMissed=0,shareCpuMs=0,shareBytes=0,shareTasks=0;
  const capabilities=detectResourceCapabilities(),resourceScheduler=createDutyCycleScheduler();
  async function heartbeat(){if(!resourceHost||!snapshot||snapshot.status!=='playing')return;try{const response=await roomAPI('resource-heartbeat',{matchId:snapshot.matchId,rtt:lastResourcePing?performance.now()-lastResourcePing:0,packetLoss:resourcePings?resourceMissed/resourcePings:0,usage:{cpuMs:shareCpuMs,bytes:shareBytes,tasks:shareTasks,cores:capabilities.cores,memoryGb:capabilities.memoryGb}});shareCpuMs=0;shareBytes=0;shareTasks=0;if(response.host!==resourceHost)resourceHost=response.host===true;}catch{}}
 function queue(action){if(snapshot?.status==='playing'&&snapshot.actors[snapshot.playerId].alive&&actions.length<6)actions.push(action);}
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const action=buttons(b);if(action){e.preventDefault();e.stopImmediatePropagation();queue(action);}},true);
 document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select')||document.querySelector('dialog[open]'))return;const action=keyAction(e.code);if(action){e.preventDefault();e.stopImmediatePropagation();if(!e.repeat)queue(action);}},true);
 window.addEventListener('blur',()=>{actions=[];});
 const events=new EventSource('/api/shooter/events');events.addEventListener('room',e=>{const value=JSON.parse(e.data);room=value.room;if(!room||room.game!==game){stopped=true;label.textContent='Phòng đã đóng hoặc không đúng game. Bấm Về phòng.';return;}if(!room.locked&&room.status==='waiting')location.href='/rooms?game='+game;});
  events.addEventListener('resource-ping',e=>{const ping=JSON.parse(e.data);if(!resourceHost)return;const gap=lastResourcePing&&ping.seq>lastResourcePing+1?ping.seq-lastResourcePing-1:0;resourceMissed+=gap;resourcePings+=Math.max(1,ping.seq-(lastResourcePing||ping.seq-1));lastResourcePing=ping.seq;});
  events.addEventListener('resource-task',e=>{if(!resourceHost)return;const task=JSON.parse(e.data);if(task.protocol!==RESOURCE_PROTOCOL)return;shareBytes+=e.data.length;resourceScheduler.enqueue(()=>{const t0=performance.now();try{return runResourceTask(task,{capabilities});}finally{shareCpuMs+=performance.now()-t0;shareTasks++;}}).then(result=>{shareBytes+=JSON.stringify(result||{}).length;return result;}).then(result=>roomAPI('resource-result',{matchId:task.matchId||snapshot?.matchId,taskId:task.taskId,result})).catch(()=>{});});
  events.addEventListener('match',e=>{const next=JSON.parse(e.data);if(!next||stopped)return;snapshot=next;seq=Math.max(seq,next.inputSeq||0);const receivedAt=performance.now();if(lastPacket)networkStats.jitter=networkStats.jitter*.8+Math.abs(receivedAt-lastPacket-100)*.2;lastPacket=receivedAt;networkStats.packetAt=lastPacket;const p=next.actors[next.playerId];const team=next.actors.filter(a=>a.team===p.team);resourceHost=next.resource?.host===true;if(capabilitySentFor!==next.matchId){capabilitySentFor=next.matchId;roomAPI('resource-capability',{matchId:next.matchId,capabilities}).catch(()=>{});}label.textContent='Phòng '+(room?.code||'')+' · '+(next.teamMode==='squad'?'Đội '+(p.team+1)+' · '+team.map(a=>a.name+(a.alive?' ♥':' ✕')).join(' / '):'Solo')+' · '+(p.alive?(next.status==='playing'?'Độ khó đã khóa':next.status==='won'?'CHIẾN THẮNG':'KẾT THÚC'):'Đã bị hạ · Chờ kết quả đội');motion.accept(next,lastPacket);receive(next);});
 events.onerror=()=>{label.textContent='Mất kết nối — đang nối lại. Trận đấu vẫn tiếp tục.';};
 const timer=setInterval(async()=>{if(stopped||busy||!snapshot||snapshot.status!=='playing')return;if(performance.now()-lastPacket>2500){label.textContent='Đang chờ máy chủ…';return;}busy=true;const sentAt=performance.now();const batch=actions.splice(0),sample=document.hidden?{}:input();try{await roomAPI('input',{...sample,actions:document.hidden?[]:batch,seq:++seq,matchId:snapshot.matchId});networkStats.rtt=performance.now()-sentAt;}catch(e){label.textContent=e.message;}finally{busy=false;}},50);
  const resourceTimer=setInterval(heartbeat,1000);
  window.addEventListener('pagehide',()=>{clearInterval(timer);clearInterval(resourceTimer);events.close();},{once:true});
}

