import {randomBytes,randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import * as B from './battle-engine.js';
import * as F from './fortnite-engine.js';
import {RESOURCE_PROTOCOL,sanitizeCapabilities} from './resource-sharing.js';
const data=JSON.parse(readFileSync(new URL('./fortnite-assets/world.json',import.meta.url))),masks=JSON.parse(readFileSync(new URL('./fortnite-assets/collision.json',import.meta.url)));
const validGame=g=>['battle','fortnite'].includes(g),validMode=m=>['solo','squad'].includes(m),validDifficulty=d=>['easy','normal','hard'].includes(d);
export class RoomError extends Error{constructor(status,message){super(message);this.status=status;}}
const fail=(status,message)=>{throw new RoomError(status,message);};
export function createShooterRooms({now=Date.now,maxMatches=4}={}){
 const rooms=new Map(),clients=new Map();let adminBoostActive=process.env.ADMIN_BOOST_ACTIVE==='1';
 const client=s=>{let c=clients.get(s.id);if(!c){c={session:s,room:null,streams:new Set(),last:now(),rate:0,at:now(),inputAt:0,resource:{capabilities:null,host:false,lastHeartbeat:0,lastPing:0,rtt:Infinity,packetLoss:1,badSince:0}};clients.set(s.id,c);}c.last=now();return c;};
 const getRoom=c=>{const r=rooms.get(c.room);if(!r)fail(404,'Bạn chưa vào phòng.');return r;};
 const waiting=r=>{if(r.match?.status==='playing')fail(409,'Trận đã bắt đầu: cấu hình và đội đã khóa.');};
 const host=(r,c)=>{if(r.host!==c.session.id)fail(403,'Chỉ chủ phòng được thay đổi cấu hình hoặc bắt đầu.');};
 const cap=(r,t)=>r.mode==='solo'?1:t===6?1:4;
 const teamCount=r=>r.mode==='solo'?25:7;
 const available=(r,t)=>[...r.members.values()].filter(m=>m.team===t).length<cap(r,t);
 const autoTeam=r=>{for(let t=0;t<teamCount(r);t++)if(available(r,t))return t;fail(409,'Phòng đã đủ 25 người.');};
 const view=(r,c)=>({code:r.code,game:r.game,mode:r.mode,difficulty:r.difficulty,host:r.host===c.session.id,locked:r.match?.status==='playing',matchId:r.match?.id||null,status:r.match?.status||'waiting',winner:r.match?.winner??null,humans:r.members.size,bots:25-r.members.size,members:[...r.members].map(([id,m])=>({name:m.name,team:m.team,ready:m.ready,host:id===r.host,me:id===c.session.id})),teamCapacities:Array.from({length:teamCount(r)},(_,i)=>cap(r,i))});
 function state(c){const r=rooms.get(c.room);return {room:r?view(r,c):null,rooms:[...rooms.values()].filter(r=>!r.match||r.match.status!=='playing').map(r=>({code:r.code,game:r.game,mode:r.mode,count:r.members.size,difficulty:r.difficulty}))};}
 function emit(c,event,payload){const text='event: '+event+'\ndata: '+JSON.stringify(payload)+'\n\n';for(const res of c.streams){if(res.destroyed){c.streams.delete(res);continue;}if(res.writableLength>512000){res.destroy();c.streams.delete(res);continue;}res.write(text);}}
 function notify(){for(const c of clients.values())if(c.streams.size)emit(c,'room',state(c));}
 function resourceState(r,c){return {enabled:adminBoostActive,host:c?.resource.host===true,hosts:[...r.match?.resource?.hosts||[]].map(id=>({id,healthy:clients.get(id)?.resource.host===true}))};}
 function clearResourceOffload(r){const resource=r.match?.resource;if(!resource)return;for(const task of resource.pending.values()){for(const id of task.botIds||[])r.match.world.resourceOffload.assignedBots.delete(id);for(const id of task.bulletIds||[])r.match.world.resourceOffload.assignedBullets.delete(id);}resource.pending.clear();resource.hosts.clear();r.match.world.resourceOffload.enabled=false;r.match.world.resourceOffload.assignedBots.clear();r.match.world.resourceOffload.assignedBullets.clear();r.match.world.resourceOffload.paths.clear();r.match.world.resourceOffload.bulletResults.clear();}
 function revokeResourceHost(c,reason){if(!c.resource.host)return;c.resource.host=false;c.resource.revokeReason=reason;const r=rooms.get(c.room),resource=r?.match?.resource;if(resource){for(const [id,task]of resource.pending){if(task.clientId!==c.session.id)continue;for(const botId of task.botIds||[])r.match.world.resourceOffload.assignedBots.delete(botId);for(const bulletId of task.bulletIds||[])r.match.world.resourceOffload.assignedBullets.delete(bulletId);resource.pending.delete(id);}if(resource.hosts.has(c.session.id)){resource.hosts.delete(c.session.id);if(!resource.hosts.size)clearResourceOffload(r);}}}
 function updateResourceHealth(c){if(!c.resource.host)return;const r=rooms.get(c.room),m=r?.match;if(!m)return revokeResourceHost(c,'match-ended');const badLatency=c.resource.rtt>150,badLoss=c.resource.packetLoss>.05;if(badLatency){revokeResourceHost(c,'latency');return;}if(badLoss){c.resource.badSince??=now();if(now()-c.resource.badSince>=3000){revokeResourceHost(c,'packet-loss');return;}}else c.resource.badSince=0;if(now()-c.resource.lastHeartbeat>3200)revokeResourceHost(c,'heartbeat-timeout');}
 function maybeAssignResourceHost(c){if(!adminBoostActive||!c.resource.capabilities?.eligible||c.resource.host)return;const r=rooms.get(c.room),m=r?.match;if(!m||m.status!=='playing'||c.streams.size===0)return;if(m.resource.hosts.size>=2)return;c.resource.host=true;c.resource.lastHeartbeat=now();c.resource.rtt=0;c.resource.packetLoss=0;m.resource.hosts.add(c.session.id);m.world.resourceOffload.enabled=true;}
 function resourceTask(r,kind){
  const m=r.match,w=m?.world;if(!m||m.status!=='playing'||!m.resource?.hosts.size)return null;
  const ids=[...m.resource.hosts];const host=clients.get(ids[m.resource.cursor++%ids.length]);if(!host?.resource.host||[...m.resource.pending.values()].some(task=>task.clientId===host.session.id))return null;
  if(kind==='bot-pathfinding'){const candidates=w.actors.filter(a=>a.bot&&a.alive&&!a.air&&(!a.resourcePathRequested||a.pathTime<=0)).slice(0,10);if(!candidates.length)return null;const task=r.game==='battle'?B.createBotPathTask(w,candidates.map(a=>a.id)):F.createBotPathTask(w,candidates.map(a=>a.id));task.protocol=RESOURCE_PROTOCOL;task.matchId=m.id;task.taskId=++m.resource.nextTaskId;task.botIds=candidates.map(a=>a.id);for(const id of task.botIds)w.resourceOffload.assignedBots.add(id);m.resource.pending.set(task.taskId,{...task,clientId:host.session.id,created:now()});return {client:host,task};}
  const bullets=w.bullets.filter(b=>b.life>0&&!w.resourceOffload.assignedBullets.has(b.id)).slice(0,120);if(!bullets.length)return null;const task={protocol:RESOURCE_PROTOCOL,kind:'bullet-collision',matchId:m.id,taskId:++m.resource.nextTaskId,bullets:bullets.map(b=>({id:b.id,x:b.x,y:b.y,vx:b.vx,vy:b.vy,dt:.05,owner:b.owner,ownerTeam:w.actors[b.owner]?.team})),actors:w.actors.map(a=>({id:a.id,x:a.x,y:a.y,r:a.r||15,alive:a.alive,air:a.air||a.air>0,team:a.team})),bounds:r.game==='battle'?{width:B.SIZE,height:B.SIZE}:{width:F.WIDTH,height:F.HEIGHT}};task.bulletIds=bullets.map(b=>b.id);for(const id of task.bulletIds)w.resourceOffload.assignedBullets.add(id);m.resource.pending.set(task.taskId,{...task,clientId:host.session.id,created:now()});return {client:host,task};
 }
 function dispatchResources(){for(const r of rooms.values()){const m=r.match;if(!m||!m.resource?.hosts.size||!adminBoostActive)continue;for(const kind of ['bot-pathfinding','bullet-collision']){const work=resourceTask(r,kind);if(work)emit(work.client,'resource-task',work.task);}}}
 function leave(c){revokeResourceHost(c,'disconnect');const r=rooms.get(c.room);if(r){const member=r.members.get(c.session.id);if(member&&r.match?.status==='playing'){const a=r.match.world.actors[member.actor];a.bot=true;a.name=member.name+' · bot';delete r.match.controls[a.id];}r.members.delete(c.session.id);if(!r.members.size)rooms.delete(r.code);else if(r.host===c.session.id)r.host=r.members.keys().next().value;}c.room=null;}
 function start(r){const world=r.game==='battle'?B.createWorld('vanguard',Math.random,r.difficulty):F.createGame(data,masks,{difficulty:r.difficulty});world.network=true;world.phase='drop';world.inputs={};for(const a of world.actors)a.bot=true;
 const slots=Array.from({length:25},(_,id)=>({id,team:r.mode==='solo'?id:Math.floor(id/4)}));
 for(const [sid,m] of r.members){const slot=slots.find(s=>s.team===m.team&&!s.used);slot.used=true;m.actor=slot.id;m.seq=-1;const a=world.actors[slot.id];a.bot=false;a.name=m.name;a.damage=1;a.damageScale=1;a.speed=145;a.guard=20;}
 for(const a of world.actors){if(a.bot){a.damage=F.MODES[r.difficulty].damage;a.damageScale=B.DIFFICULTIES[r.difficulty].damage;}a.team=slots[a.id].team;a.inPlane=true;a.dropAt=4+(a.team*2.37)%15;a.name??='Bot '+(a.id+1);if(r.game==='battle'){a.x=800;a.y=B.SIZE/2;}else{a.x=520;a.y=F.HEIGHT/2;}}
  world.resourceOffload={enabled:false,assignedBots:new Set(),assignedBullets:new Set(),paths:new Map(),bulletResults:new Map()};
  r.match={id:randomUUID(),world,status:'playing',winner:null,controls:{},started:now(),finished:null,resource:{hosts:new Set(),pending:new Map(),nextTaskId:0,cursor:0}};
 }
 function action(r,a,name){const w=r.match.world;if(!a.alive)return;if(name==='jump'){a.inPlane=false;return;}if(a.inPlane)return;const original=w.player;w.player=a;
 try{if(r.game==='battle'){if(name==='pickup')B.pickup(w,a,B.nearestLoot(w,a));else if(name==='heal')B.heal(a);else if(name==='reload')B.reload(a);else if(name==='glue')B.deployGlue(w,a);else if(name==='vehicle')B.toggleVehicle(w);else if(['dash','shield','nova'].includes(name))B.ability(w,name);else if(/^slot[01]$/.test(name))B.switchWeapon(a,Number(name.slice(4)));}
 else{if(name==='pickup')F.collect(w,a);else if(name==='heal')F.heal(a);else if(name==='reload')F.reload(a);else if(name==='build')F.build(w);else if(name==='vehicle')F.enterCar(w);else if(name==='grenade')F.throwGrenade(w);else if(name==='axe'){a.tool=!a.tool;a.reload=0;}else if(/^slot[0-5]$/.test(name))F.swap(w,Number(name.slice(4)));}}
 finally{w.player=original;}}
 function snapshot(r,c){const m=r.match,member=r.members.get(c.session.id);if(!m||!member)return null;const w=m.world,p=w.actors[member.actor];if(!p)return null;const nearby=o=>Math.abs(o.x-p.x)<1700&&Math.abs(o.y-p.y)<1400;const actorFields=r.game==='battle'?['id','name','team','x','y','r','hp','maxHp','speed','angle','vx','vy','cool','reload','shield','dash','shieldCd','novaCd','kills','level','alive','color','bot','active','slots','bag','armor','vehicle','guard','glueCd','healing','air','altitude','inPlane']:['id','name','team','x','y','hp','maxHp','armor','angle','vx','vy','alive','air','slots','slot','ammo','wood','med','grenades','vehicle','cool','reload','heal','kills','skin','damage','guard','tool','buildCd','bot','inPlane'];
 const actors=w.actors.map(a=>Object.fromEntries(actorFields.map(k=>[k,a[k]])));const out={matchId:m.id,inputSeq:member.seq,playerId:p.id,time:w.time,flight:w.flight,difficulty:r.difficulty,actors,zone:w.zone,phase:p.inPlane?'flight':p.air?'drop':'combat',status:m.status==='playing'?'playing':m.winner===p.team?'won':'lost',teamMode:r.mode,bullets:w.bullets.filter(nearby),effects:w.effects.filter(nearby),loot:w.loot.filter(nearby),events:w.events,resource:resourceState(r,c)};
 if(r.game==='battle')Object.assign(out,{covers:w.covers,vehicles:w.vehicles,classId:'vanguard',diff:w.diff});else Object.assign(out,{walls:w.walls,cars:w.cars,trees:w.trees.filter(nearby),chests:w.chests,pads:w.pads});return out;
 }
 function tick(dt=.05){for(const r of rooms.values()){const m=r.match;if(!m||m.status!=='playing')continue;const w=m.world;w.flight=Math.min(r.game==='battle'?25:22,w.flight+dt);for(const a of w.actors){if(!a.inPlane)continue;const duration=r.game==='battle'?25:22;a.x=(r.game==='battle'?800:520)+w.flight*(r.game==='battle'?B.SIZE-1600:F.WIDTH-1040)/duration;a.y=r.game==='battle'?B.SIZE/2:F.HEIGHT/2;if(w.flight>=duration||a.bot&&w.flight>=a.dropAt)a.inPlane=false;}
 w.inputs={};for(const [id,control]of Object.entries(m.controls)){if(now()-control.at>600)continue;w.inputs[id]=control.input;for(const cmd of control.actions.splice(0))action(r,w.actors[id],cmd);}
 if(r.game==='battle')B.stepWorld(w,dt);else F.step(w,dt);
 const teams=new Set(w.actors.filter(a=>a.alive).map(a=>a.team));if(teams.size<=1||w.time>1500){m.status='finished';m.winner=teams.size===1?[...teams][0]:null;m.finished=now();for(const v of r.members.values())v.ready=false;notify();}
 }}
  function publish(){for(const c of clients.values()){const r=rooms.get(c.room);if(c.resource.host){updateResourceHealth(c);if(now()-c.resource.lastPing>=1000){c.resource.lastPing=now();c.resource.pingSeq=(c.resource.pingSeq||0)+1;emit(c,'resource-ping',{seq:c.resource.pingSeq,matchId:r?.match?.id||null,serverAt:now()});}}if(r?.match&&c.streams.size)emit(c,'match',snapshot(r,c));}dispatchResources();}
  function cleanup(){for(const c of clients.values()){if(now()-c.last>120000){leave(c);for(const res of c.streams)res.end();clients.delete(c.session.id);}else{updateResourceHealth(c);for(const res of c.streams)res.write(': heartbeat\n\n');} }notify();}
  function command(s,op,d={}){const c=client(s);if(op==='state')return state(c);if(op==='admin-boost'){if(!process.env.SHOOTER_ADMIN_TOKEN||d.token!==process.env.SHOOTER_ADMIN_TOKEN)fail(403,'Lệnh quản trị không hợp lệ.');adminBoostActive=d.enabled===true;if(!adminBoostActive)for(const other of clients.values())revokeResourceHost(other,'admin-disabled');notify();return {ok:true,adminBoostActive};}if(op==='input'){const r=getRoom(c),m=r.match,member=r.members.get(s.id);if(!m||m.status!=='playing'||d.matchId!==m.id)fail(409,'Trận không còn hoạt động.');if(!Number.isSafeInteger(d.seq)||d.seq<=member.seq)return {ok:true};if(now()-c.inputAt<30)fail(429,'Gửi điều khiển quá nhanh.');c.inputAt=now();member.seq=d.seq;const old=m.controls[member.actor];const finite=n=>typeof n==='number'&&Number.isFinite(n);m.controls[member.actor]={at:now(),input:{x:finite(d.x)?Math.max(-1,Math.min(1,d.x)):0,y:finite(d.y)?Math.max(-1,Math.min(1,d.y)):0,angle:finite(d.angle)?d.angle%(Math.PI*2):0,fire:d.fire===true,reload:d.reload===true},actions:[...(old?.actions||[]),...(Array.isArray(d.actions)?d.actions.filter(a=>typeof a==='string').slice(0,6):[])].slice(0,12)};return {ok:true};}
  if(op==='resource-capability'){const r=getRoom(c),m=r.match;if(!m||m.status!=='playing'||d.matchId!==m.id)fail(409,'Trận không còn hoạt động.');c.resource.capabilities=sanitizeCapabilities(d.capabilities);maybeAssignResourceHost(c);return {ok:true,protocol:RESOURCE_PROTOCOL,eligible:c.resource.capabilities?.eligible===true,host:c.resource.host,adminBoostActive};}
  if(op==='resource-heartbeat'){const r=getRoom(c),m=r.match;if(!m||m.status!=='playing'||d.matchId!==m.id)fail(409,'Trận không còn hoạt động.');const rtt=Number(d.rtt),loss=Number(d.packetLoss);c.resource.lastHeartbeat=now();c.resource.rtt=Number.isFinite(rtt)?Math.max(0,Math.min(5000,rtt)):Infinity;c.resource.packetLoss=Number.isFinite(loss)?Math.max(0,Math.min(1,loss)):1;maybeAssignResourceHost(c);updateResourceHealth(c);return {ok:true,host:c.resource.host,serverAt:now()};}
  if(op==='resource-result'){const r=getRoom(c),m=r.match,task=m?.resource?.pending.get(d.taskId);if(!task||task.clientId!==c.session.id||d.matchId!==m.id||!c.resource.host)fail(409,'Tác vụ tài nguyên không còn hiệu lực.');const result=d.result||{};if(task.kind==='bot-pathfinding'&&Array.isArray(result.paths)){for(const row of result.paths){if(!task.botIds.includes(row.id)||!Array.isArray(row.path))continue;const path=row.path.slice(0,64).filter(p=>p&&Number.isFinite(p.x)&&Number.isFinite(p.y)).map(p=>({x:Math.max(0,Math.min(task.bounds.width,p.x)),y:Math.max(0,Math.min(task.bounds.height,p.y))}));m.world.resourceOffload.paths.set(row.id,path);m.world.resourceOffload.assignedBots.delete(row.id);}}else if(task.kind==='bullet-collision'&&Array.isArray(result.hits)){for(const hit of result.hits){if(!task.bulletIds.includes(hit.bulletId)||!Number.isInteger(hit.actorId))continue;if(!m.world.actors.some(a=>a.id===hit.actorId))continue;m.world.resourceOffload.bulletResults.set(hit.bulletId,{kind:'actor',actorId:hit.actorId});m.world.resourceOffload.assignedBullets.delete(hit.bulletId);}}m.resource.pending.delete(d.taskId);return {ok:true};}
 if(now()-c.at>60000){c.at=now();c.rate=0;}if(++c.rate>90)fail(429,'Thao tác quá nhanh, thử lại sau.');
 if(op==='create'){if(c.room)fail(409,'Hãy rời phòng hiện tại.');if(!validGame(d.game)||!validMode(d.mode)||!validDifficulty(d.difficulty))fail(400,'Cấu hình phòng không hợp lệ.');if(rooms.size>=100)fail(503,'Sảnh đang đầy.');let code;do{code=randomBytes(3).toString('hex').toUpperCase();}while(rooms.has(code));const r={code,game:d.game,mode:d.mode,difficulty:d.difficulty,host:s.id,members:new Map()};rooms.set(code,r);c.room=code;r.members.set(s.id,{name:String(d.name||s.name).trim().slice(0,24)||'Xanh',team:0,ready:true});}
 else if(op==='join'){const r=rooms.get(String(d.code||'').trim().toUpperCase());if(!r)fail(404,'Không tìm thấy phòng.');if(c.room===r.code)return state(c);if(c.room)fail(409,'Hãy rời phòng hiện tại.');waiting(r);if(r.match?.status==='finished')r.match=null;if(r.members.size>=25)fail(409,'Phòng đã đủ 25 người.');const team=autoTeam(r);c.room=r.code;r.members.set(s.id,{name:String(d.name||s.name).trim().slice(0,24)||'Người chơi',team,ready:false});}
 else if(op==='leave')leave(c);
 else{const r=getRoom(c);waiting(r);if(r.match?.status==='finished')r.match=null;const member=r.members.get(s.id);if(op==='settings'){host(r,c);if(!validDifficulty(d.difficulty)||!validMode(d.mode))fail(400,'Cấu hình không hợp lệ.');r.difficulty=d.difficulty;if(r.mode!==d.mode){r.mode=d.mode;let i=0;for(const m of r.members.values())m.team=r.mode==='solo'?i++:Math.floor(i++/4);}for(const [id,m]of r.members)m.ready=id===r.host;}
 else if(op==='team'){if(r.mode!=='squad'||!Number.isInteger(d.team)||d.team<0||d.team>=7)fail(400,'Đội không hợp lệ.');if(member.team!==d.team&&!available(r,d.team))fail(409,'Đội đã đủ người.');member.team=d.team;member.ready=false;}
 else if(op==='ready')member.ready=!member.ready;
 else if(op==='start'){host(r,c);if([...r.members].some(([id,m])=>id!==r.host&&!m.ready))fail(409,'Chờ mọi người sẵn sàng.');if([...rooms.values()].filter(x=>x.match?.status==='playing').length>=maxMatches)fail(503,'Máy chủ đang đủ trận. Thử lại sau.');start(r);}
 else fail(404,'Thao tác không tồn tại.');}
 notify();return state(c);
 }
  function subscribe(s,res){const c=client(s);if(c.streams.size>=3)fail(429,'Quá nhiều cửa sổ phòng.');res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive','X-Accel-Buffering':'no'});c.streams.add(res);emit(c,'room',state(c));const r=rooms.get(c.room);if(r?.match)emit(c,'match',snapshot(r,c));res.on('close',()=>{c.streams.delete(res);if(!c.streams.size)revokeResourceHost(c,'disconnect');});}
  return {command,subscribe,tick,publish,cleanup,rooms,get adminBoostActive(){return adminBoostActive;}};
}
